"""
Django management command to upload career data from HTML .txt files to the database.
This command reads .txt files generated by the convert_docx_to_html.py script and
updates or creates Career records in the database.
"""

import os
import re
from pathlib import Path
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from django.utils.text import slugify
from bs4 import BeautifulSoup
from careers.models import Career, CareerCluster, Profession
from core import choices


class Command(BaseCommand):
    help = 'Upload career data from HTML .txt files to the database'

    def add_arguments(self, parser):
        parser.add_argument(
            '--input-dir',
            type=str,
            default='career_html_output',
            help='Directory containing the .txt files (default: career_html_output)'
        )
        parser.add_argument(
            '--dry-run',
            action='store_true',
            help='Run without making database changes (preview mode)'
        )
        parser.add_argument(
            '--limit',
            type=int,
            help='Limit the number of files to process (for testing)'
        )

    def handle(self, *args, **options):
        input_dir = options['input_dir']
        dry_run = options['dry_run']
        limit = options.get('limit', None)
        
        if not os.path.exists(input_dir):
            raise CommandError(f'Input directory does not exist: {input_dir}')
        
        self.stdout.write(
            self.style.SUCCESS(f'Starting career upload from: {input_dir}')
        )
        
        if dry_run:
            self.stdout.write(
                self.style.WARNING('DRY RUN MODE - No database changes will be made')
            )
        
        if limit:
            self.stdout.write(f'Processing only first {limit} files')
        
        # Process all .txt files
        stats = self.process_txt_files(input_dir, dry_run, limit)
        
        # Print summary
        self.print_summary(stats, dry_run)

    # ------------------------ helpers ------------------------
    def _generate_unique_slug(self, model_cls, base_slug):
        """Generate a unique slug including soft-deleted rows.

        Uses the model manager's complete() if available; otherwise falls back to _base_manager.
        """
        # choose a manager that doesn't filter out soft-deleted rows
        if hasattr(model_cls.objects, 'complete'):
            mgr = model_cls.objects.complete()
        else:
            mgr = model_cls._base_manager
        slug = base_slug
        i = 2
        while mgr.filter(slug=slug).exists():
            slug = f"{base_slug}-{i}"
            i += 1
        return slug

    def process_txt_files(self, input_dir, dry_run, limit=None):
        """Process all .txt files in the input directory."""
        input_path = Path(input_dir)
        txt_files = list(input_path.rglob("*.txt"))
        
        # Apply limit if specified
        if limit:
            txt_files = txt_files[:limit]
        
        self.stdout.write(f'Found {len(txt_files)} .txt files to process')
        
        stats = {
            'total_files': len(txt_files),
            'processed': 0,
            'updated': 0,
            'created': 0,
            'errors': 0,
            'error_details': [],
            'clusters_created': 0,
            'clusters_found': 0,
            'professions_created': 0,
            'professions_found': 0
        }
        
        for txt_file in txt_files:
            try:
                result = self.process_single_file(txt_file, dry_run)
                stats['processed'] += 1
                
                if result['action'] == 'updated':
                    stats['updated'] += 1
                    if result.get('cluster_created', False):
                        stats['clusters_created'] += 1
                    else:
                        stats['clusters_found'] += 1
                    stats['professions_created'] += result.get('professions_created', 0)
                    stats['professions_found'] += result.get('professions_found', 0)
                elif result['action'] == 'created':
                    stats['created'] += 1
                    if result.get('cluster_created', False):
                        stats['clusters_created'] += 1
                    else:
                        stats['clusters_found'] += 1
                    stats['professions_created'] += result.get('professions_created', 0)
                    stats['professions_found'] += result.get('professions_found', 0)
                elif result['action'] == 'error':
                    stats['errors'] += 1
                    stats['error_details'].append(result['error'])
                
            except Exception as e:
                stats['errors'] += 1
                stats['error_details'].append(f"{txt_file}: {str(e)}")
                self.stdout.write(
                    self.style.ERROR(f'Error processing {txt_file}: {str(e)}')
                )
        
        return stats

    def process_single_file(self, txt_file, dry_run):
        """Process a single .txt file and update/create career record."""
        try:
            # Read HTML content from file
            with open(txt_file, 'r', encoding='utf-8') as f:
                html_content = f.read().strip()
            
            if not html_content:
                return {'action': 'error', 'error': f'{txt_file}: Empty file'}
            
            # Extract career name from title tag or filename
            career_name = self.extract_career_name_from_content(html_content, txt_file.stem)
            
            # Extract summary and description
            summary, description = self.extract_summary_and_description(html_content)
            
            if not summary and not description:
                return {'action': 'error', 'error': f'{txt_file}: No content extracted'}
            
            # Get or create career cluster from folder name
            career_cluster, cluster_created = self.get_or_create_career_cluster_from_path(txt_file, dry_run)
            
            # Find or create career
            career = Career.objects.filter(name__iexact=career_name).first()
            
            if career:
                # Update existing career
                if not dry_run:
                    with transaction.atomic():
                        career.summary = summary
                        career.description = description
                        # Add career cluster if not already associated
                        if career_cluster and career_cluster not in career.career_cluster.all():
                            career.career_cluster.add(career_cluster)
                        career.save()

                # Upsert professions from description HTML
                prof_stats = self.upsert_professions_from_html(career, html_content, dry_run)

                self.stdout.write(f'✓ Updated: {career_name} (Cluster: {career_cluster.name if career_cluster else "None"})')
                return {
                    'action': 'updated',
                    'career': career,
                    'cluster_created': cluster_created,
                    **prof_stats,
                }
            
            else:
                # Create new career
                if not dry_run:
                    with transaction.atomic():
                        career = Career.objects.create(
                            name=career_name,
                            summary=summary,
                            description=description,
                            slug=slugify(career_name),
                            publish_status=choices.PublishStatus.DRAFT
                            # Note: image field is optional - default will be used via get_image_url()
                        )
                        # Add career cluster
                        if career_cluster:
                            career.career_cluster.add(career_cluster)

                # Upsert professions from description HTML
                prof_stats = self.upsert_professions_from_html(career, html_content, dry_run)

                self.stdout.write(f'✓ Created: {career_name} (Cluster: {career_cluster.name if career_cluster else "None"})')
                return {
                    'action': 'created',
                    'career': career,
                    'cluster_created': cluster_created,
                    **prof_stats,
                }
                
        except Exception as e:
            return {'action': 'error', 'error': f'{txt_file}: {str(e)}'}

    def extract_career_name_from_content(self, html_content, filename):
        """
        Extract career name from title tag or use filename as fallback.
        
        Args:
            html_content (str): HTML content of the document
            filename (str): Filename without extension
            
        Returns:
            str: Career name
        """
        try:
            # Parse HTML with BeautifulSoup
            soup = BeautifulSoup(html_content, 'html.parser')
            
            # Look for title tag
            title_tag = soup.find('title')
            if title_tag:
                career_name = title_tag.get_text().strip()
                if career_name:
                    return career_name
            
            # Fallback to filename
            return filename
            
        except Exception as e:
            # Fallback to filename
            return filename

    def extract_summary_and_description(self, html_content):
        """
        Extract summary (first paragraph after title) and full description from HTML content.
        
        Args:
            html_content (str): HTML content of the document
            
        Returns:
            tuple: (summary, description) where summary is truncated to 250 chars
        """
        try:
            # Parse HTML with BeautifulSoup
            soup = BeautifulSoup(html_content, 'html.parser')
            
            # Find first paragraph for summary (skip title tag)
            first_p = soup.find('p')
            summary = ""
            if first_p:
                # Get text content and strip HTML tags
                summary = first_p.get_text().strip()
                # Truncate to 250 characters
                if len(summary) > 250:
                    summary = summary[:247] + "..."
            
            # Use full HTML content as description
            description = html_content
            
            return summary, description
            
        except Exception as e:
            # Fallback: use raw content
            lines = html_content.split('\n')
            first_line = lines[0] if lines else ""
            
            # Simple text extraction for summary
            summary = re.sub(r'<[^>]+>', '', first_line).strip()
            if len(summary) > 250:
                summary = summary[:247] + "..."
            
            return summary, html_content

    def get_or_create_career_cluster_from_path(self, txt_file, dry_run):
        """
        Extract folder name from file path and create/get CareerCluster.
        
        Args:
            txt_file (Path): Path to the .txt file
            dry_run (bool): Whether this is a dry run
            
        Returns:
            tuple: (CareerCluster, cluster_created) where cluster_created is bool
        """
        try:
            # Get the parent directory name (folder name)
            folder_name = txt_file.parent.name

            # Skip if it's the root directory
            if folder_name == 'career_html_output':
                return None, False

            # Clean up folder name (remove extra spaces)
            cluster_name = folder_name.strip()
            cluster_slug = slugify(cluster_name)

            # Try by slug first to avoid duplicate slug IntegrityError (include soft-deleted)
            complete_mgr = CareerCluster.objects.complete() if hasattr(CareerCluster.objects, 'complete') else CareerCluster._base_manager
            career_cluster = complete_mgr.filter(slug=cluster_slug).first()

            if not career_cluster:
                # Try by name (case-insensitive)
                career_cluster = complete_mgr.filter(name__iexact=cluster_name).first()

            cluster_created = False

            if not career_cluster:
                if dry_run:
                    self.stdout.write(f'  → Would create Career Cluster: {cluster_name}')
                    return None, True
                # Create with explicit slug; if another process created it, reuse
                try:
                    unique_slug = self._generate_unique_slug(CareerCluster, cluster_slug)
                    career_cluster = CareerCluster.objects.create(
                        name=cluster_name,
                        slug=unique_slug,
                        object_status=choices.ObjectStatus.ACTIVE
                    )
                    cluster_created = True
                    self.stdout.write(f'  → Created Career Cluster: {cluster_name}')
                except Exception as e:
                    # Likely duplicate slug; fetch existing by slug and proceed
                    existing = complete_mgr.filter(slug=cluster_slug).first()
                    if existing:
                        career_cluster = existing
                        # Reactivate if soft-deleted
                        if getattr(career_cluster, 'object_status', None) == choices.ObjectStatus.DELETED:
                            career_cluster.object_status = choices.ObjectStatus.ACTIVE
                            career_cluster.save(update_fields=['object_status','modified'])
                    else:
                        # As last resort, try by iexact name again
                        career_cluster = complete_mgr.filter(name__iexact=cluster_name).first()
                        if not career_cluster:
                            # Log and skip linking cluster
                            self.stdout.write(self.style.ERROR(
                                f'Error creating career cluster for {txt_file}: {str(e)}'
                            ))
                            return None, False

            return career_cluster, cluster_created

        except Exception as e:
            self.stdout.write(
                self.style.ERROR(f'Error creating career cluster for {txt_file}: {str(e)}')
            )
            return None, False

    # ===================== PROFESSIONS EXTRACTION/UPSERT =====================
    def upsert_professions_from_html(self, career, html_content, dry_run):
        """Extract "Leading Professions" list from HTML and upsert Profession rows.

        - Avoid duplicates by name per career (case-insensitive)
        - Store the remaining description of each <li> as Profession.summary
        - As salary is required but not present, default to 0
        """
        try:
            names_and_summaries = self.extract_leading_professions(html_content)
            created = 0
            found = 0
            if not names_and_summaries:
                return {'professions_created': 0, 'professions_found': 0}
            for name, summary in names_and_summaries:
                # Deduplicate within the same career
                existing = Profession.objects.filter(career=career, name__iexact=name).first()
                if existing:
                    # Update summary if empty and we have one
                    if summary and (not existing.summary):
                        if not dry_run:
                            existing.summary = summary
                            existing.save(update_fields=[ 'summary', 'modified' ])
                    found += 1
                    continue
                if dry_run:
                    created += 1
                    continue
                Profession.objects.create(
                    career=career,
                    name=name,
                    summary=summary or "",
                    salary=0,
                )
                created += 1
            if created or found:
                self.stdout.write(f"  → Professions: +{created}, existing {found}")
            return {'professions_created': created, 'professions_found': found}
        except Exception as e:
            self.stdout.write(self.style.ERROR(f"  → Profession extraction error: {e}"))
            return {'professions_created': 0, 'professions_found': 0}

    def extract_leading_professions(self, html_content):
        """Return list of tuples (name, summary) parsed from the 'Leading Professions' section.

        We look for a heading whose text contains 'Leading Profession' (case-insensitive),
        then capture the immediately following <ul>/<ol> and all <li> until the next heading.
        For each <li>, if there is a <strong> at the start, that text becomes the profession
        name; otherwise, we take text up to the first ':' or ' - ' as the name. The rest is
        used as the summary.
        """
        soup = BeautifulSoup(html_content, 'html.parser')
        heading = None
        for tag in soup.find_all([ 'h1','h2','h3','h4','h5','h6','p' ]):
            text = (tag.get_text() or '').strip().lower()
            if 'leading profession' in text or 'leading professions' in text:
                heading = tag
                break
        if not heading:
            return []
        # find the list following the heading
        ul = None
        nxt = heading
        # walk next siblings until ul/ol or break on new heading
        while True:
            nxt = nxt.find_next_sibling()
            if nxt is None:
                break
            if nxt.name in [ 'h1','h2','h3','h4','h5','h6' ]:
                break
            if nxt.name in [ 'ul','ol' ]:
                ul = nxt
                break
        if not ul:
            # Fallback: collect bullet-like paragraphs until next heading
            results = []
            nxt = heading
            while True:
                nxt = nxt.find_next_sibling()
                if nxt is None:
                    break
                if nxt.name in [ 'h1','h2','h3','h4','h5','h6' ]:
                    break
                if nxt.name == 'p':
                    line = nxt.get_text(" ", strip=True)
                    if not line:
                        continue
                    # Heuristics: treat as bullet if starts with common bullet chars or numbering
                    if re.match(r'^(?:[\u2022\u25CF\u25E6\u2043\-\*\+]|\d+[\.)]|[A-Za-z][\.)])\s+', line):
                        # try to split name/summary similar to above
                        parts = re.split(r'\s*[:\-–—]\s*', line, maxsplit=1)
                        name = parts[0].strip()
                        summary = parts[1].strip() if len(parts) > 1 else ''
                        # remove leading bullet marker from name
                        name = re.sub(r'^(?:[\u2022\u25CF\u25E6\u2043\-\*\+]|\d+[\.)]|[A-Za-z][\.)])\s+', '', name)
                        if name:
                            results.append((name, summary))
            return results
        results = []
        for li in ul.find_all('li'):
            name = None
            summary = ''
            # Prefer bold/strong leading name
            strong = li.find('strong')
            if strong and strong.get_text(strip=True):
                name = strong.get_text(strip=True)
                # summary is remaining text after the strong
                # remove the strong tag and get the remaining text
                strong.extract()
                remaining = li.get_text(" ", strip=True)
                # drop leading punctuation like ':' or '-' if present
                remaining = re.sub(r'^[\s:\-–—]+', '', remaining)
                summary = remaining
            else:
                full = li.get_text(" ", strip=True)
                # split on ':' or '-' for name vs summary
                parts = re.split(r'\s*[:\-–—]\s*', full, maxsplit=1)
                if parts:
                    name = parts[0].strip()
                    if len(parts) > 1:
                        summary = parts[1].strip()
            if name:
                # Normalize whitespace
                name = re.sub(r'\s+', ' ', name)
                results.append((name, summary))
        return results

    def print_summary(self, stats, dry_run):
        """Print processing summary."""
        self.stdout.write('\n' + '='*50)
        self.stdout.write(self.style.SUCCESS('CAREER UPLOAD SUMMARY'))
        self.stdout.write('='*50)
        
        if dry_run:
            self.stdout.write(self.style.WARNING('DRY RUN - No changes were made to database'))
        
        self.stdout.write(f'Total files found: {stats["total_files"]}')
        self.stdout.write(f'Files processed: {stats["processed"]}')
        self.stdout.write(f'Careers updated: {stats["updated"]}')
        self.stdout.write(f'Careers created: {stats["created"]}')
        self.stdout.write(f'Career clusters created: {stats["clusters_created"]}')
        self.stdout.write(f'Career clusters found (existing): {stats["clusters_found"]}')
        self.stdout.write(f'Professions created: {stats["professions_created"]}')
        self.stdout.write(f'Professions found (existing): {stats["professions_found"]}')
        self.stdout.write(f'Errors: {stats["errors"]}')
        
        if stats['error_details']:
            self.stdout.write('\n' + self.style.ERROR('ERRORS:'))
            for error in stats['error_details']:
                self.stdout.write(f'  - {error}')
        
        self.stdout.write('\n' + self.style.SUCCESS('Upload completed!'))
