# Generated by Django 4.2.23 on 2025-12-18 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtracurricularActivityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('icon_class', models.CharField(default='bx bx-star', help_text="Boxicons class, e.g. 'bx bx-brain', 'bx bx-football'", max_length=120)),
                ('css_class', models.CharField(blank=True, default='', help_text="Optional extra CSS class for the card wrapper, e.g. 'academic', 'sports', 'arts'.", max_length=120)),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Lower comes first')),
            ],
            options={
                'verbose_name': 'Extracurricular Category',
                'verbose_name_plural': 'Extracurricular Categories',
                'ordering': ('priority', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtracurricularActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, help_text='Optional external link', null=True)),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Lower comes first')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.extracurricularactivitycategory')),
            ],
            options={
                'verbose_name': 'Extracurricular Activity',
                'verbose_name_plural': 'Extracurricular Activities',
                'ordering': ('priority', 'name'),
                'abstract': False,
            },
        ),
    ]
