# Generated by Django 4.2.23 on 2025-12-18 10:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_extracurricular_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracurricularactivity',
            name='content_html',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Optional detailed content (HTML) for the activity detail page', null=True),
        ),
        migrations.AddField(
            model_name='extracurricularactivity',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
