# Generated by Django 4.2.23 on 2025-12-18 11:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_extracurricular_activity_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocationalCourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Lower comes first')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.vocationalcoursecategory')),
            ],
            options={
                'verbose_name': 'Vocational Course Category',
                'verbose_name_plural': 'Vocational Course Categories',
                'ordering': ('priority', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VocationalCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('content_html', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Lower comes first')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.vocationalcoursecategory')),
            ],
            options={
                'verbose_name': 'Vocational Course',
                'verbose_name_plural': 'Vocational Courses',
                'ordering': ('priority', 'name'),
                'abstract': False,
            },
        ),
    ]
