# Generated by Django 4.2.23 on 2025-12-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vocational_courses_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracurricularactivitycategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/core/extracurricular/category/'),
        ),
        migrations.AddField(
            model_name='vocationalcoursecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/core/vocational/category/'),
        ),
    ]
