# Generated by Django 4.2.23 on 2025-12-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracurricularactivity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/core/extracurricular/activity/'),
        ),
        migrations.AddField(
            model_name='vocationalcourse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/core/vocational/course/'),
        ),
    ]
