# Generated by Django 4.2.23 on 2025-12-20 06:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_item_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtracurricularActivitySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('section_id', models.CharField(help_text='Standard section ID: objectives, participation, keyskills, etc.', max_length=50)),
                ('title', models.CharField(help_text="Section title (e.g., 'Objectives & Goals')", max_length=300)),
                ('content_html', ckeditor.fields.RichTextField(help_text='HTML content for this section')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Display order')),
                ('icon', models.CharField(default='bx-target-lock', help_text='Boxicons class for navigation icon', max_length=50)),
                ('description', models.CharField(blank=True, help_text="Short description for navigation (e.g., 'Academic excellence, critical thinking')", max_length=200)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.extracurricularactivity')),
            ],
            options={
                'verbose_name': 'Extracurricular Activity Section',
                'verbose_name_plural': 'Extracurricular Activity Sections',
                'ordering': ('order',),
                'abstract': False,
                'unique_together': {('activity', 'section_id')},
            },
        ),
    ]
