# Generated by Django 4.2.23 on 2026-01-10 11:27

import core.models
from django.db import migrations, models, connection


def create_ebook_table_if_not_exist(apps, schema_editor):
    """Create ebook table only if it doesn't exist"""
    table_name = 'core_ebook'
    
    with connection.cursor() as cursor:
        if connection.vendor == 'mysql':
            # Check if table exists
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.tables 
                WHERE table_schema = DATABASE() 
                AND table_name = %s
            """, [table_name])
            table_exists = cursor.fetchone()[0] > 0
            
            # If table exists, do nothing - state_operations will update Django's state
            if table_exists:
                return
        elif connection.vendor == 'postgresql':
            # Check if table exists
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = %s
            """, [table_name])
            table_exists = cursor.fetchone()[0] > 0
            
            if table_exists:
                return
    
    # If we reach here, table doesn't exist and we need to create it
    # Since we can't use apps.get_model (state hasn't been created yet),
    # we'll create a temporary model class and use schema_editor.create_model
    from django.db import models as django_models
    
    # Create Ebook model
    class EbookModel(django_models.Model):
        created = django_models.DateTimeField(auto_now_add=True)
        modified = django_models.DateTimeField(auto_now=True)
        object_status = django_models.SmallIntegerField(
            choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')],
            default=1
        )
        publish_status = django_models.SmallIntegerField(
            choices=[(0, 'Draft'), (1, 'Published')],
            db_index=True,
            default=1
        )
        title = django_models.CharField(max_length=300, help_text='Title of the ebook')
        description = django_models.TextField(blank=True, help_text='Description of the ebook', null=True)
        cover_image = django_models.ImageField(
            help_text='Cover image for the ebook (recommended size: 400x600px)',
            upload_to=core.models.ebook_cover_directory
        )
        pdf_file = django_models.FileField(
            help_text='PDF file of the ebook',
            upload_to=core.models.ebook_pdf_directory
        )
        priority = django_models.PositiveSmallIntegerField(
            default=1,
            help_text='Lower number appears first in listing'
        )
        slug = django_models.SlugField(blank=True, max_length=300, null=True, unique=True)
        
        class Meta:
            db_table = 'core_ebook'
            verbose_name = 'Ebook'
            verbose_name_plural = 'Ebooks'
            ordering = ('priority', 'title')
    
    # Create table using schema editor
    try:
        schema_editor.create_model(EbookModel)
    except Exception:
        pass  # Table might have been created concurrently


def reverse_create_ebook_table(apps, schema_editor):
    """Reverse migration - drop table if it exists"""
    with connection.cursor() as cursor:
        try:
            if connection.vendor == 'mysql':
                cursor.execute("DROP TABLE IF EXISTS core_ebook")
            else:
                cursor.execute("DROP TABLE IF EXISTS core_ebook")
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_extracurricularactivitysection'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_ebook_table_if_not_exist,
                    reverse_create_ebook_table,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Ebook',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created', models.DateTimeField(auto_now_add=True)),
                        ('modified', models.DateTimeField(auto_now=True)),
                        ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                        ('publish_status', models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], db_index=True, default=1)),
                        ('title', models.CharField(help_text='Title of the ebook', max_length=300)),
                        ('description', models.TextField(blank=True, help_text='Description of the ebook', null=True)),
                        ('cover_image', models.ImageField(help_text='Cover image for the ebook (recommended size: 400x600px)', upload_to=core.models.ebook_cover_directory)),
                        ('pdf_file', models.FileField(help_text='PDF file of the ebook', upload_to=core.models.ebook_pdf_directory)),
                        ('priority', models.PositiveSmallIntegerField(default=1, help_text='Lower number appears first in listing')),
                        ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                    ],
                    options={
                        'verbose_name': 'Ebook',
                        'verbose_name_plural': 'Ebooks',
                        'ordering': ('priority', 'title'),
                        'abstract': False,
                    },
                ),
            ],
        ),
    ]
