# Generated by Django 4.2.23 on 2026-01-10 12:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='S3 bucket URL for cover image (alternative to file upload)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ebook',
            name='pdf_file_url',
            field=models.URLField(blank=True, help_text='S3 bucket URL for PDF file (alternative to file upload)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image for the ebook (recommended size: 400x600px). Leave empty if using S3 URL.', null=True, upload_to=core.models.ebook_cover_directory),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='PDF file of the ebook. Leave empty if using S3 URL.', null=True, upload_to=core.models.ebook_pdf_directory),
        ),
    ]
