# Generated by Django 4.2.23 on 2026-01-10 12:06

from django.db import migrations, models, connection


def remove_and_add_fields_safely(apps, schema_editor):
    """Remove old fields and add new S3 URL fields only if they don't exist"""
    db_alias = schema_editor.connection.alias
    table_name = 'core_ebook'
    
    with connection.cursor() as cursor:
        if connection.vendor == 'mysql':
            # Remove old fields if they exist
            old_fields = ['cover_image_url', 'pdf_file_url']
            for field_name in old_fields:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM information_schema.columns 
                    WHERE table_schema = DATABASE() 
                    AND table_name = %s
                    AND column_name = %s
                """, [table_name, field_name])
                if cursor.fetchone()[0] > 0:
                    try:
                        cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN {field_name}")
                    except Exception:
                        pass  # Column might not exist or already removed
            
            # Add new S3 URL fields if they don't exist
            new_fields = [
                ('cover_image_s3_url', 'S3 URL for cover image (e.g., https://topteenc.s3.ap-northeast-1.amazonaws.com/ebook/cover/image.jpg). Leave empty if uploading file.'),
                ('pdf_file_s3_url', 'S3 URL for PDF file (e.g., https://topteenc.s3.ap-northeast-1.amazonaws.com/ebook/pdf/book.pdf). Leave empty if uploading file.'),
            ]
            
            for field_name, help_text in new_fields:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM information_schema.columns 
                    WHERE table_schema = DATABASE() 
                    AND table_name = %s
                    AND column_name = %s
                """, [table_name, field_name])
                column_exists = cursor.fetchone()[0] > 0
                
                if not column_exists:
                    try:
                        cursor.execute(f"""
                            ALTER TABLE {table_name} 
                            ADD COLUMN {field_name} VARCHAR(500) NULL
                        """)
                    except Exception:
                        pass  # Column might have been created concurrently
                        
        elif connection.vendor == 'postgresql':
            # Remove old fields if they exist
            old_fields = ['cover_image_url', 'pdf_file_url']
            for field_name in old_fields:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM information_schema.columns 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                    AND column_name = %s
                """, [table_name, field_name])
                if cursor.fetchone()[0] > 0:
                    try:
                        cursor.execute(f'ALTER TABLE {table_name} DROP COLUMN "{field_name}"')
                    except Exception:
                        pass
            
            # Add new S3 URL fields if they don't exist
            new_fields = [
                ('cover_image_s3_url', 'S3 URL for cover image (e.g., https://topteenc.s3.ap-northeast-1.amazonaws.com/ebook/cover/image.jpg). Leave empty if uploading file.'),
                ('pdf_file_s3_url', 'S3 URL for PDF file (e.g., https://topteenc.s3.ap-northeast-1.amazonaws.com/ebook/pdf/book.pdf). Leave empty if uploading file.'),
            ]
            
            for field_name, help_text in new_fields:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM information_schema.columns 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                    AND column_name = %s
                """, [table_name, field_name])
                column_exists = cursor.fetchone()[0] > 0
                
                if not column_exists:
                    try:
                        cursor.execute(f"""
                            ALTER TABLE {table_name} 
                            ADD COLUMN {field_name} VARCHAR(500) NULL
                        """)
                    except Exception:
                        pass
        else:
            # SQLite or other databases
            old_fields = ['cover_image_url', 'pdf_file_url']
            for field_name in old_fields:
                try:
                    cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN {field_name}")
                except Exception:
                    pass
            
            new_fields = ['cover_image_s3_url', 'pdf_file_s3_url']
            for field_name in new_fields:
                try:
                    cursor.execute(f"""
                        ALTER TABLE {table_name} 
                        ADD COLUMN {field_name} VARCHAR(500) NULL
                    """)
                except Exception:
                    pass  # Column already exists, skip


def reverse_remove_and_add_fields(apps, schema_editor):
    """Reverse migration - remove S3 URL fields and restore old fields"""
    table_name = 'core_ebook'
    with connection.cursor() as cursor:
        # Remove new S3 URL fields
        new_fields = ['cover_image_s3_url', 'pdf_file_s3_url']
        for field_name in new_fields:
            try:
                if connection.vendor == 'mysql':
                    cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN {field_name}")
                elif connection.vendor == 'postgresql':
                    cursor.execute(f'ALTER TABLE {table_name} DROP COLUMN "{field_name}"')
                else:
                    pass  # SQLite doesn't support DROP COLUMN easily
            except Exception:
                pass
        
        # Restore old fields (if needed)
        old_fields = ['cover_image_url', 'pdf_file_url']
        for field_name in old_fields:
            try:
                cursor.execute(f"""
                    ALTER TABLE {table_name} 
                    ADD COLUMN {field_name} VARCHAR(500) NULL
                """)
            except Exception:
                pass  # Column might already exist


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ebook_cover_image_url_ebook_pdf_file_url_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    remove_and_add_fields_safely,
                    reverse_remove_and_add_fields,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='ebook',
                    name='cover_image_url',
                ),
                migrations.RemoveField(
                    model_name='ebook',
                    name='pdf_file_url',
                ),
                migrations.AddField(
                    model_name='ebook',
                    name='cover_image_s3_url',
                    field=models.URLField(blank=True, help_text='S3 URL for cover image (e.g., https://topteenc.s3.ap-northeast-1.amazonaws.com/ebook/cover/image.jpg). Leave empty if uploading file.', max_length=500, null=True),
                ),
                migrations.AddField(
                    model_name='ebook',
                    name='pdf_file_s3_url',
                    field=models.URLField(blank=True, help_text='S3 URL for PDF file (e.g., https://topteenc.s3.ap-northeast-1.amazonaws.com/ebook/pdf/book.pdf). Leave empty if uploading file.', max_length=500, null=True),
                ),
            ],
        ),
    ]
