# Generated by Django 4.2.23 on 2026-01-10 12:31

from django.db import migrations, models, connection


def create_s3fileupload_table_if_not_exist(apps, schema_editor):
    """Create s3fileupload table only if it doesn't exist"""
    table_name = 'core_s3fileupload'
    
    with connection.cursor() as cursor:
        if connection.vendor == 'mysql':
            # Check if table exists
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.tables 
                WHERE table_schema = DATABASE() 
                AND table_name = %s
            """, [table_name])
            table_exists = cursor.fetchone()[0] > 0
            
            # If table exists, do nothing - state_operations will update Django's state
            if table_exists:
                return
        elif connection.vendor == 'postgresql':
            # Check if table exists
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = %s
            """, [table_name])
            table_exists = cursor.fetchone()[0] > 0
            
            if table_exists:
                return
    
    # If we reach here, table doesn't exist and we need to create it
    # Since we can't use apps.get_model (state hasn't been created yet),
    # we'll create a temporary model class and use schema_editor.create_model
    from django.db import models as django_models
    
    # Create S3FileUpload model
    class S3FileUploadModel(django_models.Model):
        created = django_models.DateTimeField(auto_now_add=True)
        modified = django_models.DateTimeField(auto_now=True)
        object_status = django_models.SmallIntegerField(
            choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')],
            default=1
        )
        file_name = django_models.CharField(max_length=500, help_text='Original file name')
        s3_key = django_models.CharField(max_length=1000, help_text='S3 object key/path')
        s3_url = django_models.URLField(max_length=1000, help_text='Full S3 URL')
        file_type = django_models.CharField(
            blank=True,
            help_text='File MIME type',
            max_length=100,
            null=True
        )
        file_size = django_models.PositiveIntegerField(
            blank=True,
            help_text='File size in bytes',
            null=True
        )
        folder_path = django_models.CharField(
            blank=True,
            help_text='Folder path in S3',
            max_length=500,
            null=True
        )
        description = django_models.TextField(
            blank=True,
            help_text='Optional description',
            null=True
        )
        uploaded_by = django_models.CharField(
            blank=True,
            help_text='User who uploaded the file',
            max_length=200,
            null=True
        )
        
        class Meta:
            db_table = 'core_s3fileupload'
            verbose_name = 'S3 File Upload'
            verbose_name_plural = 'S3 File Uploads'
            ordering = ('-created',)
    
    # Create table using schema editor
    try:
        schema_editor.create_model(S3FileUploadModel)
    except Exception:
        pass  # Table might have been created concurrently


def reverse_create_s3fileupload_table(apps, schema_editor):
    """Reverse migration - drop table if it exists"""
    with connection.cursor() as cursor:
        try:
            if connection.vendor == 'mysql':
                cursor.execute("DROP TABLE IF EXISTS core_s3fileupload")
            else:
                cursor.execute("DROP TABLE IF EXISTS core_s3fileupload")
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_ebook_cover_image_url_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_s3fileupload_table_if_not_exist,
                    reverse_create_s3fileupload_table,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='S3FileUpload',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created', models.DateTimeField(auto_now_add=True)),
                        ('modified', models.DateTimeField(auto_now=True)),
                        ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                        ('file_name', models.CharField(help_text='Original file name', max_length=500)),
                        ('s3_key', models.CharField(help_text='S3 object key/path', max_length=1000)),
                        ('s3_url', models.URLField(help_text='Full S3 URL', max_length=1000)),
                        ('file_type', models.CharField(blank=True, help_text='File MIME type', max_length=100, null=True)),
                        ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                        ('folder_path', models.CharField(blank=True, help_text='Folder path in S3', max_length=500, null=True)),
                        ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                        ('uploaded_by', models.CharField(blank=True, help_text='User who uploaded the file', max_length=200, null=True)),
                    ],
                    options={
                        'verbose_name': 'S3 File Upload',
                        'verbose_name_plural': 'S3 File Uploads',
                        'ordering': ('-created',),
                        'abstract': False,
                    },
                ),
            ],
        ),
    ]
