# Generated by Django 4.2.23 on 2026-01-14 07:05

from django.db import migrations, models, connection


def add_content_json_field_safely(apps, schema_editor):
    """Add content_json column only if it doesn't exist"""
    table_name = 'core_vocationalcourse'
    column_name = 'content_json'
    
    with connection.cursor() as cursor:
        if connection.vendor == 'mysql':
            # Check if column exists
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.columns 
                WHERE table_schema = DATABASE() 
                AND table_name = %s
                AND column_name = %s
            """, [table_name, column_name])
            column_exists = cursor.fetchone()[0] > 0
            
            if not column_exists:
                try:
                    cursor.execute(f"""
                        ALTER TABLE {table_name} 
                        ADD COLUMN {column_name} JSON NULL
                    """)
                except Exception:
                    pass  # Column might have been created concurrently
        elif connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = %s
                AND column_name = %s
            """, [table_name, column_name])
            column_exists = cursor.fetchone()[0] > 0
            
            if not column_exists:
                try:
                    cursor.execute(f"""
                        ALTER TABLE {table_name} 
                        ADD COLUMN {column_name} JSONB NULL
                    """)
                except Exception:
                    pass
        else:
            # SQLite or other databases
            try:
                cursor.execute(f"""
                    ALTER TABLE {table_name} 
                    ADD COLUMN {column_name} TEXT NULL
                """)
            except Exception:
                pass  # Column already exists, skip


def reverse_add_content_json_field(apps, schema_editor):
    """Reverse migration - remove content_json column if it exists"""
    table_name = 'core_vocationalcourse'
    column_name = 'content_json'
    
    with connection.cursor() as cursor:
        try:
            if connection.vendor == 'mysql':
                cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN {column_name}")
            elif connection.vendor == 'postgresql':
                cursor.execute(f'ALTER TABLE {table_name} DROP COLUMN "{column_name}"')
            else:
                pass  # SQLite doesn't support DROP COLUMN easily
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_s3fileupload'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_content_json_field_safely,
                    reverse_add_content_json_field,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='vocationalcourse',
                    name='content_json',
                    field=models.JSONField(blank=True, help_text='Stored JSON structure parsed from content_html field with fixed accordion sections', null=True),
                ),
            ],
        ),
    ]
