# Generated by Django 4.2.23 on 2026-02-07 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_four_pillars_assessment_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourPillarsAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL slug, e.g. engagement-patterns', max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=512)),
                ('scoring_intro', models.TextField(blank=True, help_text='Intro text for the Scoring Guide (e.g. How to Calculate Your Score).')),
                ('mixed_results', models.TextField(blank=True, help_text='Text for dual/balanced/multi-modal patterns.')),
                ('is_active', models.BooleanField(default=True, help_text='If True, assessment content is loaded from DB. If False, falls back to JSON file.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='FourPillarsAssessmentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0-based).')),
                ('title', models.CharField(help_text='e.g. Question 1: Energy Source', max_length=255)),
                ('text', models.TextField(help_text='Question text shown to the user.')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.fourpillarsassessment')),
            ],
            options={
                'ordering': ['assessment', 'order'],
                'unique_together': {('assessment', 'order')},
            },
        ),
        migrations.CreateModel(
            name='FourPillarsAssessmentQuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.fourpillarsassessmentquestion')),
            ],
            options={
                'ordering': ['question', 'option_key'],
                'unique_together': {('question', 'option_key')},
            },
        ),
        migrations.CreateModel(
            name='FourPillarsAssessmentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('name', models.CharField(help_text='Short profile name, e.g. Goal-Oriented Achiever', max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('scoring_heading', models.CharField(blank=True, max_length=512)),
                ('scoring_bullets', models.JSONField(default=list, help_text='List of bullet strings for the Scoring Guide card.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.fourpillarsassessment')),
            ],
            options={
                'ordering': ['assessment', 'option_key'],
                'unique_together': {('assessment', 'option_key')},
            },
        ),
    ]
