# Generated by Django 4.2.23 on 2026-02-07 05:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_four_pillars_assessment_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourpillarsassessmentprofile',
            name='scoring_heading',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Heading for the Scoring Guide card. Use the editor for formatting.'),
        ),
        migrations.AlterField(
            model_name='fourpillarsassessmentprofile',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Profile summary. Use the editor for formatting.'),
        ),
        migrations.AlterField(
            model_name='fourpillarsassessmentquestion',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='Question text shown to the user. Use the editor for formatting (bold, lists, etc.).'),
        ),
        migrations.AlterField(
            model_name='fourpillarsassessmentquestionoption',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='Option text. Use the editor for formatting.'),
        ),
    ]
