# Generated by Django 4.2.23 on 2026-02-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_four_pillars_richtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourPillarsAssessmentScoringGuide',
            fields=[
            ],
            options={
                'verbose_name': 'Four Pillars Scoring Guide',
                'verbose_name_plural': 'Four Pillars Scoring Guides',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.fourpillarsassessment',),
        ),
        migrations.AlterField(
            model_name='fourpillarsassessmentquestion',
            name='text',
            field=models.TextField(help_text='Question text shown to the user.'),
        ),
        migrations.AlterField(
            model_name='fourpillarsassessmentquestionoption',
            name='text',
            field=models.TextField(),
        ),
    ]
