# Generated by Django 4.2.23 on 2026-02-07 06:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_four_pillars_questions_plain_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourpillarsassessment',
            name='mixed_results',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Text for dual/balanced/multi-modal patterns (mixed results note). Use the editor for formatting.'),
        ),
        migrations.AlterField(
            model_name='fourpillarsassessment',
            name='scoring_intro',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Intro text for the Scoring Guide (e.g. How to Calculate Your Score). Use the editor for formatting.'),
        ),
    ]
