# Generated by Django 4.2.23 on 2026-02-07 08:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_scoring_guide_richtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourpillarsassessment',
            name='guide_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Full guide content (Understanding Your Profile, Primary patterns, Combination patterns, etc.). When set, this is shown instead of the static template. Use the editor for formatting.'),
        ),
    ]
