# Generated by Django 4.2.23 on 2026-02-16 05:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_mi_eq_assessment_results'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['priority', 'created'], 'verbose_name': 'Student testimonial', 'verbose_name_plural': 'Student testimonials'},
        ),
        migrations.AddField(
            model_name='review',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1, help_text='Display order on home page (1 = first). Lower number = higher position.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.review_image_directory),
        ),
    ]
