# Generated by Django 4.2.23 on 2026-02-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_review_student_testimonial_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_s3_url',
            field=models.URLField(blank=True, help_text='S3 URL for testimonial photo (auto-set when uploading image in admin).', max_length=500, null=True),
        ),
    ]
