# Generated by Django 4.2.23 on 2026-02-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_review_image_s3_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='quote',
            field=models.CharField(blank=True, help_text='Short quote or headline shown above the full testimonial (avoids repeating the start of description).', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(help_text='Full testimonial text shown below the quote.'),
        ),
    ]
