# Generated by Django 4.2.23 on 2026-02-16 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_review_quote_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerBattleFight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "Stream A vs Stream B"', max_length=255)),
                ('streams', models.JSONField(default=list)),
                ('parameters', models.JSONField(default=list)),
                ('result', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_battle_fights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Career Battle Fight',
                'verbose_name_plural': 'Career Battle Fights',
                'ordering': ['-created'],
            },
        ),
    ]
