# Generated by Django 4.2.23 on 2026-02-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_career_battle_fight'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerbattlefight',
            name='cluster_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
