# Generated by Django 4.2.23 on 2026-02-16 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0027_career_battle_fight_cluster_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerBattleEligibilityProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_background', models.CharField(blank=True, default='', max_length=64)),
                ('stream', models.CharField(blank=True, default='', max_length=64)),
                ('specific_area', models.CharField(blank=True, default='', max_length=128)),
                ('study_location', models.CharField(blank=True, default='', max_length=64)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_battle_eligibility_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Career Battle Eligibility Profile',
                'verbose_name_plural': 'Career Battle Eligibility Profiles',
            },
        ),
    ]
