# Generated by Django 4.2.23 on 2026-02-16 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_career_battle_eligibility_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('first_message_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('crisis_flagged', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Counselling Session',
                'verbose_name_plural': 'Counselling Sessions',
                'ordering': ['-last_message_at'],
            },
        ),
    ]
