# Generated by Django 4.2.23 on 2026-02-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_counselling_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, help_text='1 is higher than 2'),
        ),
        migrations.AddIndex(
            model_name='commonfaq',
            index=models.Index(fields=['user_type', 'is_featured', 'priority'], name='core_common_user_ty_7b69a6_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['publish_status', 'priority'], name='core_review_publish_783dbd_idx'),
        ),
    ]
