# Generated by Django 4.2.23 on 2026-02-26 11:32

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_db_indexes_optimize_queries'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('value', models.PositiveSmallIntegerField(db_index=True, help_text='Numeric grade value, e.g. 6..12', unique=True)),
                ('label', models.CharField(help_text="Display label, e.g. 'Class 10'", max_length=64)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Master Class',
                'verbose_name_plural': 'Master Classes',
                'ordering': ('-value',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_key', models.CharField(db_index=True, help_text='Stable id: url_name e.g. core:aboutus or url_key e.g. about', max_length=120, unique=True)),
                ('title', models.CharField(blank=True, help_text='SEO title (50–60 chars recommended)', max_length=70, validators=[django.core.validators.MaxLengthValidator(70)])),
                ('description', models.CharField(blank=True, help_text='Meta description (150–160 chars recommended)', max_length=300, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('keywords', models.CharField(blank=True, help_text='Optional comma-separated keywords', max_length=500)),
                ('og_image', models.URLField(blank=True, help_text='Open Graph image URL', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Page SEO',
                'ordering': ['url_key'],
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_key', models.CharField(db_index=True, help_text='Stable id matching the route, e.g. terms, about, career_planning', max_length=80, unique=True)),
                ('title', models.CharField(blank=True, help_text='Optional in-page heading', max_length=255)),
                ('content_html', ckeditor.fields.RichTextField(blank=True, help_text='Main body HTML. Rendered when present; otherwise template uses default.')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Static Page (CMS)',
                'verbose_name_plural': 'Static Pages (CMS)',
                'ordering': ['url_key'],
            },
        ),
        migrations.CreateModel(
            name='StaticPageSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(help_text='Standard section ID, e.g. our_story, team', max_length=80)),
                ('title', models.CharField(help_text='Section title', max_length=255)),
                ('content_html', ckeditor.fields.RichTextField(help_text='HTML content for this section')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Display order')),
                ('static_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.staticpage')),
            ],
            options={
                'verbose_name': 'Static Page Section',
                'verbose_name_plural': 'Static Page Sections',
                'ordering': ['static_page', 'order'],
                'unique_together': {('static_page', 'section_id')},
            },
        ),
    ]
