# Generated by Django 4.2.23 on 2026-02-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_seed_static_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='content_json',
            field=models.JSONField(blank=True, help_text='Structured content as JSON. When set, edit form shows dynamic fields (text, textarea, image) and frontend can render from this.', null=True),
        ),
    ]
