# Generated by Django 4.2.23 on 2026-02-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_static_page_content_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL path segment, e.g. my-landing → /page/my-landing/', max_length=120, unique=True)),
                ('title', models.CharField(help_text='Page title (heading and SEO)', max_length=255)),
                ('content_html', models.TextField(blank=True, help_text='Main body HTML extracted from the source page')),
                ('content_css', models.TextField(blank=True, help_text='CSS to inject in the page (from source <style> and linked stylesheets)')),
                ('content_js', models.TextField(blank=True, help_text='JavaScript to inject at end of page (from source <script> and linked scripts)')),
                ('source_url', models.URLField(blank=True, help_text='URL this page was imported from', max_length=2000)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Generated Page (from URL)',
                'verbose_name_plural': 'Generated Pages (from URL)',
                'ordering': ['-created'],
            },
        ),
    ]
