# Generated by Django 4.2.23 on 2026-02-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_generated_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='content_css',
            field=models.TextField(blank=True, help_text='Optional CSS injected in the page when rendering (edit via Edit HTML/CSS/JS).'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='content_js',
            field=models.TextField(blank=True, help_text='Optional JavaScript injected at end of page when rendering (edit via Edit HTML/CSS/JS).'),
        ),
    ]
