# Generated by Django 4.2.23 on 2026-02-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_static_page_css_js'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLevelBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, e.g. Rookie, Explorer', max_length=64)),
                ('min_points', models.PositiveIntegerField(default=0, help_text='Minimum total points for this level')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Sort order; higher = higher level')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Level Band',
                'verbose_name_plural': 'Dashboard Level Bands',
                'ordering': ['order', 'min_points'],
            },
        ),
        migrations.CreateModel(
            name='DashboardPointRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_key', models.CharField(db_index=True, help_text='e.g. profile_complete, test1_complete, psychometric_test_completed', max_length=80)),
                ('points', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Point Rule',
                'verbose_name_plural': 'Dashboard Point Rules',
                'ordering': ['rule_key'],
            },
        ),
        migrations.CreateModel(
            name='DashboardStreakConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_source', models.CharField(choices=[('UserActivity', 'UserActivity (page views)'), ('UserEvent', 'UserEvent (events)')], default='UserActivity', help_text="Which model to use for 'activity' in streak calculation", max_length=32)),
                ('event_types', models.CharField(blank=True, help_text='Comma-separated event_type values if source=UserEvent (e.g. page_view,psychometric_test_completed). Empty = all events.', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Streak Config',
                'verbose_name_plural': 'Dashboard Streak Config',
            },
        ),
        migrations.CreateModel(
            name='DashboardTrophyDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_key', models.CharField(db_index=True, help_text='Same keys as point rules; condition must be true to count', max_length=80)),
                ('label', models.CharField(blank=True, help_text='Admin display label', max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Trophy Definition',
                'verbose_name_plural': 'Dashboard Trophy Definitions',
                'ordering': ['rule_key'],
            },
        ),
        migrations.DeleteModel(
            name='GeneratedPage',
        ),
        migrations.DeleteModel(
            name='PageSEO',
        ),
        migrations.AlterUniqueTogether(
            name='staticpagesection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='staticpagesection',
            name='static_page',
        ),
        migrations.DeleteModel(
            name='StaticPage',
        ),
        migrations.DeleteModel(
            name='StaticPageSection',
        ),
    ]
