# Generated by Django 4.2.23 on 2026-03-07 09:22

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_seed_dashboard_stats_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL path segment, e.g. my-landing → /page/my-landing/', max_length=120, unique=True)),
                ('title', models.CharField(help_text='Page title (heading and SEO)', max_length=255)),
                ('content_html', models.TextField(blank=True, help_text='Main body HTML extracted from the source page')),
                ('content_css', models.TextField(blank=True, help_text='CSS to inject in the page')),
                ('content_js', models.TextField(blank=True, help_text='JavaScript to inject at end of page')),
                ('source_url', models.URLField(blank=True, help_text='URL this page was imported from', max_length=2000)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Generated Page (from URL)',
                'verbose_name_plural': 'Generated Pages (from URL)',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_key', models.CharField(db_index=True, help_text='Stable id: url_name e.g. core:aboutus or url_key e.g. about', max_length=120, unique=True)),
                ('title', models.CharField(blank=True, help_text='SEO title (50–60 chars recommended)', max_length=70, validators=[django.core.validators.MaxLengthValidator(70)])),
                ('description', models.CharField(blank=True, help_text='Meta description (150–160 chars recommended)', max_length=300, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('keywords', models.CharField(blank=True, help_text='Optional comma-separated keywords', max_length=500)),
                ('og_image', models.URLField(blank=True, help_text='Open Graph image URL', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Page SEO',
                'ordering': ['url_key'],
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_key', models.CharField(db_index=True, help_text='Stable id matching the route, e.g. terms, about, career_planning', max_length=80, unique=True)),
                ('title', models.CharField(blank=True, help_text='Optional in-page heading', max_length=255)),
                ('content_html', ckeditor.fields.RichTextField(blank=True, help_text='Main body HTML. Rendered when present; otherwise template uses default.')),
                ('content_json', models.JSONField(blank=True, help_text='Structured content as JSON. When set, edit form shows dynamic fields (text, textarea, image) and frontend can render from this.', null=True)),
                ('content_css', models.TextField(blank=True, help_text='Optional CSS injected in the page when rendering (edit via Edit HTML/CSS/JS).')),
                ('content_js', models.TextField(blank=True, help_text='Optional JavaScript injected at end of page when rendering (edit via Edit HTML/CSS/JS).')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Static Page (CMS)',
                'verbose_name_plural': 'Static Pages (CMS)',
                'ordering': ['url_key'],
            },
        ),
        migrations.CreateModel(
            name='StaticPageSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(help_text='Standard section ID, e.g. our_story, team', max_length=80)),
                ('title', models.CharField(help_text='Section title', max_length=255)),
                ('content_html', ckeditor.fields.RichTextField(help_text='HTML content for this section')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Display order')),
                ('static_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.staticpage')),
            ],
            options={
                'verbose_name': 'Static Page Section',
                'verbose_name_plural': 'Static Page Sections',
                'ordering': ['static_page', 'order'],
                'unique_together': {('static_page', 'section_id')},
            },
        ),
    ]
