# Generated by Django 4.2.23 on 2026-03-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_generatedpage_pageseo_staticpage_staticpagesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.CharField(db_index=True, help_text='URL path without domain (e.g. careers/software-engineer)', max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True, help_text='Last time this URL was seen in a scan')),
            ],
            options={
                'verbose_name': 'Scanned URL',
                'verbose_name_plural': 'Scanned URLs',
                'ordering': ['url_path'],
            },
        ),
    ]
