# Generated by Django 4.2.23 on 2026-03-16 07:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_scanned_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceTestPrepCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Lower comes first')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/core/entrance_test_prep/category/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.entrancetestprepcategory')),
            ],
            options={
                'verbose_name': 'Entrance Test Prep Category',
                'verbose_name_plural': 'Entrance Test Prep Categories',
                'ordering': ('priority', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntranceTestPrepExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/core/entrance_test_prep/exam/')),
                ('content_html', ckeditor.fields.RichTextField(blank=True, help_text='Full HTML content or used when no sections', null=True)),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Lower comes first')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.entrancetestprepcategory')),
            ],
            options={
                'verbose_name': 'Entrance Test Prep Exam',
                'verbose_name_plural': 'Entrance Test Prep Exams',
                'ordering': ('priority', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntranceTestPrepExamSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('section_id', models.CharField(help_text='Slug for anchor, e.g. overview, eligibility', max_length=80)),
                ('title', models.CharField(help_text='Section title (e.g. Overview)', max_length=300)),
                ('content_html', ckeditor.fields.RichTextField(help_text='HTML content for this section')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Display order')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.entrancetestprepexam')),
            ],
            options={
                'verbose_name': 'Entrance Test Prep Exam Section',
                'verbose_name_plural': 'Entrance Test Prep Exam Sections',
                'ordering': ('order',),
                'abstract': False,
                'unique_together': {('exam', 'section_id')},
            },
        ),
    ]
