# Generated by Django 4.2.23 on 2026-03-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_entrance_test_prep_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancetestprepexam',
            name='content_json',
            field=models.JSONField(blank=True, help_text='Stored JSON structure parsed from content_html (programtitle, overview, sections) for accordion display', null=True),
        ),
    ]
