# Generated by Django 4.2.23 on 2026-03-17 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0041_add_entrancetestprepexam_content_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancetestprepexam',
            name='shortlist',
            field=models.ManyToManyField(blank=True, help_text='Users who bookmarked this exam.', related_name='entrance_test_prep_exam_shortlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
