# Generated by Django 4.2.23 on 2026-03-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_entrance_exam_accordion_validation_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocationalcourse',
            name='accordion_validation_checked_at',
            field=models.DateTimeField(blank=True, help_text='When accordion validation was last run and saved.', null=True),
        ),
        migrations.AddField(
            model_name='vocationalcourse',
            name='accordion_validation_has_errors',
            field=models.BooleanField(db_index=True, default=False, help_text='True if last validation found issues.'),
        ),
        migrations.AddField(
            model_name='vocationalcourse',
            name='accordion_validation_issues',
            field=models.JSONField(blank=True, default=list, help_text='Last stored validation messages (blank sections, etc.). Updated by Validate accordion.'),
        ),
    ]
