# Generated by Django 4.2.23 on 2026-03-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_vocational_course_accordion_validation_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLIndexRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional admin label for this rule', max_length=120)),
                ('path_pattern', models.CharField(db_index=True, help_text='Examples: /private-page/ (exact), /student/ (prefix), ^/reports/.*/$ (regex)', max_length=255)),
                ('match_type', models.CharField(choices=[('exact', 'Exact path'), ('prefix', 'Path starts with'), ('regex', 'Regex pattern')], default='prefix', max_length=10)),
                ('apply_in_robots', models.BooleanField(default=True, help_text='Add this pattern as a Disallow line in robots.txt')),
                ('apply_x_robots_tag', models.BooleanField(default=True, help_text='Add X-Robots-Tag: noindex, nofollow on matched responses')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'URL Index Rule',
                'verbose_name_plural': 'URL Index Rules',
                'ordering': ['path_pattern'],
            },
        ),
    ]
