# Generated by Django 4.0.4 on 2026-06-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_vocational_course_reasoning_mapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalconfiguration',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical configuration'},
        ),
        migrations.AlterField(
            model_name='dashboardpointrule',
            name='rule_key',
            field=models.CharField(db_index=True, help_text='e.g. registration, profile_complete, payment_success, personality_test_complete, motivation_test_complete, interest_test_complete, aptitude_test_complete, report_reading', max_length=80),
        ),
        migrations.AddField(
            model_name='dashboardpointrule',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display order in admin and dashboard (lower = first)'),
        ),
        migrations.AlterModelOptions(
            name='dashboardpointrule',
            options={'ordering': ['order', 'rule_key'], 'verbose_name': 'Dashboard Point Rule', 'verbose_name_plural': 'Dashboard Point Rules'},
        ),
        migrations.AlterField(
            model_name='historicalconfiguration',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
