# Generated by Django 4.0.4 on 2026-06-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_dashboard_point_rule_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardlevelband',
            name='min_points',
            field=models.PositiveIntegerField(default=0, help_text='Minimum total points for this level. Must be a cumulative milestone from active point rules (minimum = account registration, maximum = rules total).'),
        ),
    ]
