# Generated by Django 4.0.4 on 2026-06-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_dashboardlevelband_min_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardpointrule',
            name='applies_to',
            field=models.CharField(choices=[('all', 'All students'), ('class10', 'Class 10 and below'), ('post_matric', 'Class 11–12+')], default='all', help_text='Which student grade track can earn points from this rule.', max_length=20),
        ),
        migrations.AddField(
            model_name='dashboardtrophydefinition',
            name='applies_to',
            field=models.CharField(blank=True, choices=[('all', 'All students'), ('class10', 'Class 10 and below'), ('post_matric', 'Class 11–12+')], default='', help_text='Blank uses the matching Dashboard Point Rule applies-to setting.', max_length=20),
        ),
    ]
