# Generated by Django 4.2.23 on 2026-07-22 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0052_dashboardpointrule_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalconfiguration',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical configuration', 'verbose_name_plural': 'historical configurations'},
        ),
        migrations.AlterField(
            model_name='dashboardpointrule',
            name='rule_key',
            field=models.CharField(db_index=True, help_text='e.g. registration, profile_complete, payment_success, personality_test_complete, motivation_test_complete, interest_test_complete, aptitude_test_complete, report_reading, emotional_complete, Multiple Intelligence, Decision Making, Refer a Friend, Skill Lab Course Payment, Skill Lab Course Completion', max_length=80),
        ),
        migrations.AlterField(
            model_name='historicalconfiguration',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.CreateModel(
            name='LLMUsageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('forum', 'Forum Q&A'), ('resume_v2', 'Resume V2'), ('resume_guided', 'Resume Guided'), ('seo', 'SEO AI meta'), ('careers_search', 'Careers semantic search'), ('careers_embedding', 'Careers embeddings'), ('translation', 'Reading-level translation'), ('other', 'Other')], db_index=True, max_length=64)),
                ('provider', models.CharField(db_index=True, help_text='openai, gemini, anthropic, …', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('call_type', models.CharField(default='chat', help_text='chat, embedding, or other', max_length=32)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM usage log',
                'verbose_name_plural': 'LLM usage logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'feature'], name='core_llmusa_created_2d220d_idx'), models.Index(fields=['provider', 'model'], name='core_llmusa_provide_9a4f7d_idx')],
            },
        ),
    ]
