# Generated by Django 4.2.23 on 2026-07-22 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0053_llm_usage_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMRoleQuotaDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.CharField(choices=[('staff', 'Staff / SEO (is_staff)'), ('student', 'Student'), ('institute', 'Institute'), ('institute_group_admin', 'Institute group admin'), ('counselor', 'Counselor'), ('marketing_group_admin', 'Marketing group admin'), ('parent', 'Parent'), ('anonymous', 'Anonymous (not logged in)')], max_length=40, unique=True)),
                ('monthly_free_tokens', models.PositiveIntegerField(default=0, help_text='Free tokens granted each calendar month for this role. Admin can also grant extra.')),
                ('estimated_call_tokens', models.PositiveIntegerField(default=2000, help_text='Pre-check reserve per LLM call when exact size is unknown.')),
                ('is_enabled', models.BooleanField(default=True, help_text='If disabled, this role cannot use paid LLM features until admin enables + grants.')),
                ('marketing_headline', models.CharField(blank=True, default='', max_length=160)),
                ('marketing_body', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM role quota default',
                'verbose_name_plural': 'LLM role quota defaults',
                'ordering': ('role_key',),
            },
        ),
        migrations.CreateModel(
            name='LLMTokenPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('currency', models.PositiveSmallIntegerField(choices=[(0, 'US Dollar'), (1, 'IND Rupees / INR')], default=1)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('tagline', models.CharField(blank=True, default='', help_text='Short marketing line shown on the paywall (e.g. "Unlock 5 more polished resumes").', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('tokens', models.PositiveIntegerField(help_text='Number of AI tokens credited on successful purchase.')),
                ('badge_label', models.CharField(blank=True, default='', help_text='Optional badge, e.g. Most popular / Best value.', max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'LLM token package',
                'verbose_name_plural': 'LLM token packages',
                'ordering': ('sort_order', 'amount', 'id'),
            },
        ),
        migrations.CreateModel(
            name='UserLLMWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_tokens', models.BigIntegerField(default=0)),
                ('lifetime_credited', models.BigIntegerField(default=0)),
                ('lifetime_consumed', models.BigIntegerField(default=0)),
                ('free_period_key', models.CharField(blank=True, default='', help_text='YYYY-MM of last monthly free credit.', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User LLM wallet',
                'verbose_name_plural': 'User LLM wallets',
            },
        ),
        migrations.CreateModel(
            name='LLMAdminGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_grants_issued', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_admin_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM admin grant',
                'verbose_name_plural': 'LLM admin grants',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LLMWalletLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=16)),
                ('source', models.CharField(choices=[('free_monthly', 'Monthly free allowance'), ('purchase', 'Package purchase'), ('admin_grant', 'Admin grant'), ('usage', 'LLM usage'), ('adjustment', 'Manual adjustment')], max_length=32)),
                ('tokens', models.BigIntegerField(help_text='Absolute token amount (always positive).')),
                ('balance_after', models.BigIntegerField()),
                ('feature', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('reference', models.CharField(blank=True, db_index=True, default='', help_text='Idempotency key (payment id, grant id, usage log id).', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_ledger_actions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.userllmwallet')),
            ],
            options={
                'verbose_name': 'LLM wallet ledger',
                'verbose_name_plural': 'LLM wallet ledger',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='core_llmwal_wallet__45393b_idx'), models.Index(fields=['source', 'reference'], name='core_llmwal_source_82b7fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='LLMTokenPackagePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('currency', models.PositiveSmallIntegerField(choices=[(0, 'US Dollar'), (1, 'IND Rupees / INR')], default=1)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('tokens_granted', models.PositiveIntegerField(default=0, help_text='Snapshot of package tokens at purchase time.')),
                ('gateway_receipt', models.CharField(blank=True, max_length=120, null=True)),
                ('is_success', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], db_index=True, default=0)),
                ('tokens_credited', models.BooleanField(default=False, help_text='True after wallet credit (idempotent fulfillment).')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.llmtokenpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_package_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM package payment',
                'verbose_name_plural': 'LLM package payments',
                'indexes': [models.Index(fields=['user', 'is_success'], name='core_llmtok_user_id_a5cc02_idx')],
            },
        ),
    ]
