# Generated by Django 4.2.23 on 2026-07-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_llm_freemium_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMPricingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_inr_rate', models.DecimalField(decimal_places=4, default=83, help_text='Current USD to INR rate used when converting package USD prices for payment.', max_digits=10)),
                ('show_conversion_note', models.BooleanField(default=True, help_text='When enabled, the conversion note is shown on the AI token shop and receipts.')),
                ('conversion_note', models.TextField(blank=True, default='AI model usage is billed by providers in US Dollars (USD). Token packs are sold in Indian Rupees (INR) using the current USD→INR rate set by TopTeen at the time of purchase. The rate used is saved on your receipt.', help_text='Shown to users when "show conversion note" is enabled.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM pricing settings (USD→INR)',
                'verbose_name_plural': 'LLM pricing settings (USD→INR)',
            },
        ),
        migrations.AlterModelOptions(
            name='llmtokenpackage',
            options={'ordering': ('sort_order', 'price_usd', 'id'), 'verbose_name': 'LLM token package', 'verbose_name_plural': 'LLM token packages'},
        ),
        migrations.AddField(
            model_name='llmtokenpackage',
            name='price_usd',
            field=models.DecimalField(decimal_places=4, default=0, help_text='List price in USD. INR charged at checkout = price_usd × current USD→INR rate.', max_digits=10),
        ),
        migrations.AddField(
            model_name='llmtokenpackagepayment',
            name='price_usd',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Package USD list price snapshot at purchase.', max_digits=10),
        ),
        migrations.AddField(
            model_name='llmtokenpackagepayment',
            name='usd_to_inr_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='USD→INR rate used to compute INR charge at purchase.', max_digits=10),
        ),
    ]
