# Generated by Django 4.2.23 on 2026-07-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_llm_usd_inr_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmpricingsettings',
            name='show_exchange_rate',
            field=models.BooleanField(default=True, help_text='Show the current 1 USD = ₹ rate on the shop and receipts.'),
        ),
        migrations.AddField(
            model_name='llmpricingsettings',
            name='show_price_inr',
            field=models.BooleanField(default=True, help_text='Show INR price on the AI token shop, paywall, and checkout.'),
        ),
        migrations.AddField(
            model_name='llmpricingsettings',
            name='show_price_usd',
            field=models.BooleanField(default=True, help_text='Show USD price on the AI token shop, paywall, and checkout.'),
        ),
        migrations.AlterField(
            model_name='llmpricingsettings',
            name='show_conversion_note',
            field=models.BooleanField(default=True, help_text='Show the LLM USD-INR conversion note on the AI token shop and receipts.'),
        ),
    ]
