# Generated by Django 4.2.23 on 2026-07-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_llm_pricing_display_toggles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmpricingsettings',
            options={'verbose_name': 'LLM pricing settings (USD-INR)', 'verbose_name_plural': 'LLM pricing settings (USD-INR)'},
        ),
        migrations.AddField(
            model_name='llmtokenpackage',
            name='usage_examples',
            field=models.TextField(blank=True, default='', help_text='Buyer-friendly use cases, one per line. Shown on the shop instead of raw tech jargon. Example:\nBuild 1 AI resume\nAsk ~10 AI tutor / career chat questions\nTry reading-level simplify a few times'),
        ),
        migrations.AlterField(
            model_name='llmtokenpackage',
            name='tokens',
            field=models.PositiveIntegerField(help_text='Number of AI tokens credited on successful purchase (internal wallet credit).'),
        ),
    ]
