# Generated by Django 4.2.23 on 2026-07-23 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0057_llm_package_usage_examples'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFeatureQuotaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_free_creates', models.PositiveIntegerField(default=1, help_text='Free resume creates for students/parents.')),
                ('resume_free_ai_edits', models.PositiveIntegerField(default=2, help_text='Free AI generation/edit actions for students/parents.')),
                ('counsellor_message_limit', models.PositiveIntegerField(blank=True, help_text='Max AI Counselor messages for students/parents. Empty or 0 = unlimited.', null=True)),
                ('page_chat_message_limit', models.PositiveIntegerField(blank=True, help_text='Max Chat-with-page messages for students/parents. Empty or 0 = unlimited.', null=True)),
                ('purchase_bonus_resume_creates', models.PositiveIntegerField(default=1, help_text='Extra resume creates granted on each AI token pack purchase.')),
                ('purchase_bonus_resume_ai', models.PositiveIntegerField(default=10, help_text='Extra resume AI edits granted on each AI token pack purchase.')),
                ('purchase_bonus_counsellor', models.PositiveIntegerField(default=100, help_text='Extra AI Counselor messages granted on each AI token pack purchase.')),
                ('purchase_bonus_page_chat', models.PositiveIntegerField(default=100, help_text='Extra Chat-with-page messages granted on each AI token pack purchase.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI feature quota settings',
                'verbose_name_plural': 'AI feature quota settings',
            },
        ),
        migrations.CreateModel(
            name='UserAIFeatureUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_creates_used', models.PositiveIntegerField(default=0)),
                ('resume_ai_edits_used', models.PositiveIntegerField(default=0)),
                ('counsellor_messages_used', models.PositiveIntegerField(default=0)),
                ('page_chat_messages_used', models.PositiveIntegerField(default=0)),
                ('resume_create_bonus', models.PositiveIntegerField(default=0)),
                ('resume_ai_bonus', models.PositiveIntegerField(default=0)),
                ('counsellor_bonus', models.PositiveIntegerField(default=0)),
                ('page_chat_bonus', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feature_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User AI feature usage',
                'verbose_name_plural': 'User AI feature usage',
            },
        ),
    ]
