"""
Django settings for topteens project.

Generated by 'django-admin startproject' using Django 2.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/ 
"""

import os
import logging.handlers
import socket
from pathlib import Path
from decouple import config
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='(&yw*5eqsx-tkz^&kvlxx8donayimg&kee=*1nmkxlmor0$q^9')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,testserver,www.topteen.in,test.topteen.in').split(',')
# Dev tunnels (iPhone Safari testing when LAN/AP isolation blocks http://10.x:8002)
if str(config('ENVIRONMENT', default='production')).lower() in ('development', 'staging', 'demo'):
    for _h in ('.ngrok-free.app', '.ngrok-free.dev', '.ngrok.app', '.ngrok.io', '.loca.lt'):
        if _h not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_h)

# Student localStorage payload encryption (for chatbot decryption use same key)
# Generate a key: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
STUDENT_DATA_ENCRYPTION_KEY = config('STUDENT_DATA_ENCRYPTION_KEY', default='')


# Application definition

INSTALLED_APPS = [
    'storages',
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'ckeditor',
    'ckeditor_uploader',
    'nested_inline',
    'django_filters',
    'django_extensions',
    'rest_framework',
    # 'django_unused_media',
    'core',
    'gamification.apps.GamificationConfig',
    'skilllab',
    'users',
    'careers.apps.CareersConfig',
    'topteenadmin',
    'colleges',
    'courses',
    'entrance_exams',
    'blog',
    'communication',
    'social_django',
    'psychometric_tests',
    'payments',
    'crm',
    'institute',
    'app',
    'counselor',
    'course_mindmap',
    'nested_admin',
    'analytics_dashboard',
    'app_post_matric',
    'user_analytics',
    'forum',
    'demo_data',
    'invoices',
    'seo_dashboard',
    'notifications.apps.NotificationsConfig',
    'loan_desk.apps.LoanDeskConfig',
]

# Optional services: set False in .env when not running (avoids errors, uses fallbacks)
ENABLE_REDIS = config('ENABLE_REDIS', default=True, cast=bool)
ENABLE_CELERY = config('ENABLE_CELERY', default=True, cast=bool)

# Service monitor identity: match THIS project's Docker compose / host env (ignore other apps on same host).
# Compose names default to {COMPOSE_PROJECT_NAME}-{service}-1 e.g. topteens-celery-1
COMPOSE_PROJECT_NAME = (config('COMPOSE_PROJECT_NAME', default='topteens') or 'topteens').strip()
DOCKER_IMAGE = (config('DOCKER_IMAGE', default='developertopteen/demotopteen') or 'developertopteen/demotopteen').strip()
DOCKER_IMAGE_NGINX = (
    config('DOCKER_IMAGE_NGINX', default='developertopteen/demotopteen-nginx') or 'developertopteen/demotopteen-nginx'
).strip()
APP_PORT = config('APP_PORT', default='80')
HTTPS_PORT = config('HTTPS_PORT', default='443')
# Celery Django app module used on CLI: celery -A topteens
SERVICE_MONITOR_CELERY_APP = (config('SERVICE_MONITOR_CELERY_APP', default='topteens') or 'topteens').strip()
SERVICE_MONITOR_GUNICORN_MODULE = (
    config('SERVICE_MONITOR_GUNICORN_MODULE', default='topteens.wsgi') or 'topteens.wsgi'
).strip()
# Comma-separated supervisor program names for env mode (sudo supervisorctl status)
SERVICE_MONITOR_SUPERVISOR_CELERY = config(
    'SERVICE_MONITOR_SUPERVISOR_CELERY', default='celery_worker,celery_beat'
)
SERVICE_MONITOR_SUPERVISOR_GUNICORN = config(
    'SERVICE_MONITOR_SUPERVISOR_GUNICORN', default='gunicorn,gunicorn_topteen,topteens_gunicorn'
)
# Installed-mode (systemd) unit names — first loaded unit wins. Production www uses topteen-in-prod-website.
SERVICE_MONITOR_SYSTEMD_GUNICORN = config(
    'SERVICE_MONITOR_SYSTEMD_GUNICORN',
    default='topteen-in-prod-website,topteen-new-website,gunicorn-topteens',
)
SERVICE_MONITOR_SYSTEMD_CELERY = config(
    'SERVICE_MONITOR_SYSTEMD_CELERY',
    default='celery,celery-worker,topteen-celery,celery_worker',
)
SERVICE_MONITOR_SYSTEMD_REDIS = config(
    'SERVICE_MONITOR_SYSTEMD_REDIS',
    default='redis-server,redis',
)
# Prefix control commands with `sudo -n` (passwordless). Set False if the app user can restart directly.
SERVICE_MONITOR_CONTROL_USE_SUDO = config('SERVICE_MONITOR_CONTROL_USE_SUDO', default=True, cast=bool)

# User analytics: set False in .env to disable all tracking (debugging / manual data clean)
ENABLE_USER_ANALYTICS_TRACKING = config('ENABLE_USER_ANALYTICS_TRACKING', default=True, cast=bool)
# Optional comma-separated URL path prefixes to skip for page/journey tracking (middleware), e.g. "/internal/,/status/"
USER_ANALYTICS_EXTRA_SKIP_PATH_PREFIXES = tuple(
    p.strip() for p in config('USER_ANALYTICS_EXTRA_SKIP_PATH_PREFIXES', default='').split(',') if p.strip()
)
# Allow destructive analytics cleanup (purge-all / domain delete / admin POST). Keep False in production unless needed.
ANALYTICS_CLEANUP_ALLOW_DESTRUCTIVE = config('ANALYTICS_CLEANUP_ALLOW_DESTRUCTIVE', default=False, cast=bool)

# Add django_elasticsearch_dsl conditionally based on environment
ENABLE_ELASTICSEARCH = config('ENABLE_ELASTICSEARCH', default=True, cast=bool)
if ENABLE_ELASTICSEARCH:
    INSTALLED_APPS.append('django_elasticsearch_dsl')

# Indian colleges listing API (canamuni upstream). When enabled, /colleges/ uses this API.
USE_INDIAN_COLLEGES_API = config('USE_INDIAN_COLLEGES_API', default=True, cast=bool)
INDIAN_COLLEGES_API_BASE = config(
    'INDIAN_COLLEGES_API_BASE', default='http://35.154.133.230:8000'
)
INDIAN_COLLEGES_DETAIL_BASE = config(
    'INDIAN_COLLEGES_DETAIL_BASE', default='http://35.154.133.230:5173'
)

# AI Features Configuration (Optional - defaults to False)
ENABLE_AI_FEATURES = config('ENABLE_AI_FEATURES', default=False, cast=bool)
ENABLE_AI_SUMMARIES = config('ENABLE_AI_SUMMARIES', default=False, cast=bool)
ENABLE_SEMANTIC_SEARCH = config('ENABLE_SEMANTIC_SEARCH', default=False, cast=bool)

# AI Provider Configuration (only used if ENABLE_AI_FEATURES=True or ENABLE_SEMANTIC_SEARCH=True)
AI_PROVIDER = config('AI_PROVIDER', default='none')  # openai, gemini, anthropic, local, none
OPENAI_API_KEY = config('OPENAI_API_KEY', default='')
GOOGLE_API_KEY = config('GOOGLE_API_KEY', default='')
GOOGLE_MAPS_API_KEY = config('GOOGLE_MAPS_API_KEY', default='')
GOOGLE_CSE_ID = config('GOOGLE_CSE_ID', default='')  # Programmable Search Engine ID for resume suggestions
ANTHROPIC_API_KEY = config('ANTHROPIC_API_KEY', default='')
AI_MODEL = config('AI_MODEL', default='gpt-3.5-turbo')  # or gemini-1.5-flash, claude-3-haiku, etc.
GEMINI_MODEL = config('GEMINI_MODEL', default='gemini-1.5-flash')
# INR per 1 USD — compare provider spend vs amount collected on the LLM billing admin page.
USD_TO_INR_RATE = config('USD_TO_INR_RATE', default=84.0, cast=float)

# Forum AI Configuration
OPENAI_MODEL = config('OPENAI_MODEL', default='gpt-4o-mini')  # Default to cost-effective model for forum
USE_DATABASE_CACHE = config('USE_DATABASE_CACHE', default='True', cast=bool)  # Enable database caching for forum
SEMANTIC_SIMILARITY_THRESHOLD = config('SEMANTIC_SIMILARITY_THRESHOLD', default=0.85, cast=float)  # 0.0 to 1.0

# Freetrail: seconds a guest can view ebook/vocational/extracurricular detail before login popup (0 = no freetrail)
FREETRAIL_TIME_SECONDS = config('FREETRAIL_TIME_SECONDS', default=5, cast=int)

# Embedding Cache Configuration
ENABLE_EMBEDDING_CACHE = config('ENABLE_EMBEDDING_CACHE', default=True, cast=bool)
EMBEDDING_CACHE_TTL = config('EMBEDDING_CACHE_TTL', default=86400, cast=int)  # 24 hours
QUERY_EMBEDDING_CACHE_TTL = config('QUERY_EMBEDDING_CACHE_TTL', default=3600, cast=int)  # 1 hour

# Psychometric Test Widget Configuration
# ENABLE_ANSWERING_CAREFULLY_WIDGET: Show "Answering Carefully" / "Rushing Through" widget on test pages (default: True)
ENABLE_ANSWERING_CAREFULLY_WIDGET = config('ENABLE_ANSWERING_CAREFULLY_WIDGET', default=True, cast=bool)
# ENABLE_AUTO_FORWARD: Auto-advance to next question when user selects an answer (default: True)
ENABLE_AUTO_FORWARD = config('ENABLE_AUTO_FORWARD', default=True, cast=bool)
# Voice-to-text: off | browser | openai (Admin → Core website settings overrides).
# Legacy ENABLE_VOICE_TO_TEXT=False maps to off; True maps to browser when mode unset.
VOICE_TO_TEXT_MODE = config('VOICE_TO_TEXT_MODE', default='browser')
ENABLE_VOICE_TO_TEXT = config('ENABLE_VOICE_TO_TEXT', default=True, cast=bool)
OPENAI_TRANSCRIBE_MODEL = config('OPENAI_TRANSCRIBE_MODEL', default='gpt-4o-mini-transcribe')

# Allow same-origin iframes (e.g. Career Battle wrapper embedding /career-battle/app/).
# Still blocks embedding from other sites (clickjacking protection).
X_FRAME_OPTIONS = 'SAMEORIGIN'

MIDDLEWARE = [
    'core.health_check_middleware.HealthCheckMiddleware',  # ALB/ECS health checks; must be first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'core.slash_middleware.AppendSlashRedirectMiddleware',  # Redirect /path to /path/ when /path/ resolves (before catch-all 404)
    'django.middleware.common.CommonMiddleware',
    'core.indexing_middleware.URLIndexingMiddleware',  # Add X-Robots-Tag for admin-blocked URL patterns
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # AJAX: return 401 JSON instead of redirecting XHR to login page HTML (v2 dashboards)
    'core.ajax_auth_middleware.AjaxAuthRedirectMiddleware',
    # After auth: slide session expiry for logged-in users when SAVE_EVERY_REQUEST is False
    'topteens.custome_middleware.SlideSessionForAuthenticatedMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'topteens.admin_template_middleware.AdminTemplateMiddleware',  # Force Django templates for admin
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'topteens.custome_middleware.CustomeSocialAuthExceptionMiddleware',
    'topteens.custome_middleware.TopteenAdminRequireLoginCheck',
    'topteens.custome_middleware.TopteenAdminPermissionMiddleware',
    'user_analytics.middleware.AnalyticsMiddleware',
    'core.seo_middleware.PageSEOMiddleware',  # Merge PageSEO into html_head by request path (all pages)
]


CORS_ALLOWED_ORIGINS = [
    'https://www.topteen.in',
    'http://demo.topteen.in',
    'https://demo.topteen.in',
    'https://topteenc.s3.ap-northeast-1.amazonaws.com',
]
# CloudFront domain is appended after CLOUDFRONT_DOMAIN is resolved (see S3 block below).

CSRF_TRUSTED_ORIGINS = [
    'https://www.topteen.in',
    'http://demo.topteen.in',
    'https://demo.topteen.in',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:8002',
    'http://127.0.0.1:8002',
    'http://10.0.0.93:8000',
    'http://10.0.0.93:8002',
    'http://10.0.0.118:8000',
    'http://10.0.0.118:8002',
]
# Extra CSRF origins from env (comma-separated full origins), e.g. http://192.168.1.10:8002
_extra_csrf = config('CSRF_TRUSTED_ORIGINS_EXTRA', default='', cast=str) or ''
for _origin in [o.strip() for o in _extra_csrf.split(',') if o.strip()]:
    if _origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_origin)
# In development, also trust http(s)://<ALLOWED_HOST> on common local ports (login from phones/LAN).
if str(config('ENVIRONMENT', default='production')).lower() in ('development', 'staging', 'demo'):
    for _host in ALLOWED_HOSTS:
        _host = (_host or '').strip()
        if not _host or _host.startswith('.') or _host == '*':
            continue
        for _port in ('8000', '8002', '8005', '8080'):
            for _scheme in ('http', 'https'):
                _o = f'{_scheme}://{_host}:{_port}'
                if _o not in CSRF_TRUSTED_ORIGINS:
                    CSRF_TRUSTED_ORIGINS.append(_o)
                _o2 = f'{_scheme}://{_host}'
                if _o2 not in CSRF_TRUSTED_ORIGINS:
                    CSRF_TRUSTED_ORIGINS.append(_o2)
    # Wildcard CSRF for ngrok tunnels (Django 4.1+)
    for _wild in (
        'https://*.ngrok-free.app',
        'https://*.ngrok-free.dev',
        'https://*.ngrok.app',
        'https://*.ngrok.io',
    ):
        if _wild not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_wild)

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True # If needed for cookies or auth

# HTTP vs HTTPS - controlled by USE_HTTPS env (True=HTTPS, False=HTTP)
ENVIRONMENT = config('ENVIRONMENT', default='production')
TOPTEEN_SITE_URL = config('TOPTEEN_SITE_URL', default='https://www.topteen.in')
USE_HTTPS = config('USE_HTTPS', default=False, cast=bool)
# Allow HTTP+HTTPS dual access on custom ports (e.g. :8005 and :8443) without
# redirecting http://IP:8005 -> https://IP/ (missing port = blank page).
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=USE_HTTPS, cast=bool)
SESSION_COOKIE_SECURE = USE_HTTPS
CSRF_COOKIE_SECURE = USE_HTTPS
# Keep users signed in during normal browsing (avoid mobile browser clearing session cookies).
SESSION_COOKIE_AGE = config('SESSION_COOKIE_AGE', default=604800, cast=int)  # 7 days
# False = only save when session data changes (much cheaper under load).
# Logged-in sliding expiry is handled by SlideSessionForAuthenticatedMiddleware.
SESSION_SAVE_EVERY_REQUEST = config('SESSION_SAVE_EVERY_REQUEST', default=False, cast=bool)
SESSION_EXPIRE_AT_BROWSER_CLOSE = config('SESSION_EXPIRE_AT_BROWSER_CLOSE', default=False, cast=bool)
SESSION_COOKIE_SAMESITE = config('SESSION_COOKIE_SAMESITE', default='Lax')
SESSION_COOKIE_HTTPONLY = True
# Share login across subdomains (e.g. .topteen.in for www + demo). Leave unset for localhost.
SESSION_COOKIE_DOMAIN = config('SESSION_COOKIE_DOMAIN', default='') or None
SESSION_COOKIE_NAME = config('SESSION_COOKIE_NAME', default='sessionid')
CSRF_COOKIE_SAMESITE = config('CSRF_COOKIE_SAMESITE', default=SESSION_COOKIE_SAMESITE)
_CSRF_COOKIE_DOMAIN = config('CSRF_COOKIE_DOMAIN', default=SESSION_COOKIE_DOMAIN or '')
CSRF_COOKIE_DOMAIN = _CSRF_COOKIE_DOMAIN or None
# Demo/staging hosts need host-only cookies; production SESSION_COOKIE_DOMAIN breaks CSRF there.
if (
    ENVIRONMENT in ('development', 'staging', 'demo')
    or 'demo.topteen.in' in TOPTEEN_SITE_URL.lower()
):
    SESSION_COOKIE_DOMAIN = None
    CSRF_COOKIE_DOMAIN = None
# JSON serializer avoids pickle issues across deploys; signed cookies use SECRET_KEY (HMAC).
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'
DEFAULT_LOGIN_SESSION_AGE = SESSION_COOKIE_AGE
REMEMBER_ME_SESSION_AGE = config('REMEMBER_ME_SESSION_AGE', default=2592000, cast=int)  # 30 days
DEMO_LOGIN_SESSION_AGE = config('DEMO_LOGIN_SESSION_AGE', default=SESSION_COOKIE_AGE, cast=int)
CSRF_FAILURE_VIEW = 'users.views.csrf_failure'
# Honor X-Forwarded-Proto from reverse proxies / ngrok so build_absolute_uri()
# returns https://… after login (iPhone Chrome was getting http:// and failing).
# Safe when only trusted proxies set this header (ngrok, nginx).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = config('USE_X_FORWARDED_HOST', default=True, cast=bool)

ROOT_URLCONF = 'topteens.urls'
# Trailing slash: our AppendSlashRedirectMiddleware redirects /path -> /path/ when /path/ resolves.
# APPEND_SLASH still used by CommonMiddleware for any URL that does not match (e.g. before catch-all).
APPEND_SLASH = True
DEFAULT_AUTO_FIELD='django.db.models.AutoField'
TEMPLATES = [
     {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': ['templates', os.path.join(BASE_DIR, 'frontend')],  # Added frontend directory for Jinja2 templates
        'APP_DIRS': False,  # Disable APP_DIRS - custom loader handles app directories and skips admin templates
        'OPTIONS': {
            'environment': 'topteens.jinja_env.environment',
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'core.context_processors.set_upg_variables',
                'topteens.context_processor.globals',
                'core.ttv2_role_context.ttv2_role_ctx',
                'users.context_processors.student_scrapbook_hub',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),  # Add templates directory for Django admin templates
            os.path.join(BASE_DIR, 'templates1'),
            os.path.join(BASE_DIR, 'frontend'),  # old code not in use - start - New isolated frontend templates
        ],  # old code not in use - end
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.has_payment',
                # Inject master class list for grade/class dropdowns (Django templates)
                'core.context_processors.master_classes_processor',
                # Only ENVIRONMENT=production allows search engine indexing (noindex otherwise)
                'core.context_processors.allow_search_engine_index_processor',
                'topteens.context_processor.globals',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'users.backends.CustomUserBackend',
    'django.contrib.auth.backends.ModelBackend',
    'users.auth.MasterPasswordBackend',  # Custom backend with master password support
)

WSGI_APPLICATION = 'topteens.wsgi.application'

AUTH_USER_MODEL = "users.User"


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'topteens',
#         'USER':'root',
#         'PASSWORD':'root',
#         'HOST':'mariadb',
#         'PORT':'3306',
#         'OPTIONS': {'charset': 'utf8mb4'},
#     }
# }

DB_ENGINE = config('DB_ENGINE', default='django.db.backends.mysql')
DB_NAME = config('DB_NAME', default='topteens')
DB_USER = config('DB_USER', default='root')
DB_PASSWORD = config('DB_PASSWORD', default='')
DB_HOST = config('DB_HOST', default='127.0.0.1')
DB_PORT = config('DB_PORT', default='3306')
DB_CONN_MAX_AGE = config('DB_CONN_MAX_AGE', default=60, cast=int)
DB_AUTO_SQLITE_FALLBACK_DEBUG = config('DB_AUTO_SQLITE_FALLBACK_DEBUG', default=True, cast=bool)
DB_CONNECT_TIMEOUT_SECONDS = config('DB_CONNECT_TIMEOUT_SECONDS', default=2, cast=int)


def _mysql_host_reachable(host: str, port: str, timeout_seconds: int = 2) -> bool:
    try:
        with socket.create_connection((host, int(port)), timeout=timeout_seconds):
            return True
    except Exception:
        return False


if DB_ENGINE == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
else:
    use_sqlite_fallback = False
    if DEBUG and DB_AUTO_SQLITE_FALLBACK_DEBUG:
        # Local developer safety: if configured MySQL host is unreachable,
        # fallback to sqlite so local pages don't crash with OperationalError.
        use_sqlite_fallback = not _mysql_host_reachable(DB_HOST, DB_PORT, DB_CONNECT_TIMEOUT_SECONDS)

    if use_sqlite_fallback:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
            }
        }
    else:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': DB_NAME,
                'USER': DB_USER,
                'PASSWORD': DB_PASSWORD,
                'HOST': DB_HOST,
                'PORT': DB_PORT,
                'CONN_MAX_AGE': DB_CONN_MAX_AGE,
                'OPTIONS': {
                    'charset': 'utf8mb4',
                    # Use UTC for every connection so datetime values are valid (fixes admin date_hierarchy
                    # "invalid datetime / time zone definitions" on MySQL when tz tables are not loaded).
                    'init_command': "SET time_zone = '+00:00'",
                },
            }
        }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'topteen12',
#         'USER':'root12',
#         'PASSWORD':'root12',
#         'HOST':'13.232.70.31',
#         'PORT':'3306',
#         'OPTIONS': {'charset': 'utf8mb4'},
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = config('TIME_ZONE', default='Asia/Kolkata')

USE_I18N = True

USE_L10N = True

USE_TZ = True  # Keep this enabled to handle time zones correctly



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
# Common base path for STATIC_ROOT and MEDIA_ROOT so they are not duplicated per run/env.
# Set COMMON_BASE_PATH in .env to a shared path, or leave unset to use project root (BASE_DIR).
COMMON_BASE_PATH = config('COMMON_BASE_PATH', default=str(BASE_DIR))
if not os.path.isabs(COMMON_BASE_PATH):
    COMMON_BASE_PATH = os.path.normpath(os.path.join(BASE_DIR, COMMON_BASE_PATH))

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(COMMON_BASE_PATH, 'staticfiles')

# Progressive Web App (manifest + service worker)
PWA_ENABLED = config('PWA_ENABLED', default=True, cast=bool)
# Use "auto" to bust caches from git SHA or static file fingerprint (no manual bump per deploy).
PWA_CACHE_VERSION = config('PWA_CACHE_VERSION', default='auto')

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(COMMON_BASE_PATH, 'media')


# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 60,
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Add development specific middleware
# if DEBUG:
#     INSTALLED_APPS += [
#         'debug_toolbar',
#     ]
    
#     MIDDLEWARE = [
#         'debug_toolbar.middleware.DebugToolbarMiddleware',
#     ] + MIDDLEWARE  # Note: Debug toolbar middleware should be as early as possible

#     INTERNAL_IPS = [
#         '127.0.0.1',
#         '10.0.0.93',
#         'localhost',
#     ]

#     DEBUG_TOOLBAR_CONFIG = {
#         'SHOW_TOOLBAR_CALLBACK': lambda request: True,  # Always show toolbar in debug mode
#     }


CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"
CKEDITOR_ALLOW_NONIMAGE_FILES = False
CKEDITOR_UPLOAD_PATH = "cke/uploads/"
CKEDITOR_FILENAME_GENERATOR = 'core.utils.reformat_filename'
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': None,
    },
    'email_template': {
        'toolbar': 'EmailTemplate',
        'toolbar_EmailTemplate': [
            ['Source', '-', 'Bold', 'Italic', 'Underline', 'Strike'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight'],
            ['Link', 'Unlink', '-', 'RemoveFormat'],
            ['Format', 'TextColor', 'BGColor'],
        ],
        'height': 380,
        'width': '100%',
        'allowedContent': True,
        'extraAllowedContent': '*(*);*{*}',
        'removePlugins': 'stylesheetparser',
        'entities': False,
        'basicEntities': False,
        'contentsCss': ['/static/admin/css/email_message_template_ckeditor_contents.css'],
        'bodyClass': 'email-template-editor-body',
        'linkDefaultProtocol': 'http://',
    },
}

# File Upload Settings
# Upload size limits for ebooks
DATA_UPLOAD_MAX_MEMORY_SIZE = 3 * 1024 * 1024  # 3 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 3 * 1024 * 1024  # 3 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240  # Increase if needed

# S3 Bucket Configuration
S3_BUCKET_PREFIX = config('S3_BUCKET_PREFIX', default='s3://topteenc/')
S3_EBOOK_FOLDER = 'ebook'  # Folder path for ebooks in S3
S3_FOUR_PILLARS_FOLDER = config('S3_FOUR_PILLARS_FOLDER', default='four_pillars')  # Folder for Four Pillars of Learning images in S3
# Multiple Intelligences (MI) page: full base URL for MI images in S3 (e.g. https://bucket.s3.region.amazonaws.com/mi/). If unset, uses static/images_new/mi/
S3_MI_IMAGES_BASE_URL = config('S3_MI_IMAGES_BASE_URL', default='')
S3_EQ_IMAGES_BASE_URL = config('S3_EQ_IMAGES_BASE_URL', default='')

# Path to assessment reference docx (MI reports, scoring method, EQ report). Default: sibling topteens html/b.
# 7nov/topteenhtml/html/b (go up from topteen_1.0: parent=new_template-demo-topteens, parent=git, parent=7nov)
_assessment_ref = BASE_DIR.parent.parent.parent / 'topteenhtml' / 'html' / 'b'
_ASSESSMENT_REF_DEFAULT = str(_assessment_ref) if _assessment_ref.exists() else ''
ASSESSMENT_REFERENCE_BASE = config('ASSESSMENT_REFERENCE_BASE', default=_ASSESSMENT_REF_DEFAULT)

# AWS S3 Upload Configuration
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')
AWS_REGION = config('AWS_REGION', default='ap-northeast-1')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME', default='topteenc')

# CloudFront CDN in front of the S3 bucket (optional).
# Set CLOUDFRONT_DOMAIN (or AWS_S3_CUSTOM_DOMAIN) to dxxxx.cloudfront.net or a custom alias (no scheme).
# Then set S3_MEDIA_ACCESS_MODE=cloudfront so FileField/.url and S3_BUCKET_BASE_URL use the CDN.
def _normalize_cdn_domain(raw):
    value = (raw or '').strip()
    for prefix in ('https://', 'http://'):
        if value.lower().startswith(prefix):
            value = value[len(prefix):]
    return value.strip().strip('/')


CLOUDFRONT_DOMAIN = _normalize_cdn_domain(
    config('CLOUDFRONT_DOMAIN', default='') or config('AWS_S3_CUSTOM_DOMAIN', default='')
)
if CLOUDFRONT_DOMAIN:
    _cf_origin = f'https://{CLOUDFRONT_DOMAIN}'
    if _cf_origin not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(_cf_origin)

# S3 File Upload Size Limit (in MB)
S3_MAX_FILE_SIZE_MB = config('S3_MAX_FILE_SIZE_MB', default=2, cast=int)

# Media Library Base Folder
S3_MEDIA_LIBRARY_BASE_FOLDER = config('S3_MEDIA_LIBRARY_BASE_FOLDER', default='medialibrary')

# Optional path to wkhtmltopdf for pdfkit. When unset/missing, PDFs fall back to WeasyPrint.
WKHTMLTOPDF_PATH = config("WKHTMLTOPDF_PATH", default="")
# Resume studio PDF engine: weasyprint (default) or wkhtmltopdf
RESUME_PDF_ENGINE = config("RESUME_PDF_ENGINE", default="weasyprint")

# Use S3 for media uploads (images, PDFs from admin). When True and AWS credentials exist,
# FileField/ImageField uploads go to S3 instead of local MEDIA_ROOT.
USE_S3_FOR_MEDIA = config('USE_S3_FOR_MEDIA', default=True, cast=bool)
_USE_S3 = USE_S3_FOR_MEDIA and bool(AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY)

# S3 media access: how your website serves S3 media (applies to all media on the bucket).
# - presigned: .url returns signed URLs (private bucket; only your app generates valid links; URLs expire in 1h).
# - public: .url returns plain S3 URLs (or CloudFront if CLOUDFRONT_DOMAIN is set).
# - cloudfront: .url returns https://{CLOUDFRONT_DOMAIN}/... (requires CLOUDFRONT_DOMAIN; use OAI/OAC or public origin).
# - proxy: .url returns /media/s3/...; Django streams from S3 (bucket fully private; only your site can show files).
S3_MEDIA_ACCESS_MODE = config('S3_MEDIA_ACCESS_MODE', default='presigned')
# For proxy mode, S3 key prefix (must match storage "location"); used by s3_media_proxy view.
S3_MEDIA_LOCATION = config('S3_MEDIA_LOCATION', default='media')

# Legacy: when S3_MEDIA_ACCESS_MODE is presigned/public, this controls querystring_auth.
AWS_QUERYSTRING_AUTH = config('AWS_QUERYSTRING_AUTH', default=True, cast=bool)

_S3_DIRECT_BASE_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_REGION}.amazonaws.com/"
_S3_BUCKET_BASE_URL_ENV = config('S3_BUCKET_BASE_URL', default='')
_use_cloudfront = bool(CLOUDFRONT_DOMAIN) and S3_MEDIA_ACCESS_MODE in ('cloudfront', 'public')
if _use_cloudfront:
    S3_BUCKET_BASE_URL = f"https://{CLOUDFRONT_DOMAIN}/"
elif _S3_BUCKET_BASE_URL_ENV:
    S3_BUCKET_BASE_URL = _S3_BUCKET_BASE_URL_ENV if _S3_BUCKET_BASE_URL_ENV.endswith('/') else f"{_S3_BUCKET_BASE_URL_ENV}/"
else:
    S3_BUCKET_BASE_URL = _S3_DIRECT_BASE_URL

if _USE_S3:
    _use_proxy = (S3_MEDIA_ACCESS_MODE == 'proxy')
    # CloudFront / public URLs must not append S3 signature query strings.
    if _use_proxy or _use_cloudfront or S3_MEDIA_ACCESS_MODE == 'public':
        _querystring_auth = False
    else:
        _querystring_auth = AWS_QUERYSTRING_AUTH
    _storage_options = {
        "bucket_name": AWS_STORAGE_BUCKET_NAME,
        "region_name": AWS_REGION,
        "location": S3_MEDIA_LOCATION,
        "default_acl": "public-read",
        "querystring_auth": _querystring_auth,
        "querystring_expire": 3600,
    }
    if _use_cloudfront:
        _storage_options["custom_domain"] = CLOUDFRONT_DOMAIN
        AWS_S3_CUSTOM_DOMAIN = CLOUDFRONT_DOMAIN
    STORAGES = {
        "default": {
            "BACKEND": "core.storage_backends.S3MediaStorage" if (_use_proxy or _use_cloudfront) else "storages.backends.s3.S3Storage",
            "OPTIONS": _storage_options,
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    if _use_proxy:
        MEDIA_URL = "/media/"
    elif _use_cloudfront:
        MEDIA_URL = f"https://{CLOUDFRONT_DOMAIN}/{S3_MEDIA_LOCATION}/"
    else:
        MEDIA_URL = f"{_S3_DIRECT_BASE_URL}{S3_MEDIA_LOCATION}/"
    AWS_S3_REGION_NAME = AWS_REGION
    AWS_LOCATION = S3_MEDIA_LOCATION
    AWS_DEFAULT_ACL = "public-read"
    AWS_QUERYSTRING_AUTH = _querystring_auth
    AWS_S3_QUERYSTRING_EXPIRE = 3600
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# Suppress CKEditor 4 deprecation warning
# Note: CKEditor 4 is deprecated but still in use. Consider migrating to django-ckeditor-5 in the future.
SILENCED_SYSTEM_CHECKS = ['ckeditor.W001']

gettext = lambda s: s
LANGUAGES = (
    ('en', gettext('English')),
)

# Environment-based Elasticsearch configuration
if ENABLE_ELASTICSEARCH:
    ELASTICSEARCH_DSL = {
        'default': {
            'hosts': f"http://{config('ELASTICSEARCH_HOST', default='localhost')}:{config('ELASTICSEARCH_PORT', default='9200')}",
            'timeout': 30,
        },
    }
    ELASTICSEARCH_DSL_AUTOSYNC = True
    ELASTICSEARCH_DSL_SIGNAL_PROCESSOR = 'django_elasticsearch_dsl.signals.RealTimeSignalProcessor'
else:
    # Disable Elasticsearch for local development
    ELASTICSEARCH_DSL_AUTOSYNC = False
    ELASTICSEARCH_DSL_SIGNAL_PROCESSOR = None
    ELASTICSEARCH_DSL = {
        'default': {
            'hosts': 'http://localhost:9200',
            'timeout': 30,
        },
    }


# Cache: in development (DEBUG=True) use DummyCache so code/template changes reflect immediately.
# In production use Redis if enabled, else in-memory.
DISABLE_CACHE_FOR_DEV = config('DISABLE_CACHE_FOR_DEV', default=True, cast=bool)
if DEBUG and DISABLE_CACHE_FOR_DEV:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }
elif ENABLE_REDIS:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': f"redis://{config('REDIS_HOST', default='127.0.0.1')}:{config('REDIS_PORT', default='6379')}/1",
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'topteen-default',
        }
    }

# Session storage uses a dedicated cache alias (never DummyCache — that would drop logins in DEBUG).
_redis_host = config('REDIS_HOST', default='127.0.0.1') or '127.0.0.1'
_redis_port = config('REDIS_PORT', default='6379') or '6379'
SESSION_REDIS_DB = config('SESSION_REDIS_DB', default=2, cast=int)
TRANSLATION_REDIS_DB = config('TRANSLATION_REDIS_DB', default=3, cast=int)
ROSTER_REDIS_DB = config('ROSTER_REDIS_DB', default=4, cast=int)
CAREERS_REDIS_DB = config('CAREERS_REDIS_DB', default=5, cast=int)
PARENTS_REDIS_DB = config('PARENTS_REDIS_DB', default=6, cast=int)
SESSION_CACHE_ALIAS = 'sessions'
SESSION_USE_SIGNED_COOKIES = config('SESSION_USE_SIGNED_COOKIES', default=False, cast=bool)

if ENABLE_REDIS:
    CACHES['sessions'] = {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f"redis://{_redis_host}:{_redis_port}/{SESSION_REDIS_DB}",
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'topteen_sess',
        'TIMEOUT': SESSION_COOKIE_AGE,
    }
    # LLM translation complexity cache — always Redis when enabled (even if default is DummyCache in DEBUG).
    CACHES['translations'] = {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f"redis://{_redis_host}:{_redis_port}/{TRANSLATION_REDIS_DB}",
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'topteen_tr',
        'TIMEOUT': 60 * 60 * 24 * 30,  # 30 days
    }
    # Institute roster test-result payloads — Redis even in DEBUG so student cards load from cache.
    CACHES['roster'] = {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f"redis://{_redis_host}:{_redis_port}/{ROSTER_REDIS_DB}",
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'topteen_roster',
        'TIMEOUT': 90,
    }
    # Careers list/cluster/detail — Redis even in DEBUG (default may be DummyCache).
    CACHES['careers'] = {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f"redis://{_redis_host}:{_redis_port}/{CAREERS_REDIS_DB}",
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'topteen_careers',
        'TIMEOUT': 900,
    }
    # Parent dashboard / catalog query results — Redis even in DEBUG (default may be DummyCache).
    CACHES['parents'] = {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f"redis://{_redis_host}:{_redis_port}/{PARENTS_REDIS_DB}",
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'topteen_parents',
        'TIMEOUT': 120,
    }
else:
    CACHES['translations'] = {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'topteen-translations',
    }
    CACHES['roster'] = {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'topteen-roster',
    }
    CACHES['careers'] = {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'topteen-careers',
    }
    CACHES['parents'] = {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'topteen-parents',
    }

SESSION_ENGINE = (config('SESSION_ENGINE', default='') or '').strip()
if not SESSION_ENGINE:
    if SESSION_USE_SIGNED_COOKIES:
        # Signed cookie backend: session data lives in the cookie (SECRET_KEY HMAC). Max ~4KB total.
        SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
    elif ENABLE_REDIS:
        # Redis cache + DB fallback; custom store drops Redis orphans missing from DB
        # (avoids SessionInterrupted when SESSION_SAVE_EVERY_REQUEST / analytics save).
        SESSION_ENGINE = 'topteens.session_backends'
    else:
        SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Celery broker: use Redis only when both Celery and Redis are enabled, else in-memory (no broker required)
# Use explicit host so Kombu does not emit "No hostname was supplied. Reverting to default 'localhost'"
if ENABLE_CELERY and ENABLE_REDIS:
    _redis_host = config('REDIS_HOST', default='127.0.0.1') or '127.0.0.1'
    _redis_port = config('REDIS_PORT', default='6379') or '6379'
    CELERY_BROKER_URL = f"redis://{_redis_host}:{_redis_port}/0"
else:
    CELERY_BROKER_URL = 'memory://localhost'

# Celery Beat: crontab hour/minute for scheduled tasks use this timezone (IST).
CELERY_TIMEZONE = config('CELERY_TIMEZONE', default='Asia/Kolkata')
CELERY_ENABLE_UTC = True

QUEUE_DEFAULT = 'default'

_TOPTEEN_FROM_EMAIL = config('TOPTEEN_FROM_EMAIL', default='support@topteen.careers')
TOPTEEN_FROM_EMAIL = _TOPTEEN_FROM_EMAIL
MOBILE_SMS_SERVICE = ''

# SMS / WhatsApp — live enable/disable and credentials are managed in admin
# (SmsSettings / WhatsAppSettings). Env values below seed empty admin fields only.
# https://www.plivo.com/ — Auth ID/Token from https://manage.plivo.com/dashboard/
SMS_ENABLED = config('SMS_ENABLED', default=False, cast=bool)  # legacy; prefer admin SmsSettings.is_enabled
WHATSAPP_ENABLED = config('WHATSAPP_ENABLED', default=False, cast=bool)  # legacy; prefer admin WhatsAppSettings.is_enabled
SMS_PROVIDER = config('SMS_PROVIDER', default='smartping').strip().lower()  # smartping | plivo
OTP_MOBILE_CHANNEL = config('OTP_MOBILE_CHANNEL', default='sms').strip().lower()  # legacy
SMS_FORCE_SEND = config('SMS_FORCE_SEND', default=False, cast=bool)  # legacy
WHATSAPP_FORCE_SEND = config('WHATSAPP_FORCE_SEND', default=False, cast=bool)  # legacy

# SmartPing SMS API Configuration
SMARTPING_SMS_API_URL = config('SMARTPING_SMS_API_URL', default='https://pgapi.smartping.ai/fe/api/v1/send')
SMARTPING_SMS_USERNAME = config('SMARTPING_SMS_USERNAME', default='Testprepgpt.trans')
SMARTPING_SMS_PASSWORD = config('SMARTPING_SMS_PASSWORD', default='sW2gV')
SMARTPING_SMS_FROM = config('SMARTPING_SMS_FROM', default='TSTGPT')
SMARTPING_SMS_DLT_CONTENT_ID = config('SMARTPING_SMS_DLT_CONTENT_ID', default='1707175152949044040')
SMARTPING_SMS_DLT_PRINCIPAL_ENTITY_ID = config('SMARTPING_SMS_DLT_PRINCIPAL_ENTITY_ID', default='1701172845816093698')
SMARTPING_SMS_UNICODE = config('SMARTPING_SMS_UNICODE', default='false')
SMARTPING_SMS_MESSAGE_TEMPLATE = config('SMARTPING_SMS_MESSAGE_TEMPLATE', default='{otp} is your verification code for TestprepGPT AI')
# Legacy alias — prefer SMS_FORCE_SEND
SMARTPING_SMS_FORCE_SEND = config('SMARTPING_SMS_FORCE_SEND', default=False, cast=bool)

# Plivo SMS + WhatsApp
PLIVO_AUTH_ID = config('PLIVO_AUTH_ID', default='')
PLIVO_AUTH_TOKEN = config('PLIVO_AUTH_TOKEN', default='')
PLIVO_SMS_FROM = config('PLIVO_SMS_FROM', default='')  # E.164 number or alphanumeric sender ID
PLIVO_WHATSAPP_FROM = config('PLIVO_WHATSAPP_FROM', default='')  # WABA-linked number in E.164
PLIVO_SMS_MESSAGE_TEMPLATE = config(
    'PLIVO_SMS_MESSAGE_TEMPLATE',
    default='{otp} is your verification code for TopTeen',
)
PLIVO_WHATSAPP_OTP_TEMPLATE = config('PLIVO_WHATSAPP_OTP_TEMPLATE', default='')  # approved template name
PLIVO_WHATSAPP_OTP_TEMPLATE_LANG = config('PLIVO_WHATSAPP_OTP_TEMPLATE_LANG', default='en_US')
# Legacy alias — prefer SMS_FORCE_SEND / WHATSAPP_FORCE_SEND
PLIVO_FORCE_SEND = config('PLIVO_FORCE_SEND', default=False, cast=bool)

# Email / AWS SES – all from .env; no credentials in code
EMAIL_HOST = config('EMAIL_HOST', default='email-smtp.ap-south-1.amazonaws.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
_DEFAULT_FROM_RAW = config('DEFAULT_FROM_EMAIL', default='')
DEFAULT_FROM_EMAIL = _DEFAULT_FROM_RAW if _DEFAULT_FROM_RAW else f'Topteen <{_TOPTEEN_FROM_EMAIL}>'

_env_backend = (config('EMAIL_BACKEND', default='') or '').strip()
if _env_backend:
    EMAIL_BACKEND = _env_backend
    # If .env sets stock Django backends, swap to our subclasses so logs/email_send.jsonl is written.
    if EMAIL_BACKEND == 'django.core.mail.backends.smtp.EmailBackend':
        EMAIL_BACKEND = 'topteens.mail_backends.LoggingSMTPEmailBackend'
    elif EMAIL_BACKEND == 'django.core.mail.backends.console.EmailBackend':
        EMAIL_BACKEND = 'topteens.mail_backends.LoggingConsoleEmailBackend'
elif EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'topteens.mail_backends.LoggingSMTPEmailBackend'
else:
    EMAIL_BACKEND = 'topteens.mail_backends.LoggingConsoleEmailBackend'

EMAIL_FILE_PATH = BASE_DIR / "mail/password_reset_email.html"


SOCIAL_AUTH_FACEBOOK_KEY = '1491504031336499'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = '6d5863f628f8a317ab1d8f31bce3aeb9' # App Secret

SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
   'fields': 'id, name, email, age_range'
}
SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL = True

# SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'
# SOCIAL_AUTH_REDIRECT_IS_HTTPS=True
SOCIAL_AUTH_FACEBOOK_EXTRA_DATA=[
    ('name','name'),
    ('email','email'),
    ('picture','image'),
]

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '97101059941-nhbbui825qegkhl9ivgiudoqm2d5q1rn.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE =[
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
]

# Central logs directory for app, gunicorn and debugging (bind-mount in Docker to host)
LOG_DIR = config('LOG_PATH', default=str(BASE_DIR / 'logs'))
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} [{name}] {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': 'INFO',
        },
        'file_app': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'django_app.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'file_error': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'django_error.log'),
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console', 'file_app'],
            'level': 'DEBUG' if DEBUG else 'WARNING',
        },
        'django.request': {
            'handlers': ['console', 'file_error'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'file_error'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Set to DEBUG temporarily to see "Enquiry ref=... -> source id=..." in logs (ref-landing tracking)
        'user_analytics': {
            'handlers': ['console', 'file_app'],
            'level': config('LOG_LEVEL_USER_ANALYTICS', default='WARNING'),
            'propagate': False,
        },
        # Celery logs a DEBUG line per registered task (stub "def task(...): return 1") from head_from_fun().
        # Root DEBUG would spam the console; keep this at INFO or higher.
        'celery.utils.functional': {
            'handlers': ['console', 'file_app'],
            'level': 'INFO',
            'propagate': False,
        },
        # Noisy third-party loggers — keep off the server console
        'matplotlib': {
            'handlers': ['file_app'],
            'level': 'WARNING',
            'propagate': False,
        },
        'PIL': {
            'handlers': ['file_app'],
            'level': 'WARNING',
            'propagate': False,
        },
        'urllib3': {
            'handlers': ['file_app'],
            'level': 'WARNING',
            'propagate': False,
        },
        'botocore': {
            'handlers': ['file_app'],
            'level': 'WARNING',
            'propagate': False,
        },
        'boto3': {
            'handlers': ['file_app'],
            'level': 'WARNING',
            'propagate': False,
        },
        'topteens.services_status': {
            'handlers': ['file_app'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}


# SOCIAL_AUTH_LOGIN_REDIRECT_URL = "userfeeds"

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.social_auth.associate_by_email',
    'social_core.pipeline.user.create_user',
    'users.welcome_popup.set_social_registration_welcome_popup',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

SOCIAL_AUTH_LOGIN_ERROR_URL = '/user/login'
SOCIAL_AUTH_RAISE_EXCEPTIONS = False
LOGIN_URL = '/user/login'
LOGOUT_URL = '/'
# LOGIN_REDIRECT_URL =  "/user/user-feeds"
LOGIN_REDIRECT_URL =  "/user/dashboard/"
LOGOUT_REDIRECT_URL = "/user/login"
SOCIAL_AUTH_REDIRECT_IS_HTTPS = USE_HTTPS


# Payment Gateway Configuration from Environment
# Gateway Preference: 1=ICICI_EAZYPAY (first preference), 2=RAZORPAY (fallback)
PAYMENT_GATEWAY_PREFERENCE = config('PAYMENT_GATEWAY_PREFERENCE', default=1, cast=int)

# Payment Gateway Environment Mode (sandbox or production)
RAZORPAY_ENVIRONMENT = config('RAZORPAY_ENVIRONMENT', default='sandbox')
ICICI_EAZYPAY_ENVIRONMENT = config('ICICI_EAZYPAY_ENVIRONMENT', default='sandbox')

# Razorpay Configuration - Select keys based on environment
if RAZORPAY_ENVIRONMENT == 'production':
    RAZORPAY_KEY = config('RAZORPAY_PRODUCTION_KEY', default=config('RAZORPAY_KEY', default=''))
    RAZORPAY_SECRET = config('RAZORPAY_PRODUCTION_SECRET', default=config('RAZORPAY_SECRET', default=''))
else:  # sandbox/test mode
    RAZORPAY_KEY = config('RAZORPAY_SANDBOX_KEY', default=config('RAZORPAY_KEY', default=''))
    RAZORPAY_SECRET = config('RAZORPAY_SANDBOX_SECRET', default=config('RAZORPAY_SECRET', default=''))

# For backward compatibility, use RAZORPAY_KEY/SECRET if API_KEY/SECRET not provided
_razorpay_api_key = config('RAZORPAY_API_KEY', default='')
_razorpay_api_secret = config('RAZORPAY_API_SECRET', default='')
RAZORPAY_API_KEY = _razorpay_api_key if _razorpay_api_key else RAZORPAY_KEY
RAZORPAY_API_SECRET = _razorpay_api_secret if _razorpay_api_secret else RAZORPAY_SECRET

# Razorpay Dashboard → Webhooks → signing secret (not the API secret). Used by /payments/razorpay/webhook/
RAZORPAY_WEBHOOK_SECRET = config('RAZORPAY_WEBHOOK_SECRET', default='')

# Default password for new users (can be overridden via .env)
DEFAULT_PASSWORD = config('DEFAULT_PASSWORD', default='12345')

# ICICI Eazypay Configuration - Select URLs and keys based on environment
if ICICI_EAZYPAY_ENVIRONMENT == 'production':
    ICICI_EAZYPAY_DEFAULT_BASE_URL = config('ICICI_EAZYPAY_PRODUCTION_BASE_URL', default=config('ICICI_EAZYPAY_DEFAULT_BASE_URL', default='https://eazypay.icicibank.com/EazyPG?'))
    ICICI_EAZYPAY_PAYMENT_MODE = config('ICICI_EAZYPAY_PRODUCTION_PAYMENT_MODE', default=config('ICICI_EAZYPAY_PAYMENT_MODE', default=9, cast=int), cast=int)
    ICICI_EAZYPAY_MERCHANT_ID = config('ICICI_EAZYPAY_PRODUCTION_MERCHANT_ID', default=config('ICICI_EAZYPAY_MERCHANT_ID', default=''))
    ICICI_EAZYPAY_ENCRYPTION_KEY = config('ICICI_EAZYPAY_PRODUCTION_ENCRYPTION_KEY', default=config('ICICI_EAZYPAY_ENCRYPTION_KEY', default=''))
else:  # sandbox/test mode
    ICICI_EAZYPAY_DEFAULT_BASE_URL = config('ICICI_EAZYPAY_SANDBOX_BASE_URL', default=config('ICICI_EAZYPAY_DEFAULT_BASE_URL', default='https://eazypay.icicibank.com/EazyPG?'))
    ICICI_EAZYPAY_PAYMENT_MODE = config('ICICI_EAZYPAY_SANDBOX_PAYMENT_MODE', default=config('ICICI_EAZYPAY_PAYMENT_MODE', default=9, cast=int), cast=int)
    ICICI_EAZYPAY_MERCHANT_ID = config('ICICI_EAZYPAY_SANDBOX_MERCHANT_ID', default=config('ICICI_EAZYPAY_MERCHANT_ID', default=''))
    ICICI_EAZYPAY_ENCRYPTION_KEY = config('ICICI_EAZYPAY_SANDBOX_ENCRYPTION_KEY', default=config('ICICI_EAZYPAY_ENCRYPTION_KEY', default=''))

ICICI_EAZYPAY_BASE_RETURN_URL = config('ICICI_EAZYPAY_BASE_RETURN_URL', default='https://www.topteen.in/payments/payment-success-v2/')
# Optional: require this value in header X-Eazypay-Webhook-Secret or ?secret= on /payments/eazypay/webhook/
ICICI_EAZYPAY_WEBHOOK_SECRET = config('ICICI_EAZYPAY_WEBHOOK_SECRET', default='')
ICICI_EAZYPAY_PAYMENT_SUCESS_RESPONSE_CODE = config('ICICI_EAZYPAY_PAYMENT_SUCESS_RESPONSE_CODE', default='E000')

# Psychometric Test Amounts
STREAM_SORTER_TEST_AMOUNT = config('STREAM_SORTER_TEST_AMOUNT', default=999, cast=int)
CAREER_DIRECTION_TEST_AMOUNT = config('CAREER_DIRECTION_TEST_AMOUNT', default=999, cast=int)
ENABLE_PSYCHOMETRIC_PACKAGES = config('ENABLE_PSYCHOMETRIC_PACKAGES', default=False, cast=bool)

LOGO_URL="https://topteen.in/static/images/logos/topteen-logo-with-text.png"
TOPTEEN_EMAIL_LOGO_URL = config(
    'TOPTEEN_EMAIL_LOGO_URL',
    default='https://www.topteen.in/static/images_new/logos/logo.svg',
)
TOPTEEN_SUPPORT_EMAIL = config('TOPTEEN_SUPPORT_EMAIL', default='support@topteen.careers')
SITE_NAME="Topteen Careers"
LOGIN_ERROR_URL='/user/login'
CENTRAL_TEST_API_USERNAME="counselcareer1@gmail.com"
CENTRAL_TEST_API_PASSWORD="assessment"
CAREER_INTEREST_ASSESSMENTT_TEST_ID=531
CAREER_INTEREST_ASSESSMENTT_TEST_LANGUAGE_ID=1

SERVER_EMAIL = config('SERVER_EMAIL', default=_TOPTEEN_FROM_EMAIL)
ADMINS=[('Shanti', 'it@canamgroup.com'),
        ('Dev', 'admin@canamgroup.com')]
EXCEPTION_EMAIL_TO = [
    'it@canamgroup.com',
    'admin@canamgroup.com',
]
EMAIL_SUBJECT_PREFIX = '[TopTeen-Exceptions] '

PSYCHOMETRIC_COURSE_FREE_ID=3

DEMO_EMAIL=[]
CREDIT_LIMIT=5000

# User id of the marketing admin who owns self-serve ("direct") institute signups when no partner is chosen.
# Set to 0 in .env to leave marketing_group unset for direct registrations.
DEFAULT_DIRECT_INSTITUTE_MARKETING_ADMIN_USER_ID = config(
    'DEFAULT_DIRECT_INSTITUTE_MARKETING_ADMIN_USER_ID',
    default=1409,
    cast=int,
)

# Production indexing. Override with ALLOW_SEARCH_ENGINE_INDEX=true in .env when needed.
# ALLOW_SEARCH_ENGINE_INDEX = config(
#     'ALLOW_SEARCH_ENGINE_INDEX',
#     default=(ENVIRONMENT == 'production'),
#     cast=bool,
# )
# demo.topteen.in / localhost: allow index for Lighthouse QA (robots.txt + meta robots).
ALLOW_DEMO_SEARCH_INDEX = config('ALLOW_DEMO_SEARCH_INDEX', default=False, cast=bool)
WEBADMINEMAIL = config('WEBADMINEMAIL', default='')
# Daily new user report schedule: core.Configuration key DAILY_USER_REPORT_TIME (HH:MM, 24h, IST).
# Celery Beat uses CELERY_TIMEZONE (default Asia/Kolkata). Edit in Service monitor or Admin → Configuration.

# Enquiry source UTM links: base URL is always www.topteen.in or demo.topteen.in (set in .env per environment).
ENQUIRY_SOURCE_BASE_URL = config('ENQUIRY_SOURCE_BASE_URL', default='https://www.topteen.in').rstrip('/')

# Demo accounts: use DB only (User.is_demo_account, Institute.is_demo_institute). No .env demo credentials.

# Chatbot visibility: home-only | students-parents | institutes | counselors
CHATBOT_VISIBILITY = config('CHATBOT_VISIBILITY', default='home-only')

# @manish
# Master password settings
MASTER_PASSWORD = config('MASTER_PASSWORD', default='')


# try:
#     from topteens.local_settings import *
# except ImportError:
#     pass

# https://www.topteen.in/psychometrictest/update-psychometric-test-payment-eazypay
# https://www.topteen.in/skilllabcourse/update-skilllab-course-payment
