"""
Django settings for topteens project.

Generated by 'django-admin startproject' using Django 2.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/ 
"""

import os
import logging.handlers
from pathlib import Path
from decouple import config
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='(&yw*5eqsx-tkz^&kvlxx8donayimg&kee=*1nmkxlmor0$q^9')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,testserver,www.topteen.in,test.topteen.in').split(',')

# Student localStorage payload encryption (for chatbot decryption use same key)
# Generate a key: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
STUDENT_DATA_ENCRYPTION_KEY = config('STUDENT_DATA_ENCRYPTION_KEY', default='')


# Application definition

INSTALLED_APPS = [
    'storages',
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'ckeditor_uploader',
    'nested_inline',
    'django_filters',
    'django_extensions',
    'rest_framework',
    # 'django_unused_media',
    'core',
    'skilllab',
    'users',
    'careers',
    'topteenadmin',
    'colleges',
    'kaunsa_mirror',
    'courses',
    'entrance_exams',
    'blog',
    'communication',
    'social_django',
    'psychometric_tests',
    'payments',
    'crm',
    'institute',
    'app',
    'counselor',
    'nested_admin',
    'analytics_dashboard',
    'app_post_matric',
    'user_analytics',
    'forum',
    'demo_data',
    'invoices',
    'seo_dashboard',
]

# Optional services: set False in .env when not running (avoids errors, uses fallbacks)
ENABLE_REDIS = config('ENABLE_REDIS', default=True, cast=bool)
ENABLE_CELERY = config('ENABLE_CELERY', default=True, cast=bool)

# User analytics: set False in .env to disable all tracking (debugging / manual data clean)
ENABLE_USER_ANALYTICS_TRACKING = config('ENABLE_USER_ANALYTICS_TRACKING', default=True, cast=bool)

# Add django_elasticsearch_dsl conditionally based on environment
ENABLE_ELASTICSEARCH = config('ENABLE_ELASTICSEARCH', default=True, cast=bool)
if ENABLE_ELASTICSEARCH:
    INSTALLED_APPS.append('django_elasticsearch_dsl')

# AI Features Configuration (Optional - defaults to False)
ENABLE_AI_FEATURES = config('ENABLE_AI_FEATURES', default=False, cast=bool)
ENABLE_AI_SUMMARIES = config('ENABLE_AI_SUMMARIES', default=False, cast=bool)
ENABLE_SEMANTIC_SEARCH = config('ENABLE_SEMANTIC_SEARCH', default=False, cast=bool)

# AI Provider Configuration (only used if ENABLE_AI_FEATURES=True or ENABLE_SEMANTIC_SEARCH=True)
AI_PROVIDER = config('AI_PROVIDER', default='none')  # openai, gemini, anthropic, local, none
OPENAI_API_KEY = config('OPENAI_API_KEY', default='')
GOOGLE_API_KEY = config('GOOGLE_API_KEY', default='')
ANTHROPIC_API_KEY = config('ANTHROPIC_API_KEY', default='')
AI_MODEL = config('AI_MODEL', default='gpt-3.5-turbo')  # or gemini-1.5-flash, claude-3-haiku, etc.
GEMINI_MODEL = config('GEMINI_MODEL', default='gemini-1.5-flash')

# Forum AI Configuration
OPENAI_MODEL = config('OPENAI_MODEL', default='gpt-4o-mini')  # Default to cost-effective model for forum
USE_DATABASE_CACHE = config('USE_DATABASE_CACHE', default='True', cast=bool)  # Enable database caching for forum
SEMANTIC_SIMILARITY_THRESHOLD = config('SEMANTIC_SIMILARITY_THRESHOLD', default=0.85, cast=float)  # 0.0 to 1.0

# Freetrail: seconds a guest can view ebook/vocational/extracurricular detail before login popup (0 = no freetrail)
FREETRAIL_TIME_SECONDS = config('FREETRAIL_TIME_SECONDS', default=5, cast=int)

# Embedding Cache Configuration
ENABLE_EMBEDDING_CACHE = config('ENABLE_EMBEDDING_CACHE', default=True, cast=bool)
EMBEDDING_CACHE_TTL = config('EMBEDDING_CACHE_TTL', default=86400, cast=int)  # 24 hours
QUERY_EMBEDDING_CACHE_TTL = config('QUERY_EMBEDDING_CACHE_TTL', default=3600, cast=int)  # 1 hour

# Psychometric Test Widget Configuration
# ENABLE_ANSWERING_CAREFULLY_WIDGET: Show "Answering Carefully" / "Rushing Through" widget on test pages (default: True)
ENABLE_ANSWERING_CAREFULLY_WIDGET = config('ENABLE_ANSWERING_CAREFULLY_WIDGET', default=True, cast=bool)
# ENABLE_AUTO_FORWARD: Auto-advance to next question when user selects an answer (default: True)
ENABLE_AUTO_FORWARD = config('ENABLE_AUTO_FORWARD', default=True, cast=bool)

# Allow same-origin iframes (e.g. Career Battle wrapper embedding /career-battle/app/).
# Still blocks embedding from other sites (clickjacking protection).
X_FRAME_OPTIONS = 'SAMEORIGIN'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'core.slash_middleware.AppendSlashRedirectMiddleware',  # Redirect /path to /path/ when /path/ resolves (before catch-all 404)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'topteens.admin_template_middleware.AdminTemplateMiddleware',  # Force Django templates for admin
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'topteens.custome_middleware.CustomeSocialAuthExceptionMiddleware',
    'topteens.custome_middleware.TopteenAdminRequireLoginCheck',
    'topteens.custome_middleware.TopteenAdminPermissionMiddleware',
    'user_analytics.middleware.AnalyticsMiddleware',
    'core.seo_middleware.PageSEOMiddleware',  # Merge PageSEO into html_head by request path (all pages)
]


CORS_ALLOWED_ORIGINS = [
    'https://www.topteen.in',
    'http://demo.topteen.in',
    'https://topteenc.s3.ap-northeast-1.amazonaws.com',
]

CSRF_TRUSTED_ORIGINS = [
    'https://www.topteen.in',
    'http://demo.topteen.in',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://10.0.0.93:8000',  # Replace with your actual domain
    
    # Add your domain here
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True # If needed for cookies or auth

# HTTP vs HTTPS - controlled by USE_HTTPS env (True=HTTPS, False=HTTP)
USE_HTTPS = config('USE_HTTPS', default=False, cast=bool)
SECURE_SSL_REDIRECT = USE_HTTPS
SESSION_COOKIE_SECURE = USE_HTTPS
CSRF_COOKIE_SECURE = USE_HTTPS
# When behind reverse proxy (nginx, etc.) that terminates SSL
if USE_HTTPS:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ROOT_URLCONF = 'topteens.urls'
# Trailing slash: our AppendSlashRedirectMiddleware redirects /path -> /path/ when /path/ resolves.
# APPEND_SLASH still used by CommonMiddleware for any URL that does not match (e.g. before catch-all).
APPEND_SLASH = True
DEFAULT_AUTO_FIELD='django.db.models.AutoField'
TEMPLATES = [
     {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': ['templates', os.path.join(BASE_DIR, 'frontend')],  # Added frontend directory for Jinja2 templates
        'APP_DIRS': False,  # Disable APP_DIRS - custom loader handles app directories and skips admin templates
        'OPTIONS': {
            'environment': 'topteens.jinja_env.environment',
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'core.context_processors.set_upg_variables',
                'topteens.context_processor.globals',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),  # Add templates directory for Django admin templates
            os.path.join(BASE_DIR, 'templates1'),
            os.path.join(BASE_DIR, 'frontend'),  # old code not in use - start - New isolated frontend templates
        ],  # old code not in use - end
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.has_payment',
                # Inject master class list for grade/class dropdowns (Django templates)
                'core.context_processors.master_classes_processor',
                # Only ENVIRONMENT=production allows search engine indexing (noindex otherwise)
                'core.context_processors.allow_search_engine_index_processor',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'users.backends.CustomUserBackend',
    'django.contrib.auth.backends.ModelBackend',
    'users.auth.MasterPasswordBackend',  # Custom backend with master password support
)

WSGI_APPLICATION = 'topteens.wsgi.application'

AUTH_USER_MODEL = "users.User"


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'topteens',
#         'USER':'root',
#         'PASSWORD':'root',
#         'HOST':'mariadb',
#         'PORT':'3306',
#         'OPTIONS': {'charset': 'utf8mb4'},
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
        'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=60, cast=int),
        'OPTIONS': {
            'charset': 'utf8mb4',
            # Use UTC for every connection so datetime values are valid (fixes admin date_hierarchy
            # "invalid datetime / time zone definitions" on MySQL when tz tables are not loaded).
            'init_command': "SET time_zone = '+00:00'",
        },
    }
}

# Kaunsa College API mirror (PostgreSQL) — optional; enable for India/international sync cache.
# Local Docker: docker compose -f docker/docker-compose.kaunsa-postgres.yml up -d
# Env template: docker/kaunsa-postgres.env.example
KAUNSA_PG_ENABLED = config('KAUNSA_PG_ENABLED', default=False, cast=bool)
DATABASE_ROUTERS = []
if KAUNSA_PG_ENABLED:
    DATABASES['kaunsa_mirror'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('KAUNSA_PG_NAME', default='kaunsa_mirror'),
        'USER': config('KAUNSA_PG_USER', default='kaunsa'),
        'PASSWORD': config('KAUNSA_PG_PASSWORD', default=''),
        'HOST': config('KAUNSA_PG_HOST', default='127.0.0.1'),
        'PORT': config('KAUNSA_PG_PORT', default='5432'),
        'CONN_MAX_AGE': config('KAUNSA_PG_CONN_MAX_AGE', default=60, cast=int),
        'OPTIONS': {},
    }
    _kaunsa_ssl = config('KAUNSA_PG_SSLMODE', default='').strip()
    if _kaunsa_ssl:
        DATABASES['kaunsa_mirror']['OPTIONS']['sslmode'] = _kaunsa_ssl
    DATABASE_ROUTERS = ['kaunsa_mirror.routers.KaunsaMirrorRouter']

KAUNSA_INDIA_API_BASE_URL = config('KAUNSA_INDIA_API_BASE_URL', default='').rstrip('/')
KAUNSA_INTL_API_BASE_URL = config('KAUNSA_INTL_API_BASE_URL', default='').rstrip('/')
KAUNSA_INDIA_COUNTRY_ID = config('KAUNSA_INDIA_COUNTRY_ID', default='').strip()
KAUNSA_INTL_COUNTRY_ID = config('KAUNSA_INTL_COUNTRY_ID', default='').strip()
KAUNSA_REQUEST_TIMEOUT = config('KAUNSA_REQUEST_TIMEOUT', default=30, cast=int)

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'topteen12',
#         'USER':'root12',
#         'PASSWORD':'root12',
#         'HOST':'13.232.70.31',
#         'PORT':'3306',
#         'OPTIONS': {'charset': 'utf8mb4'},
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = config('TIME_ZONE', default='Asia/Kolkata')

USE_I18N = True

USE_L10N = True

USE_TZ = True  # Keep this enabled to handle time zones correctly



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
# Common base path for STATIC_ROOT and MEDIA_ROOT so they are not duplicated per run/env.
# Set COMMON_BASE_PATH in .env to a shared path, or leave unset to use project root (BASE_DIR).
COMMON_BASE_PATH = config('COMMON_BASE_PATH', default=str(BASE_DIR))
if not os.path.isabs(COMMON_BASE_PATH):
    COMMON_BASE_PATH = os.path.normpath(os.path.join(BASE_DIR, COMMON_BASE_PATH))

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(COMMON_BASE_PATH, 'staticfiles')

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(COMMON_BASE_PATH, 'media')


# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 60,
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Add development specific middleware
# if DEBUG:
#     INSTALLED_APPS += [
#         'debug_toolbar',
#     ]
    
#     MIDDLEWARE = [
#         'debug_toolbar.middleware.DebugToolbarMiddleware',
#     ] + MIDDLEWARE  # Note: Debug toolbar middleware should be as early as possible

#     INTERNAL_IPS = [
#         '127.0.0.1',
#         '10.0.0.93',
#         'localhost',
#     ]

#     DEBUG_TOOLBAR_CONFIG = {
#         'SHOW_TOOLBAR_CALLBACK': lambda request: True,  # Always show toolbar in debug mode
#     }


CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"
CKEDITOR_ALLOW_NONIMAGE_FILES = False
CKEDITOR_UPLOAD_PATH = "cke/uploads/"
CKEDITOR_FILENAME_GENERATOR = 'core.utils.reformat_filename'
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': None,
    },
}

# File Upload Settings
# Upload size limits for ebooks
DATA_UPLOAD_MAX_MEMORY_SIZE = 3 * 1024 * 1024  # 3 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 3 * 1024 * 1024  # 3 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240  # Increase if needed

# S3 Bucket Configuration
S3_BUCKET_PREFIX = config('S3_BUCKET_PREFIX', default='s3://topteenc/')
S3_BUCKET_BASE_URL = config('S3_BUCKET_BASE_URL', default='https://topteenc.s3.ap-northeast-1.amazonaws.com/')
S3_EBOOK_FOLDER = 'ebook'  # Folder path for ebooks in S3
S3_FOUR_PILLARS_FOLDER = config('S3_FOUR_PILLARS_FOLDER', default='four_pillars')  # Folder for Four Pillars of Learning images in S3
# Multiple Intelligences (MI) page: full base URL for MI images in S3 (e.g. https://bucket.s3.region.amazonaws.com/mi/). If unset, uses static/images_new/mi/
S3_MI_IMAGES_BASE_URL = config('S3_MI_IMAGES_BASE_URL', default='')
S3_EQ_IMAGES_BASE_URL = config('S3_EQ_IMAGES_BASE_URL', default='')

# Path to assessment reference docx (MI reports, scoring method, EQ report). Default: sibling topteens html/b.
# 7nov/topteenhtml/html/b (go up from topteen_1.0: parent=new_template-demo-topteens, parent=git, parent=7nov)
_assessment_ref = BASE_DIR.parent.parent.parent / 'topteenhtml' / 'html' / 'b'
_ASSESSMENT_REF_DEFAULT = str(_assessment_ref) if _assessment_ref.exists() else ''
ASSESSMENT_REFERENCE_BASE = config('ASSESSMENT_REFERENCE_BASE', default=_ASSESSMENT_REF_DEFAULT)

# AWS S3 Upload Configuration
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')
AWS_REGION = config('AWS_REGION', default='ap-northeast-1')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME', default='topteenc')

# S3 File Upload Size Limit (in MB)
S3_MAX_FILE_SIZE_MB = config('S3_MAX_FILE_SIZE_MB', default=2, cast=int)

# Media Library Base Folder
S3_MEDIA_LIBRARY_BASE_FOLDER = config('S3_MEDIA_LIBRARY_BASE_FOLDER', default='medialibrary')

# Use S3 for media uploads (images, PDFs from admin). When True and AWS credentials exist,
# FileField/ImageField uploads go to S3 instead of local MEDIA_ROOT.
USE_S3_FOR_MEDIA = config('USE_S3_FOR_MEDIA', default=True, cast=bool)
_USE_S3 = USE_S3_FOR_MEDIA and bool(AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY)

# S3 media access: how your website serves S3 media (applies to all media on the bucket).
# - presigned: .url returns signed URLs (private bucket; only your app generates valid links; URLs expire in 1h).
# - public: .url returns plain S3 URLs (bucket/objects must allow public GetObject).
# - proxy: .url returns /media/s3/...; Django streams from S3 (bucket fully private; only your site can show files).
S3_MEDIA_ACCESS_MODE = config('S3_MEDIA_ACCESS_MODE', default='presigned')
# For proxy mode, S3 key prefix (must match storage "location"); used by s3_media_proxy view.
S3_MEDIA_LOCATION = config('S3_MEDIA_LOCATION', default='media')

# Legacy: when S3_MEDIA_ACCESS_MODE is presigned/public, this controls querystring_auth.
AWS_QUERYSTRING_AUTH = config('AWS_QUERYSTRING_AUTH', default=True, cast=bool)

if _USE_S3:
    _use_proxy = (S3_MEDIA_ACCESS_MODE == 'proxy')
    _querystring_auth = False if _use_proxy else AWS_QUERYSTRING_AUTH
    STORAGES = {
        "default": {
            "BACKEND": "core.storage_backends.S3MediaStorage" if _use_proxy else "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "region_name": AWS_REGION,
                "location": S3_MEDIA_LOCATION,
                "default_acl": "public-read",
                "querystring_auth": _querystring_auth,
                "querystring_expire": 3600,
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    if _use_proxy:
        MEDIA_URL = "/media/"
    else:
        MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_REGION}.amazonaws.com/{S3_MEDIA_LOCATION}/"
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# Suppress CKEditor 4 deprecation warning
# Note: CKEditor 4 is deprecated but still in use. Consider migrating to django-ckeditor-5 in the future.
SILENCED_SYSTEM_CHECKS = ['ckeditor.W001']

gettext = lambda s: s
LANGUAGES = (
    ('en', gettext('English')),
)

# Environment-based Elasticsearch configuration
if ENABLE_ELASTICSEARCH:
    ELASTICSEARCH_DSL = {
        'default': {
            'hosts': f"http://{config('ELASTICSEARCH_HOST', default='localhost')}:{config('ELASTICSEARCH_PORT', default='9200')}",
            'timeout': 30,
        },
    }
    ELASTICSEARCH_DSL_AUTOSYNC = True
    ELASTICSEARCH_DSL_SIGNAL_PROCESSOR = 'django_elasticsearch_dsl.signals.RealTimeSignalProcessor'
else:
    # Disable Elasticsearch for local development
    ELASTICSEARCH_DSL_AUTOSYNC = False
    ELASTICSEARCH_DSL_SIGNAL_PROCESSOR = None
    ELASTICSEARCH_DSL = {
        'default': {
            'hosts': 'http://localhost:9200',
            'timeout': 30,
        },
    }


# Cache: in development (DEBUG=True) use DummyCache so code/template changes reflect immediately.
# In production use Redis if enabled, else in-memory.
DISABLE_CACHE_FOR_DEV = config('DISABLE_CACHE_FOR_DEV', default=True, cast=bool)
if DEBUG and DISABLE_CACHE_FOR_DEV:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }
elif ENABLE_REDIS:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': f"redis://{config('REDIS_HOST', default='127.0.0.1')}:{config('REDIS_PORT', default='6379')}/1",
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'topteen-default',
        }
    }

# Celery broker: use Redis only when both Celery and Redis are enabled, else in-memory (no broker required)
# Use explicit host so Kombu does not emit "No hostname was supplied. Reverting to default 'localhost'"
if ENABLE_CELERY and ENABLE_REDIS:
    _redis_host = config('REDIS_HOST', default='127.0.0.1') or '127.0.0.1'
    _redis_port = config('REDIS_PORT', default='6379') or '6379'
    CELERY_BROKER_URL = f"redis://{_redis_host}:{_redis_port}/0"
else:
    CELERY_BROKER_URL = 'memory://localhost'

QUEUE_DEFAULT = 'default'

_TOPTEEN_FROM_EMAIL = config('TOPTEEN_FROM_EMAIL', default='support@topteen.careers')
TOPTEEN_FROM_EMAIL = _TOPTEEN_FROM_EMAIL
MOBILE_SMS_SERVICE = ''

# SmartPing SMS API Configuration
SMARTPING_SMS_API_URL = config('SMARTPING_SMS_API_URL', default='https://pgapi.smartping.ai/fe/api/v1/send')
SMARTPING_SMS_USERNAME = config('SMARTPING_SMS_USERNAME', default='Testprepgpt.trans')
SMARTPING_SMS_PASSWORD = config('SMARTPING_SMS_PASSWORD', default='sW2gV')
SMARTPING_SMS_FROM = config('SMARTPING_SMS_FROM', default='TSTGPT')
SMARTPING_SMS_DLT_CONTENT_ID = config('SMARTPING_SMS_DLT_CONTENT_ID', default='1707175152949044040')
SMARTPING_SMS_DLT_PRINCIPAL_ENTITY_ID = config('SMARTPING_SMS_DLT_PRINCIPAL_ENTITY_ID', default='1701172845816093698')
SMARTPING_SMS_UNICODE = config('SMARTPING_SMS_UNICODE', default='false')
SMARTPING_SMS_MESSAGE_TEMPLATE = config('SMARTPING_SMS_MESSAGE_TEMPLATE', default='{otp} is your verification code for TestprepGPT AI')

# Email / AWS SES – all from .env; no credentials in code
EMAIL_HOST = config('EMAIL_HOST', default='email-smtp.ap-south-1.amazonaws.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
_DEFAULT_FROM_RAW = config('DEFAULT_FROM_EMAIL', default='')
DEFAULT_FROM_EMAIL = _DEFAULT_FROM_RAW if _DEFAULT_FROM_RAW else f'Topteen <{_TOPTEEN_FROM_EMAIL}>'

_env_backend = config('EMAIL_BACKEND', default='')
if _env_backend:
    EMAIL_BACKEND = _env_backend
elif EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_FILE_PATH = BASE_DIR / "mail/password_reset_email.html"


SOCIAL_AUTH_FACEBOOK_KEY = '1491504031336499'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = '6d5863f628f8a317ab1d8f31bce3aeb9' # App Secret

SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
   'fields': 'id, name, email, age_range'
}
SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL = True

# SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'
# SOCIAL_AUTH_REDIRECT_IS_HTTPS=True
SOCIAL_AUTH_FACEBOOK_EXTRA_DATA=[
    ('name','name'),
    ('email','email'),
    ('picture','image'),
]

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '97101059941-nhbbui825qegkhl9ivgiudoqm2d5q1rn.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE =[
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
]

# Central logs directory for app, gunicorn and debugging (bind-mount in Docker to host)
LOG_DIR = config('LOG_PATH', default=str(BASE_DIR / 'logs'))
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} [{name}] {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_app': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'django_app.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'file_error': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'django_error.log'),
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console', 'file_app'],
            'level': 'DEBUG' if DEBUG else 'WARNING',
        },
        'django.request': {
            'handlers': ['console', 'file_error'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'file_error'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Set to DEBUG temporarily to see "Enquiry ref=... -> source id=..." in logs (ref-landing tracking)
        'user_analytics': {
            'handlers': ['console', 'file_app'],
            'level': config('LOG_LEVEL_USER_ANALYTICS', default='WARNING'),
            'propagate': False,
        },
    },
}


# SOCIAL_AUTH_LOGIN_REDIRECT_URL = "userfeeds"

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.social_auth.associate_by_email',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

SOCIAL_AUTH_LOGIN_ERROR_URL = '/user/login'
SOCIAL_AUTH_RAISE_EXCEPTIONS = False
LOGIN_URL = '/user/login'
LOGOUT_URL = '/'
# LOGIN_REDIRECT_URL =  "/user/user-feeds"
LOGIN_REDIRECT_URL =  "/user/dashboard/"
LOGOUT_REDIRECT_URL = "/user/login"
SOCIAL_AUTH_REDIRECT_IS_HTTPS = USE_HTTPS


# Payment Gateway Configuration from Environment
# Gateway Preference: 1=ICICI_EAZYPAY (first preference), 2=RAZORPAY (fallback)
PAYMENT_GATEWAY_PREFERENCE = config('PAYMENT_GATEWAY_PREFERENCE', default=1, cast=int)

# Payment Gateway Environment Mode (sandbox or production)
RAZORPAY_ENVIRONMENT = config('RAZORPAY_ENVIRONMENT', default='sandbox')
ICICI_EAZYPAY_ENVIRONMENT = config('ICICI_EAZYPAY_ENVIRONMENT', default='sandbox')

# Razorpay Configuration - Select keys based on environment
if RAZORPAY_ENVIRONMENT == 'production':
    RAZORPAY_KEY = config('RAZORPAY_PRODUCTION_KEY', default=config('RAZORPAY_KEY', default=''))
    RAZORPAY_SECRET = config('RAZORPAY_PRODUCTION_SECRET', default=config('RAZORPAY_SECRET', default=''))
else:  # sandbox/test mode
    RAZORPAY_KEY = config('RAZORPAY_SANDBOX_KEY', default=config('RAZORPAY_KEY', default=''))
    RAZORPAY_SECRET = config('RAZORPAY_SANDBOX_SECRET', default=config('RAZORPAY_SECRET', default=''))

# For backward compatibility, use RAZORPAY_KEY/SECRET if API_KEY/SECRET not provided
_razorpay_api_key = config('RAZORPAY_API_KEY', default='')
_razorpay_api_secret = config('RAZORPAY_API_SECRET', default='')
RAZORPAY_API_KEY = _razorpay_api_key if _razorpay_api_key else RAZORPAY_KEY
RAZORPAY_API_SECRET = _razorpay_api_secret if _razorpay_api_secret else RAZORPAY_SECRET

# Default password for new users (can be overridden via .env)
DEFAULT_PASSWORD = config('DEFAULT_PASSWORD', default='12345')

# ICICI Eazypay Configuration - Select URLs and keys based on environment
if ICICI_EAZYPAY_ENVIRONMENT == 'production':
    ICICI_EAZYPAY_DEFAULT_BASE_URL = config('ICICI_EAZYPAY_PRODUCTION_BASE_URL', default=config('ICICI_EAZYPAY_DEFAULT_BASE_URL', default='https://eazypay.icicibank.com/EazyPG?'))
    ICICI_EAZYPAY_PAYMENT_MODE = config('ICICI_EAZYPAY_PRODUCTION_PAYMENT_MODE', default=config('ICICI_EAZYPAY_PAYMENT_MODE', default=9, cast=int), cast=int)
    ICICI_EAZYPAY_MERCHANT_ID = config('ICICI_EAZYPAY_PRODUCTION_MERCHANT_ID', default=config('ICICI_EAZYPAY_MERCHANT_ID', default=''))
    ICICI_EAZYPAY_ENCRYPTION_KEY = config('ICICI_EAZYPAY_PRODUCTION_ENCRYPTION_KEY', default=config('ICICI_EAZYPAY_ENCRYPTION_KEY', default=''))
else:  # sandbox/test mode
    ICICI_EAZYPAY_DEFAULT_BASE_URL = config('ICICI_EAZYPAY_SANDBOX_BASE_URL', default=config('ICICI_EAZYPAY_DEFAULT_BASE_URL', default='https://eazypay.icicibank.com/EazyPG?'))
    ICICI_EAZYPAY_PAYMENT_MODE = config('ICICI_EAZYPAY_SANDBOX_PAYMENT_MODE', default=config('ICICI_EAZYPAY_PAYMENT_MODE', default=9, cast=int), cast=int)
    ICICI_EAZYPAY_MERCHANT_ID = config('ICICI_EAZYPAY_SANDBOX_MERCHANT_ID', default=config('ICICI_EAZYPAY_MERCHANT_ID', default=''))
    ICICI_EAZYPAY_ENCRYPTION_KEY = config('ICICI_EAZYPAY_SANDBOX_ENCRYPTION_KEY', default=config('ICICI_EAZYPAY_ENCRYPTION_KEY', default=''))

ICICI_EAZYPAY_BASE_RETURN_URL = config('ICICI_EAZYPAY_BASE_RETURN_URL', default='https://www.topteen.in/payments/payment-success-v2/')
ICICI_EAZYPAY_PAYMENT_SUCESS_RESPONSE_CODE = config('ICICI_EAZYPAY_PAYMENT_SUCESS_RESPONSE_CODE', default='E000')

# Psychometric Test Amounts
STREAM_SORTER_TEST_AMOUNT = config('STREAM_SORTER_TEST_AMOUNT', default=999, cast=int)
CAREER_DIRECTION_TEST_AMOUNT = config('CAREER_DIRECTION_TEST_AMOUNT', default=999, cast=int)

LOGO_URL="https://topteen.in/static/images/logos/topteen-logo-with-text.png"
SITE_NAME="Topteen Careers"
LOGIN_ERROR_URL='/user/login'
CENTRAL_TEST_API_USERNAME="counselcareer1@gmail.com"
CENTRAL_TEST_API_PASSWORD="assessment"
CAREER_INTEREST_ASSESSMENTT_TEST_ID=531
CAREER_INTEREST_ASSESSMENTT_TEST_LANGUAGE_ID=1

SERVER_EMAIL = config('SERVER_EMAIL', default=_TOPTEEN_FROM_EMAIL)
ADMINS=[('Shanti', 'it@canamgroup.com'),
        ('Dev', 'admin@canamgroup.com')]
EXCEPTION_EMAIL_TO = [
    'it@canamgroup.com',
    'admin@canamgroup.com',
]
EMAIL_SUBJECT_PREFIX = '[TopTeen-Exceptions] '

PSYCHOMETRIC_COURSE_FREE_ID=3

DEMO_EMAIL=[]
CREDIT_LIMIT=5000

ENVIRONMENT = config('ENVIRONMENT', default='production')
# Only allow Google (and other search engines) to index when ENVIRONMENT=production in .env
ALLOW_SEARCH_ENGINE_INDEX = (ENVIRONMENT == 'production')

# Enquiry source UTM links: base URL is always www.topteen.in or demo.topteen.in (set in .env per environment).
ENQUIRY_SOURCE_BASE_URL = config('ENQUIRY_SOURCE_BASE_URL', default='https://www.topteen.in').rstrip('/')

# Demo accounts: use DB only (User.is_demo_account, Institute.is_demo_institute). No .env demo credentials.

# Chatbot visibility: home-only | students-parents | institutes | counselors
CHATBOT_VISIBILITY = config('CHATBOT_VISIBILITY', default='home-only')

# AI Counselling Engine (FastAPI microservice)
COUNSELLING_ENGINE_URL = config('COUNSELLING_ENGINE_URL', default='http://localhost:8000')
TOPTEEN_COUNSELLING_API_KEY = config('TOPTEEN_COUNSELLING_API_KEY', default='dev-key')

# Requests to counselling engine: timeout (seconds) and retry attempts
# Increase timeout if engine does heavy work or cold-starts; keep retries small to avoid duplicate work.
COUNSELLING_REQUEST_TIMEOUT = config('COUNSELLING_REQUEST_TIMEOUT', default=60, cast=int)
COUNSELLING_REQUEST_RETRIES = config('COUNSELLING_REQUEST_RETRIES', default=2, cast=int)

# @manish
# Master password settings
MASTER_PASSWORD = config('MASTER_PASSWORD', default='')


# try:
#     from topteens.local_settings import *
# except ImportError:
#     pass

# https://www.topteen.in/psychometrictest/update-psychometric-test-payment-eazypay
# https://www.topteen.in/skilllabcourse/update-skilllab-course-payment
