# Generated by Django 4.0.4 on 2024-10-22 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1)),
                ('counselor_name', models.CharField(max_length=250)),
                ('counselor_email', models.EmailField(max_length=255, null=True, unique=True)),
                ('counselor_address', models.CharField(blank=True, max_length=350, null=True)),
                ('counselor_contact_info', models.CharField(blank=True, max_length=250, null=True)),
                ('counselor_education', models.CharField(blank=True, max_length=250, null=True)),
                ('counselor_gender', models.PositiveSmallIntegerField(choices=[(10, 'Unknown'), (20, 'Male'), (30, 'Female')], default=20)),
                ('counselor_admin', models.ForeignKey(blank=True, limit_choices_to={'user_type': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
