# Generated by Django 4.0.4 on 2024-10-23 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institute', '0003_institutegroup_institute_institute_group'),
        ('counselor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='coun_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='counselor',
            name='counselor_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coun_institute', to='institute.institute'),
        ),
    ]
