# Generated by Django 4.0.4 on 2024-10-30 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_institutegroup_institute_institute_group'),
        ('counselor', '0002_counselor_coun_user_alter_counselor_counselor_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='counselors', to='institute.studentmanagement'),
        ),
        migrations.CreateModel(
            name='FollowUpStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1)),
                ('mode_of_follow_up', models.CharField(choices=[('email', 'Email'), ('call', 'Call'), ('meeting', 'Meeting')], default='Call', max_length=20)),
                ('follow_up_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('follow-up', 'Follow-up')], default='pending', max_length=20)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('last_follow_up_date', models.DateField(blank=True, null=True)),
                ('is_followed_up', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='counselor.counselor')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_statuses', to='institute.studentmanagement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
