#!/usr/bin/env python3
"""
Upload course to database from verified JSON file.
Reads JSON file generated by generate_course_json.py and uploads to database.
"""

import os
import sys
import json
from pathlib import Path
from typing import Optional, Dict, List

# Django setup
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'topteens.settings')

import django
django.setup()

from django.utils.text import slugify
from skilllab.models import (
    SkillLabCourse, SkillLabCourseChapter, SkillLabCourseActivity,
    SkillLabMCQ, SkillLabMCQQuestion, SkillLabMCQAnswer, SkillLabCourseSection
)
from core.utils import choices
from core.s3_utils import get_s3_upload_service
from django.core.files import File


# Configuration
JSON_DIR = Path("/home/itpc6/Public/django/git-repo/7nov/git/new_template-demo-topteens/topteen_1.0/scripts/skilllabcourses_script/course_json")
PROCESSED_DIR = Path("/home/itpc6/Public/django/git-repo/7nov/git/new_template-demo-topteens/topteen_1.0/skilllabcourses_html")
S3_FOLDER = "skilllab_courses"


def get_course_category(course_name: str) -> int:
    """Determine course category based on course name."""
    name_lower = course_name.lower()
    
    if any(keyword in name_lower for keyword in ['class 7', 'class 8', 'career ready']):
        return choices.SkillLabCourseTypeChoice.after_10_class
    elif any(keyword in name_lower for keyword in ['class 12', 'after 12', 'soft skills', 'high school']):
        return choices.SkillLabCourseTypeChoice.after_12_class
    elif any(keyword in name_lower for keyword in ['college', 'graduate', 'post-graduate']):
        return choices.SkillLabCourseTypeChoice.after_college
    else:
        return choices.SkillLabCourseTypeChoice.BOTH


def upload_pdf_to_s3(pdf_path: Path, course_name: str, chapter_num: int, file_type: str) -> Optional[str]:
    """Upload PDF file to S3 and return S3 URL."""
    if not pdf_path.exists():
        return None
    
    try:
        s3_service = get_s3_upload_service()
        if not s3_service.is_enabled():
            print(f"  Warning: S3 upload is disabled. Skipping PDF upload for {pdf_path.name}")
            return None
        
        folder_path = f"{S3_FOLDER}/{slugify(course_name)}/chapter_{chapter_num}"
        
        with open(pdf_path, 'rb') as f:
            file_obj = File(f, name=pdf_path.name)
            result = s3_service.upload_file(
                file_obj=file_obj,
                folder_path=folder_path,
                file_name=pdf_path.name,
                description=f"{file_type.title()} for {course_name} - Chapter {chapter_num}",
                uploaded_by="skilllab_upload_script"
            )
            
            if result.get('success'):
                return result.get('s3_url')
            else:
                print(f"  Error uploading {pdf_path.name} to S3: {result.get('error')}")
                return None
                
    except Exception as e:
        print(f"  Error uploading {pdf_path.name} to S3: {e}")
        import traceback
        traceback.print_exc()
        return None


def combine_chapter_content(intro_html: Optional[str], sections: List[Dict]) -> str:
    """
    Combine chapter intro and sections into full HTML content.
    """
    html_parts = []
    
    # Add intro
    if intro_html:
        html_parts.append(f"<!-- Chapter Introduction -->\n{intro_html}")
    
    # Add sections (h2 headings with content)
    for section in sections:
        html_parts.append(section.get('heading_html', ''))
        html_parts.append(section.get('content_html', ''))
    
    return '\n\n'.join(html_parts)


def upload_course_from_json(json_path: Path, dry_run: bool = False) -> Dict:
    """
    Upload course to database from JSON file.
    """
    stats = {
        'course_name': None,
        'course_id': None,
        'course_created': False,
        'course_updated': False,
        'chapters': [],
        'worksheets': [],
        'mcqs': [],
        'mcq_activities': [],
        'pdfs_uploaded': 0
    }
    
    # Load JSON
    try:
        with open(json_path, 'r', encoding='utf-8') as f:
            course_data = json.load(f)
    except Exception as e:
        print(f"Error reading JSON file: {e}")
        return stats
    
    course_name = course_data.get('course_name')
    stats['course_name'] = course_name
    
    print(f"\n{'[DRY RUN] ' if dry_run else ''}Uploading course from JSON: {course_name}")
    
    # Create or update course
    course_description = course_data.get('course_description', '')
    course_intro_html = course_data.get('course_intro_html', '')
    course_index_html = course_data.get('course_index_html', '')
    category = get_course_category(course_name)
    course_slug = slugify(course_name)
    
    if dry_run:
        print(f"  Would create/update course: {course_name}")
        print(f"    Slug: {course_slug}")
        print(f"    Category: {category}")
        print(f"    Description length: {len(course_description)} chars")
        print(f"    Course intro length: {len(course_intro_html) if course_intro_html else 0} chars")
        print(f"    Course index length: {len(course_index_html) if course_index_html else 0} chars")
    else:
        try:
            course, created = SkillLabCourse.objects.get_or_create(
                slug=course_slug,
                defaults={
                    'name': course_name,
                    'description': course_description,
                    'courseintro': course_intro_html,
                    'index': course_index_html,
                    'category': category,
                    'object_status': choices.ObjectStatus.ACTIVE,
                    'amount': 0,
                    'currency': choices.Currency.IND
                }
            )
            
            if not created:
                course.name = course_name
                course.description = course_description
                course.courseintro = course_intro_html
                course.index = course_index_html
                course.category = category
                course.object_status = choices.ObjectStatus.ACTIVE
                course.save()
                stats['course_id'] = course.id
                stats['course_updated'] = True
                print(f"  Updated existing course: {course_name} (ID: {course.id})")
            else:
                stats['course_id'] = course.id
                stats['course_created'] = True
                print(f"  Created new course: {course_name} (ID: {course.id})")
        except Exception as e:
            print(f"  Error creating/updating course: {e}")
            import traceback
            traceback.print_exc()
            return stats
    
    # Process chapters
    chapters_data = course_data.get('chapters', [])
    
    for chapter_data in chapters_data:
        chapter_num = chapter_data.get('chapter_number')
        chapter_name = chapter_data.get('chapter_name', f"Chapter {chapter_num}")
        
        print(f"  Processing {chapter_name}...")
        
        # Get chapter data
        intro_html = chapter_data.get('intro_html')
        sections = chapter_data.get('sections', [])
        chapter_html = combine_chapter_content(intro_html, sections)
        
        if not chapter_html and not intro_html and not sections:
            print(f"    Warning: No HTML content found for {chapter_name}")
            continue
        
        if dry_run:
            print(f"    Would create/update chapter: {chapter_name}")
            print(f"      Intro HTML length: {len(intro_html) if intro_html else 0} chars")
            print(f"      Sections: {len(sections)}")
            print(f"      Combined content length: {len(chapter_html) if chapter_html else 0} chars")
        else:
            try:
                # Create or update chapter
                chapter, created = SkillLabCourseChapter.objects.get_or_create(
                    skilllab=course,
                    chapter_name=chapter_name,
                    defaults={
                        'intro_html': intro_html,
                        'content': chapter_html,
                        'object_status': choices.ObjectStatus.ACTIVE
                    }
                )
                
                if not created:
                    chapter.intro_html = intro_html
                    chapter.content = chapter_html
                    chapter.object_status = choices.ObjectStatus.ACTIVE
                    chapter.save()
                    
                    # Delete existing sections to recreate them
                    SkillLabCourseSection.objects.filter(skilllab_chapter=chapter).delete()
                    
                    stats['chapters'].append({
                        'name': chapter_name,
                        'id': chapter.id,
                        'created': False,
                        'updated': True,
                        'sections_count': len(sections)
                    })
                    print(f"    Updated existing chapter: {chapter_name} (ID: {chapter.id}, {len(sections)} sections)")
                else:
                    stats['chapters'].append({
                        'name': chapter_name,
                        'id': chapter.id,
                        'created': True,
                        'updated': False,
                        'sections_count': len(sections)
                    })
                    print(f"    Created new chapter: {chapter_name} (ID: {chapter.id}, {len(sections)} sections)")
                
                # Create sections
                sections_created = 0
                sections_updated = 0
                for idx, section_data in enumerate(sections):
                    section_heading = section_data.get('heading', f'Section {idx + 1}')
                    section_heading_html = section_data.get('heading_html', '')
                    section_content = section_data.get('content', '')
                    section_content_html = section_data.get('content_html', '')
                    
                    section, s_created = SkillLabCourseSection.objects.get_or_create(
                        skilllab_chapter=chapter,
                        heading=section_heading,
                        defaults={
                            'heading_html': section_heading_html,
                            'content': section_content,
                            'content_html': section_content_html,
                            'order': idx + 1,
                            'object_status': choices.ObjectStatus.ACTIVE
                        }
                    )
                    
                    if not s_created:
                        section.heading_html = section_heading_html
                        section.content = section_content
                        section.content_html = section_content_html
                        section.order = idx + 1
                        section.object_status = choices.ObjectStatus.ACTIVE
                        section.save()
                        sections_updated += 1
                    else:
                        sections_created += 1
                
                print(f"    Sections: {sections_created} created, {sections_updated} updated (Total: {len(sections)})")
                
            except Exception as e:
                print(f"    Error creating/updating chapter: {e}")
                import traceback
                traceback.print_exc()
                continue
        
        # Process worksheet
        if chapter_data.get('has_worksheet'):
            worksheet_pdf_path = Path(chapter_data.get('worksheet_pdf', ''))
            if worksheet_pdf_path.exists():
                if dry_run:
                    print(f"    Would upload worksheet PDF: {worksheet_pdf_path.name}")
                else:
                    s3_url = upload_pdf_to_s3(worksheet_pdf_path, course_name, chapter_num, 'worksheet')
                    if s3_url:
                        try:
                            activity_name = f"Worksheet - Chapter {chapter_num}"
                            activity, created = SkillLabCourseActivity.objects.get_or_create(
                                skilllab_chapter=chapter,
                                name=activity_name,
                                defaults={
                                    'type': choices.SkillLabAcivityChoice.worksheet,
                                    'content': f'<p>Download worksheet for {chapter_name}</p><p><a href="{s3_url}" target="_blank">Download Worksheet PDF</a></p>',
                                    'object_status': choices.ObjectStatus.ACTIVE
                                }
                            )
                            
                            if not created:
                                activity.content = f'<p>Download worksheet for {chapter_name}</p><p><a href="{s3_url}" target="_blank">Download Worksheet PDF</a></p>'
                                activity.type = choices.SkillLabAcivityChoice.worksheet
                                activity.object_status = choices.ObjectStatus.ACTIVE
                                activity.save()
                                stats['worksheets'].append({
                                    'chapter': chapter_name,
                                    'activity_id': activity.id,
                                    'created': False,
                                    'updated': True,
                                    's3_url': s3_url
                                })
                                print(f"    Updated existing worksheet activity (ID: {activity.id})")
                            else:
                                stats['worksheets'].append({
                                    'chapter': chapter_name,
                                    'activity_id': activity.id,
                                    'created': True,
                                    'updated': False,
                                    's3_url': s3_url
                                })
                                print(f"    Created new worksheet activity (ID: {activity.id})")
                            
                            stats['pdfs_uploaded'] += 1
                        except Exception as e:
                            print(f"    Error creating worksheet activity: {e}")
                            import traceback
                            traceback.print_exc()
        
        # Process MCQ
        if chapter_data.get('has_mcq'):
            mcq_data = chapter_data.get('mcq_data')
            if mcq_data:
                # Upload MCQ PDF if exists
                course_dir = PROCESSED_DIR / course_name
                chapter_dir = course_dir / f"chapter_{chapter_num}"
                mcq_pdf_path = chapter_dir / f"chapter{chapter_num}-mcq.pdf"
                s3_url = None
                if mcq_pdf_path.exists():
                    s3_url = upload_pdf_to_s3(mcq_pdf_path, course_name, chapter_num, 'mcq')
                    if s3_url:
                        stats['pdfs_uploaded'] += 1
                
                if not dry_run:
                    try:
                        mcq_title = mcq_data.get('title', f'MCQ - {chapter_name}')
                        mcq, created = SkillLabMCQ.objects.get_or_create(
                            skilllab_chapter=chapter,
                            defaults={
                                'title': mcq_title,
                                'description': f'<p>MCQ questions for {chapter_name}</p>',
                                'object_status': choices.ObjectStatus.ACTIVE
                            }
                        )
                        
                        if not created:
                            mcq.title = mcq_title
                            mcq.description = f'<p>MCQ questions for {chapter_name}</p>'
                            mcq.save()
                            stats['mcqs'].append({
                                'chapter': chapter_name,
                                'mcq_id': mcq.id,
                                'title': mcq_title,
                                'created': False,
                                'updated': True,
                                'questions_created': 0,
                                'questions_updated': 0,
                                'total_questions': 0
                            })
                            print(f"    Updated existing MCQ: {mcq_title} (ID: {mcq.id})")
                        else:
                            stats['mcqs'].append({
                                'chapter': chapter_name,
                                'mcq_id': mcq.id,
                                'title': mcq_title,
                                'created': True,
                                'updated': False,
                                'questions_created': 0,
                                'questions_updated': 0,
                                'total_questions': 0
                            })
                            print(f"    Created new MCQ: {mcq_title} (ID: {mcq.id})")
                        
                        # Import questions
                        questions_data = mcq_data.get('questions', [])
                        total_questions = len(questions_data)
                        created_questions = 0
                        updated_questions = 0
                        
                        mcq_stat = next((m for m in stats['mcqs'] if m['mcq_id'] == mcq.id), None)
                        if mcq_stat:
                            mcq_stat['total_questions'] = total_questions
                        
                        for q_data in questions_data:
                            question_number = q_data.get('question_number', 0)
                            question_text = q_data.get('question_text', '')
                            
                            question, q_created = SkillLabMCQQuestion.objects.get_or_create(
                                mcq=mcq,
                                question_number=question_number,
                                defaults={
                                    'question_text': question_text,
                                    'order': question_number,
                                    'object_status': choices.ObjectStatus.ACTIVE
                                }
                            )
                            
                            if not q_created:
                                question.question_text = question_text
                                question.order = question_number
                                question.save()
                                updated_questions += 1
                            else:
                                created_questions += 1
                            
                            # Import answers
                            options = q_data.get('options', [])
                            correct_answer = q_data.get('correct_answer', {})
                            correct_letter = correct_answer.get('letter', '') if correct_answer else ''
                            
                            for opt_idx, option in enumerate(options):
                                opt_letter = option.get('letter', '').upper()
                                opt_text = option.get('text', '')
                                is_correct = (opt_letter == correct_letter.upper())
                                
                                answer, a_created = SkillLabMCQAnswer.objects.get_or_create(
                                    question=question,
                                    answer_letter=opt_letter,
                                    defaults={
                                        'answer_text': opt_text,
                                        'is_correct': is_correct,
                                        'order': opt_idx,
                                        'object_status': choices.ObjectStatus.ACTIVE
                                    }
                                )
                                
                                if not a_created:
                                    answer.answer_text = opt_text
                                    answer.is_correct = is_correct
                                    answer.order = opt_idx
                                    answer.save()
                        
                        if mcq_stat:
                            mcq_stat['questions_created'] = created_questions
                            mcq_stat['questions_updated'] = updated_questions
                        
                        print(f"    MCQ Questions: {created_questions} created, {updated_questions} updated (Total: {total_questions})")
                        
                        # Create MCQ activity
                        activity_name = f"MCQ Test - Chapter {chapter_num}"
                        activity_content = f'<p>Take the MCQ test for {chapter_name}</p>'
                        if s3_url:
                            activity_content += f'<p><a href="{s3_url}" target="_blank">Download MCQ PDF</a></p>'
                        
                        activity, created = SkillLabCourseActivity.objects.get_or_create(
                            skilllab_chapter=chapter,
                            name=activity_name,
                            defaults={
                                'type': choices.SkillLabAcivityChoice.activity,
                                'content': activity_content,
                                'object_status': choices.ObjectStatus.ACTIVE
                            }
                        )
                        
                        if not created:
                            activity.content = activity_content
                            activity.type = choices.SkillLabAcivityChoice.activity
                            activity.object_status = choices.ObjectStatus.ACTIVE
                            activity.save()
                            stats['mcq_activities'].append({
                                'chapter': chapter_name,
                                'activity_id': activity.id,
                                'created': False,
                                'updated': True,
                                's3_url': s3_url
                            })
                            print(f"    Updated existing MCQ activity (ID: {activity.id})")
                        else:
                            stats['mcq_activities'].append({
                                'chapter': chapter_name,
                                'activity_id': activity.id,
                                'created': True,
                                'updated': False,
                                's3_url': s3_url
                            })
                            print(f"    Created new MCQ activity (ID: {activity.id})")
                        
                    except Exception as e:
                        print(f"    Error importing MCQ data: {e}")
                        import traceback
                        traceback.print_exc()
    
    return stats


def main():
    """Main upload function."""
    import argparse
    
    parser = argparse.ArgumentParser(description='Upload course from verified JSON file')
    parser.add_argument('--json-file', type=str, help='JSON file name (without path, required if --all not used)')
    parser.add_argument('--all', action='store_true', help='Upload all JSON files')
    parser.add_argument('--dry-run', action='store_true', help='Preview changes without making them')
    args = parser.parse_args()
    
    if not JSON_DIR.exists():
        print(f"Error: JSON directory not found: {JSON_DIR}")
        sys.exit(1)
    
    # Determine which JSON files to process
    if args.all:
        # Get all JSON files
        json_files = list(JSON_DIR.glob("*.json"))
        if not json_files:
            print(f"Error: No JSON files found in {JSON_DIR}")
            sys.exit(1)
        json_files.sort()
        print("=" * 80)
        print("Course Upload from JSON - ALL COURSES")
        print("=" * 80)
        print(f"Found {len(json_files)} JSON files to process")
        print(f"Dry run: {args.dry_run}")
        print()
    else:
        if not args.json_file:
            parser.error("Either --json-file or --all must be specified")
        json_path = JSON_DIR / args.json_file
        if not json_path.exists():
            print(f"Error: JSON file not found: {json_path}")
            sys.exit(1)
        json_files = [json_path]
        print("=" * 80)
        print("Course Upload from JSON")
        print("=" * 80)
        print(f"JSON file: {json_path}")
        print(f"Dry run: {args.dry_run}")
        print()
    
    # Process JSON files
    all_stats = []
    successful = []
    failed = []
    total_files = len(json_files)
    
    for idx, json_path in enumerate(json_files, 1):
        json_filename = json_path.name
        print(f"\n[{idx}/{total_files}] Processing: {json_filename}")
        print("-" * 80)
        
        try:
            stats = upload_course_from_json(json_path, dry_run=args.dry_run)
            all_stats.append(stats)
            
            if stats.get('course_name'):
                successful.append(stats)
                print(f"  ✓ Successfully processed: {stats.get('course_name')}")
            else:
                failed.append(json_filename)
                print(f"  ✗ Failed to process: {json_filename}")
                
        except Exception as e:
            print(f"  ✗ Error processing {json_filename}: {e}")
            import traceback
            traceback.print_exc()
            failed.append(json_filename)
    
    # Display comprehensive summary
    print("\n" + "=" * 80)
    print("UPLOAD SUMMARY")
    print("=" * 80)
    print(f"Total JSON files: {total_files}")
    print(f"Successful: {len(successful)}")
    print(f"Failed: {len(failed)}")
    
    if successful and not args.dry_run:
        print("\n" + "-" * 80)
        print("DETAILED BREAKDOWN BY COURSE")
        print("-" * 80)
        
        total_chapters_created = 0
        total_chapters_updated = 0
        total_worksheets_created = 0
        total_worksheets_updated = 0
        total_mcqs_created = 0
        total_mcqs_updated = 0
        total_pdfs = 0
        
        for stats in successful:
            course_name = stats.get('course_name', 'Unknown')
            course_id = stats.get('course_id')
            course_status = 'CREATED' if stats.get('course_created') else 'UPDATED'
            
            print(f"\nCourse: {course_name}")
            if course_id:
                print(f"  ID: {course_id} | Status: {course_status}")
            
            # Chapters
            chapters = stats.get('chapters', [])
            chapters_created = sum(1 for ch in chapters if ch.get('created'))
            chapters_updated = sum(1 for ch in chapters if ch.get('updated'))
            total_chapters_created += chapters_created
            total_chapters_updated += chapters_updated
            print(f"  Chapters: {len(chapters)} ({chapters_created} created, {chapters_updated} updated)")
            
            # Worksheets
            worksheets = stats.get('worksheets', [])
            worksheets_created = sum(1 for w in worksheets if w.get('created'))
            worksheets_updated = sum(1 for w in worksheets if w.get('updated'))
            total_worksheets_created += worksheets_created
            total_worksheets_updated += worksheets_updated
            print(f"  Worksheets: {len(worksheets)} ({worksheets_created} created, {worksheets_updated} updated)")
            
            # MCQs
            mcqs = stats.get('mcqs', [])
            mcqs_created = sum(1 for m in mcqs if m.get('created'))
            mcqs_updated = sum(1 for m in mcqs if m.get('updated'))
            total_mcqs_created += mcqs_created
            total_mcqs_updated += mcqs_updated
            print(f"  MCQs: {len(mcqs)} ({mcqs_created} created, {mcqs_updated} updated)")
            
            # MCQ Activities
            mcq_activities = stats.get('mcq_activities', [])
            print(f"  MCQ Activities: {len(mcq_activities)}")
            
            # PDFs
            pdfs = stats.get('pdfs_uploaded', 0)
            total_pdfs += pdfs
            print(f"  PDFs Uploaded: {pdfs}")
        
        # Overall totals
        print("\n" + "=" * 80)
        print("OVERALL TOTALS")
        print("=" * 80)
        print(f"Total Courses: {len(successful)}")
        print(f"Total Chapters: {total_chapters_created + total_chapters_updated} ({total_chapters_created} created, {total_chapters_updated} updated)")
        print(f"Total Worksheets: {total_worksheets_created + total_worksheets_updated} ({total_worksheets_created} created, {total_worksheets_updated} updated)")
        print(f"Total MCQs: {total_mcqs_created + total_mcqs_updated} ({total_mcqs_created} created, {total_mcqs_updated} updated)")
        print(f"Total PDFs Uploaded: {total_pdfs}")
    
    if failed:
        print("\n" + "-" * 80)
        print("FAILED FILES")
        print("-" * 80)
        for filename in failed:
            print(f"  - {filename}")
    
    if args.dry_run:
        print("\n" + "=" * 80)
        print("⚠️  This was a DRY RUN. No changes were made to the database.")
        print("=" * 80)
    
    print()


if __name__ == "__main__":
    main()
