from django.contrib import admin
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path("",views.Home.as_view(),name="home"),
    path("searchand-explore/",views.SearchItems.as_view(),name="searchandexplore"),
    path("searchand-explore-result/",views.AjaxSearchResult.as_view(),name="searchandexploreresult"),
    path("recommandedsearch/",views.AjaxRecommandedSearchCollege.as_view(),name="recommandedsearch"),
    path("terms-and-condition/",views.terms_and_condition,name="terms&condition"),
    path("privacy-policy/",views.privacy_policy,name="privacypolicy"),
    path("contact-us/",views.contact_us,name="contactus"),
    path("upload/",views.upload,name="upload"),
    path("about-us/",views.AboutUsView.as_view(),name="aboutus"),
    path("all-faq/",views.AllFaqView.as_view(),name="allfaq"),
    path("extracurricular-activities/", views.ExtracurricularActivitiesView.as_view(), name="extracurricular_activities"),
    path("extracurricular-activities/activity/<int:pk>/", views.ExtracurricularActivityDetailView.as_view(), name="extracurricular_activity_detail"),
    path("vocational-courses/", views.VocationalCoursesView.as_view(), name="vocational_courses"),
    path("vocational-courses/<slug:level_slug>/", views.VocationalCoursesLevelView.as_view(), name="vocational_courses_level"),
    path("vocational-courses/course/<int:pk>/", views.VocationalCourseDetailView.as_view(), name="vocational_course_detail"),
    path("career-planning/", views.CareerPlanningView.as_view(), name="career_planning"),
    path("career-planning/4-year-course-plan/", views.CareerPlanning4YearView.as_view(), name="career_planning_4_year"),
    path("career-planning/class-9/", views.CareerPlanningClass9View.as_view(), name="career_planning_class_9"),
    path("career-planning/class-10/", views.CareerPlanningClass10View.as_view(), name="career_planning_class_10"),
    path("career-planning/class-11/", views.CareerPlanningClass11View.as_view(), name="career_planning_class_11"),
    path("career-planning/class-12/", views.CareerPlanningClass12View.as_view(), name="career_planning_class_12"),
    path("assessments/emotional-intelligences/", views.EmotionalIntelligencesView.as_view(), name="emotional_intelligences"),
    path("assessments/emotional-intelligences/test/", views.EmotionalIntelligencesAssessmentView.as_view(), name="emotional_intelligences_assessment"),
    path("assessments/multiple-intelligences/", views.MultipleIntelligencesView.as_view(), name="multiple_intelligences"),
    path("assessments/multiple-intelligences/test/", views.MultipleIntelligencesAssessmentView.as_view(), name="multiple_intelligences_assessment"),
    path("assessments/multiple-intelligences/test/save/", views.save_mi_assessment, name="save_mi_assessment"),
    path("assessments/multiple-intelligences/test/report-pdf/", views.mi_report_pdf, name="mi_report_pdf"),
    path("assessments/emotional-intelligences/test/save/", views.save_eq_assessment, name="save_eq_assessment"),
    path("assessments/emotional-intelligences/test/report-pdf/", views.eq_report_pdf, name="eq_report_pdf"),
    path("four-pillars-of-learning/", views.FourPillarsOfLearningView.as_view(), name="four_pillars"),
    path("four-pillars-of-learning/pillar/<int:pillar_number>/", views.FourPillarsPillarDetailView.as_view(), name="four_pillars_pillar"),
    path("four-pillars-of-learning/assessment/<slug:pillar_slug>/", views.FourPillarsAssessmentView.as_view(), name="four_pillars_assessment"),
    path("four-pillars-of-learning/assessment/<slug:pillar_slug>/submit/", views.four_pillars_assessment_submit, name="four_pillars_assessment_submit"),
    path("ebooks/", views.EbookListView.as_view(), name="ebook_list"),
    path("ebooks/flip-book/<slug:slug>/", views.EbookDetailView.as_view(), name="ebook_detail"),
    path("delete-history/",views.deletehistory,name="deletehistory"), 
    path("lead-submit/",views.LeadData.as_view(),name="lead_submit"),
    # React game SPA (Career Battle / stream comparison) – serve index.html; assets at /static/game/
    path("career-battle/", views.serve_game_spa, name="language_game"),
    path("career-battle/<path:path>/", views.serve_game_spa, name="language_game_subpath"),
]