# Generated by Django 4.2.23 on 2025-12-13 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('event_type', models.CharField(choices=[('registration', 'User Registration'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('payment_pending', 'Payment Pending'), ('psychometric_test_started', 'Psychometric Test Started'), ('psychometric_test_completed', 'Psychometric Test Completed'), ('course_enrolled', 'Course Enrolled'), ('skilllab_enrolled', 'SkillLab Course Enrolled'), ('institute_student_registered', 'Institute Student Registered'), ('counselor_course_enrolled', 'Counselor Course Enrolled'), ('page_view', 'Page View'), ('download', 'Download'), ('form_submission', 'Form Submission')], db_index=True, max_length=100)),
                ('event_name', models.CharField(db_index=True, max_length=255)),
                ('event_value', models.DecimalField(decimal_places=2, default=0, help_text='Monetary value if applicable', max_digits=10)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event data')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Event',
                'verbose_name_plural': 'User Events',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('session_id', models.CharField(db_index=True, help_text='Unique session identifier', max_length=255)),
                ('page_path', models.CharField(db_index=True, help_text='URL path visited', max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=500, null=True)),
                ('referrer', models.CharField(blank=True, help_text='HTTP referrer', max_length=500, null=True)),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('utm_medium', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('utm_campaign', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('time_on_page', models.IntegerField(default=0, help_text='Time spent on page in seconds')),
                ('is_bounce', models.BooleanField(default=False, help_text='Single page visit')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(db_index=True, help_text='Traffic source', max_length=255)),
                ('medium', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('referrer', models.CharField(blank=True, max_length=500, null=True)),
                ('landing_page', models.CharField(blank=True, max_length=500, null=True)),
                ('first_visit', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('visit_count', models.IntegerField(default=1)),
                ('is_converted', models.BooleanField(db_index=True, default=False, help_text='Converted to customer')),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0, help_text='Revenue from conversion', max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Linked user when they register', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-first_visit'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('cache_type', models.CharField(choices=[('daily_summary', 'Daily Summary'), ('weekly_summary', 'Weekly Summary'), ('monthly_summary', 'Monthly Summary'), ('revenue_report', 'Revenue Report'), ('conversion_funnel', 'Conversion Funnel'), ('traffic_sources', 'Traffic Sources'), ('top_pages', 'Top Pages')], db_index=True, max_length=50)),
                ('date_range_start', models.DateField(db_index=True)),
                ('date_range_end', models.DateField(db_index=True)),
                ('cached_data', models.JSONField(help_text='Cached aggregated data')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Cache expiration time')),
            ],
            options={
                'verbose_name': 'Analytics Cache',
                'verbose_name_plural': 'Analytics Caches',
                'ordering': ['-updated'],
                'indexes': [models.Index(fields=['cache_type', 'date_range_start', 'date_range_end'], name='user_analyt_cache_t_d3c71d_idx'), models.Index(fields=['expires_at'], name='user_analyt_expires_0113a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_pages', models.IntegerField(default=0)),
                ('total_time', models.IntegerField(default=0, help_text='Total session time in seconds')),
                ('entry_page', models.CharField(max_length=500)),
                ('exit_page', models.CharField(blank=True, max_length=500, null=True)),
                ('referrer', models.CharField(blank=True, max_length=500, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('converted', models.BooleanField(db_index=True, default=False, help_text='Did this session convert?')),
                ('journey_path', models.JSONField(default=list, help_text='Sequence of pages visited')),
                ('conversion_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to='user_analytics.userevent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_journeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Journey',
                'verbose_name_plural': 'User Journeys',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['-start_time', 'user'], name='user_analyt_start_t_5a7c7a_idx'), models.Index(fields=['session_id'], name='user_analyt_session_01d0e4_idx'), models.Index(fields=['converted', '-start_time'], name='user_analyt_convert_1d9988_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['-created', 'event_type'], name='user_analyt_created_f240d9_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['user', '-created'], name='user_analyt_user_id_72fda8_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['event_type', 'event_name'], name='user_analyt_event_t_0f4c98_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['session_id', '-created'], name='user_analyt_session_afd5be_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['-created', 'user'], name='user_analyt_created_c51f92_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['session_id', '-created'], name='user_analyt_session_99ea6c_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['utm_source', 'utm_medium'], name='user_analyt_utm_sou_92db2c_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['device_type', '-created'], name='user_analyt_device__efd86c_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['-first_visit', 'is_converted'], name='user_analyt_first_v_1e5d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source', 'medium'], name='user_analyt_source_e4ba89_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='user_analyt_email_52035e_idx'),
        ),
    ]
