# Generated by Django 4.2.23 on 2026-01-14 08:09

from django.db import migrations, models
import django.utils.timezone


def rename_indexes_if_exist(apps, schema_editor):
    """Rename indexes only if they exist"""
    index_mappings = [
        ('user_analy_ga4_cli_idx', 'user_analyt_ga4_cli_d86f7b_idx'),
        ('user_analy_django__idx', 'user_analyt_django__9f54fd_idx'),
        ('user_analy_user_id_idx', 'user_analyt_user_id_ab5708_idx'),
        ('user_analy_date_so_idx', 'user_analyt_date_9b8a7f_idx'),
        ('user_analy_synced__idx', 'user_analyt_synced__24b8f2_idx'),
    ]
    
    with schema_editor.connection.cursor() as cursor:
        for old_name, new_name in index_mappings:
            # Check if old index exists
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'user_analytics_ga4session' 
                AND index_name = %s
            """, [old_name])
            old_exists = cursor.fetchone()[0] > 0
            
            # Check if new index already exists
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'user_analytics_ga4session' 
                AND index_name = %s
            """, [new_name])
            new_exists = cursor.fetchone()[0] > 0
            
            if old_exists and not new_exists:
                cursor.execute(f"ALTER TABLE user_analytics_ga4session RENAME INDEX `{old_name}` TO `{new_name}`")
            elif new_exists:
                # New index already exists, skip
                pass


def reverse_rename_indexes(apps, schema_editor):
    """Reverse rename indexes"""
    index_mappings = [
        ('user_analyt_ga4_cli_d86f7b_idx', 'user_analy_ga4_cli_idx'),
        ('user_analyt_django__9f54fd_idx', 'user_analy_django__idx'),
        ('user_analyt_user_id_ab5708_idx', 'user_analy_user_id_idx'),
        ('user_analyt_date_9b8a7f_idx', 'user_analy_date_so_idx'),
        ('user_analyt_synced__24b8f2_idx', 'user_analy_synced__idx'),
    ]
    
    with schema_editor.connection.cursor() as cursor:
        for new_name, old_name in index_mappings:
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'user_analytics_ga4session' 
                AND index_name = %s
            """, [new_name])
            exists = cursor.fetchone()[0] > 0
            
            if exists:
                cursor.execute(f"ALTER TABLE user_analytics_ga4session RENAME INDEX `{new_name}` TO `{old_name}`")


def _add_created_field_if_not_exists(schema_editor):
    """Add created field only if it doesn't exist"""
    with schema_editor.connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'user_analytics_ga4session' 
            AND COLUMN_NAME = 'created'
        """)
        exists = cursor.fetchone()[0] > 0
        
        if not exists:
            # Add the column
            cursor.execute("""
                ALTER TABLE user_analytics_ga4session 
                ADD COLUMN created DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('user_analytics', '0002_add_ga4_session_and_client_id'),
    ]

    operations = [
        migrations.RunPython(
            rename_indexes_if_exist,
            reverse_rename_indexes,
        ),
        migrations.RunPython(
            lambda apps, schema_editor: _add_created_field_if_not_exists(schema_editor),
            lambda apps, schema_editor: None,  # No reverse needed
        ),
    ]
