# Generated by Django 4.2.23 on 2026-01-14 08:13

from django.db import migrations, models, connection


def add_ga4_client_id_field_safely(apps, schema_editor):
    """Add ga4_client_id column only if it doesn't exist"""
    table_name = 'user_analytics_userjourney'
    column_name = 'ga4_client_id'
    
    with connection.cursor() as cursor:
        if connection.vendor == 'mysql':
            # Check if column exists
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.columns 
                WHERE table_schema = DATABASE() 
                AND table_name = %s
                AND column_name = %s
            """, [table_name, column_name])
            column_exists = cursor.fetchone()[0] > 0
            
            if not column_exists:
                try:
                    # Add column first
                    cursor.execute(f"""
                        ALTER TABLE {table_name} 
                        ADD COLUMN {column_name} VARCHAR(255) NULL
                    """)
                    # Then add index separately
                    try:
                        cursor.execute(f"""
                            CREATE INDEX user_analytics_userjourney_ga4_client_id_idx 
                            ON {table_name} ({column_name})
                        """)
                    except Exception:
                        pass  # Index might already exist or creation failed
                except Exception:
                    pass  # Column might have been created concurrently
        elif connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = %s
                AND column_name = %s
            """, [table_name, column_name])
            column_exists = cursor.fetchone()[0] > 0
            
            if not column_exists:
                try:
                    cursor.execute(f"""
                        ALTER TABLE {table_name} 
                        ADD COLUMN {column_name} VARCHAR(255) NULL
                    """)
                    cursor.execute(f"""
                        CREATE INDEX user_analytics_userjourney_ga4_client_id_idx 
                        ON {table_name} ({column_name})
                    """)
                except Exception:
                    pass
        else:
            # SQLite or other databases
            try:
                cursor.execute(f"""
                    ALTER TABLE {table_name} 
                    ADD COLUMN {column_name} VARCHAR(255) NULL
                """)
            except Exception:
                pass  # Column already exists, skip


def _alter_unique_together_safely(schema_editor):
    """Alter unique together constraint safely - skip if it would cause key length error"""
    # The unique constraint is already handled by the unique index in migration 0002
    # This operation is just for Django's state, so we can skip the database operation
    # The unique index with prefix on entry_page already exists
    pass


def reverse_add_ga4_client_id_field(apps, schema_editor):
    """Reverse migration - remove ga4_client_id column if it exists"""
    table_name = 'user_analytics_userjourney'
    column_name = 'ga4_client_id'
    
    with connection.cursor() as cursor:
        try:
            if connection.vendor == 'mysql':
                cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN {column_name}")
            elif connection.vendor == 'postgresql':
                cursor.execute(f'ALTER TABLE {table_name} DROP COLUMN "{column_name}"')
            else:
                pass  # SQLite doesn't support DROP COLUMN easily
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('user_analytics', '0003_rename_user_analy_ga4_cli_idx_user_analyt_ga4_cli_d86f7b_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_ga4_client_id_field_safely,
                    reverse_add_ga4_client_id_field,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='userjourney',
                    name='ga4_client_id',
                    field=models.CharField(blank=True, db_index=True, help_text='GA4 client ID for session linking', max_length=255, null=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    lambda apps, schema_editor: _alter_unique_together_safely(schema_editor),
                    lambda apps, schema_editor: None,
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='ga4session',
                    unique_together={('ga4_client_id', 'date', 'source', 'country', 'device', 'entry_page')},
                ),
            ],
        ),
    ]
