# Generated by Django 4.2.23 on 2026-01-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_analytics', '0004_userjourney_ga4_client_id_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ga4session',
            new_name='user_analyt_ga4_cli_d86f7b_idx',
            old_name='user_analy_ga4_cli_idx',
        ),
        migrations.RenameIndex(
            model_name='ga4session',
            new_name='user_analyt_django__9f54fd_idx',
            old_name='user_analy_django__idx',
        ),
        migrations.RenameIndex(
            model_name='ga4session',
            new_name='user_analyt_user_id_ab5708_idx',
            old_name='user_analy_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='ga4session',
            new_name='user_analyt_date_9b8a7f_idx',
            old_name='user_analy_date_so_idx',
        ),
        migrations.RenameIndex(
            model_name='ga4session',
            new_name='user_analyt_synced__24b8f2_idx',
            old_name='user_analy_synced__idx',
        ),
        migrations.AddField(
            model_name='ga4session',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='Asia/Kolkata'),
            preserve_default=False,
        ),
    ]
