# Generated by Django 4.2.23 on 2026-01-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_analytics', '0005_rename_user_analy_ga4_cli_idx_user_analyt_ga4_cli_d86f7b_idx_and_more'),
        ('user_analytics', '0008_fix_duplicate_index'),
    ]

    operations = [
    ]
