# Generated by Django 4.2.23 on 2026-01-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_analytics', '0009_merge_20260120_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='event_type',
            field=models.CharField(choices=[('registration', 'User Registration'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('payment_pending', 'Payment Pending'), ('psychometric_test_started', 'Psychometric Test Started'), ('psychometric_test_completed', 'Psychometric Test Completed'), ('result_generated', 'Result Generated'), ('course_enrolled', 'Course Enrolled'), ('skilllab_enrolled', 'SkillLab Course Enrolled'), ('institute_student_registered', 'Institute Student Registered'), ('counselor_course_enrolled', 'Counselor Course Enrolled'), ('page_view', 'Page View'), ('download', 'Download'), ('form_submission', 'Form Submission')], db_index=True, max_length=100),
        ),
    ]
