# Generated by Django 4.0.4 on 2024-09-24 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=3, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('fields', models.TextField()),
                ('best_colleges', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, max_length=300, null=True)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('category', models.CharField(max_length=100)),
                ('test_paper', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test1_complete', models.BooleanField(blank=True, null=True)),
                ('test2_complete', models.BooleanField(blank=True, null=True)),
                ('test3_complete', models.BooleanField(blank=True, null=True)),
                ('numerical_complete', models.BooleanField(blank=True, null=True)),
                ('verbal_complete', models.BooleanField(blank=True, null=True)),
                ('logical_complete', models.BooleanField(blank=True, null=True)),
                ('emotional_complete', models.BooleanField(blank=True, null=True)),
                ('machanical_complete', models.BooleanField(blank=True, null=True)),
                ('language_complete', models.BooleanField(blank=True, null=True)),
                ('spatial_complete', models.BooleanField(blank=True, null=True)),
                
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(max_length=10)),
                ('subjects', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_paper', models.CharField(max_length=100)),
                ('scores', models.JSONField(default=dict)),
                ('results', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(blank=True, max_length=200, null=True)),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to='answer_images/')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
            ],
        ),
        
    ]
