# Generated by Django 4.2.23 on 2026-01-22 08:12

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import skilllab.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLabCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('currency', models.PositiveSmallIntegerField(choices=[(0, 'US Dollar'), (1, 'IND Rupees / INR')], default=1)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=160)),
                ('name_en', models.CharField(max_length=160, null=True)),
                ('image', models.ImageField(max_length=250, null=True, upload_to=skilllab.models.skill_lab_image_directory)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'After 10th'), (2, 'After 12th'), (3, 'After 10th or 12th'), (4, 'After College')], default=2)),
                ('description', ckeditor.fields.RichTextField(null=True)),
                ('courseintro', ckeditor.fields.RichTextField(blank=True, help_text='Course introduction HTML content', null=True)),
                ('index', ckeditor.fields.RichTextField(blank=True, help_text='Course index HTML content', null=True)),
                ('video_url', models.URLField(blank=True, max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillLabCourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('chapter_name', models.CharField(max_length=160)),
                ('intro_html', ckeditor.fields.RichTextField(blank=True, help_text='Chapter introduction HTML content', null=True)),
                ('content', ckeditor.fields.RichTextField(help_text='Full chapter content (includes intro + sections combined)', null=True)),
                ('skilllab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skilllabcoursechapter', to='skilllab.skilllabcourse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillLabMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('skilllab_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='skilllab.skilllabcoursechapter')),
            ],
            options={
                'verbose_name': 'Skill Lab MCQ',
                'verbose_name_plural': 'Skill Lab MCQs',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='SkillLabMCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('question_number', models.PositiveIntegerField(default=1)),
                ('question_text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='skilllab.skilllabmcq')),
            ],
            options={
                'verbose_name': 'MCQ Question',
                'verbose_name_plural': 'MCQ Questions',
                'ordering': ['order', 'question_number'],
                'unique_together': {('mcq', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='SkilllabCoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('currency', models.PositiveSmallIntegerField(choices=[(0, 'US Dollar'), (1, 'IND Rupees / INR')], default=1)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('gateway_receipt', models.CharField(blank=True, max_length=120, null=True)),
                ('is_success', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('skilllab_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skilllabcourpayment', to='skilllab.skilllabcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userskillabcourse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillLabCourseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('type', models.SmallIntegerField(choices=[(1, 'Activity'), (2, 'Worksheet')])),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('downloadable_file', models.FileField(blank=True, max_length=250, null=True, upload_to=skilllab.models.skill_lab_image_directory)),
                ('skilllab_chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skilllabcourseactivity', to='skilllab.skilllabcoursechapter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillLabMCQResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('answers', models.JSONField(default=dict, help_text="User's answers: {question_id: answer_letter}")),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='skilllab.skilllabmcq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skilllab_mcq_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MCQ Result',
                'verbose_name_plural': 'MCQ Results',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', 'mcq'], name='skilllab_sk_user_id_1d5acd_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkillLabMCQAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('answer_letter', models.CharField(help_text='Answer option letter (A, B, C, D, etc.)', max_length=1)),
                ('answer_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='skilllab.skilllabmcqquestion')),
            ],
            options={
                'verbose_name': 'MCQ Answer',
                'verbose_name_plural': 'MCQ Answers',
                'ordering': ['order', 'answer_letter'],
                'unique_together': {('question', 'answer_letter')},
            },
        ),
        migrations.CreateModel(
            name='SkillLabCourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('heading', models.CharField(help_text='Section heading (h2 text)', max_length=500)),
                ('heading_html', models.TextField(blank=True, help_text='Section heading HTML (h2 tag)', null=True)),
                ('content', models.TextField(blank=True, help_text='Section content text', null=True)),
                ('content_html', ckeditor.fields.RichTextField(blank=True, help_text='Section content HTML', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of section within chapter')),
                ('skilllab_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='skilllab.skilllabcoursechapter')),
            ],
            options={
                'verbose_name': 'Course Section',
                'verbose_name_plural': 'Course Sections',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['skilllab_chapter', 'order'], name='skilllab_sk_skillla_0630a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkillLabCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='skilllab.skilllabcoursechapter')),
                ('skilllab_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='skilllab.skilllabcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skilllab_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'skilllab_course'], name='skilllab_sk_user_id_7855b9_idx'), models.Index(fields=['user', 'chapter'], name='skilllab_sk_user_id_975619_idx')],
                'unique_together': {('user', 'chapter')},
            },
        ),
    ]
