# Generated by Django 4.2.23 on 2026-01-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilllab', '0001_initial_fresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllabcoursesection',
            name='heading',
            field=models.CharField(help_text='Section heading (h2 text)', max_length=500),
        ),
    ]
