# Generated by Django 4.2.23 on 2026-01-22 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import skilllab.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skilllab', '0003_increase_heading_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllabcourse',
            name='image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=skilllab.models.skill_lab_image_directory),
        ),
        migrations.CreateModel(
            name='SkillLabCourseSectionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('viewed', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='skilllab.skilllabcoursesection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skilllab_section_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'section'], name='skilllab_sk_user_id_814e03_idx'), models.Index(fields=['section', 'completed'], name='skilllab_sk_section_e7abb8_idx')],
                'unique_together': {('user', 'section')},
            },
        ),
    ]
