# Generated by Django 4.2.23 on 2026-01-22 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skilllab', '0004_add_section_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLabWorksheetProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('downloaded', models.BooleanField(default=False, help_text='Worksheet file has been downloaded')),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False, help_text='Worksheet is completed (download is mandatory)')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='skilllab.skilllabcourseactivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skilllab_worksheet_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Worksheet Progress',
                'verbose_name_plural': 'Worksheet Progress',
                'indexes': [models.Index(fields=['user', 'activity'], name='skilllab_sk_user_id_ecaf17_idx')],
                'unique_together': {('user', 'activity')},
            },
        ),
        migrations.CreateModel(
            name='SkillLabMCQProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='skilllab.skilllabmcq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skilllab_mcq_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MCQ Progress',
                'verbose_name_plural': 'MCQ Progress',
                'indexes': [models.Index(fields=['user', 'mcq'], name='skilllab_sk_user_id_c88119_idx')],
                'unique_together': {('user', 'mcq')},
            },
        ),
    ]
