# Generated by Django 4.2.23 on 2026-01-30 07:15

import ckeditor.fields
from django.db import migrations, models
import skilllab.models


class Migration(migrations.Migration):

    dependencies = [
        ('skilllab', '0005_skilllabworksheetprogress_skilllabmcqprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilllabcoursesection',
            name='skilllab_chapter',
        ),
        migrations.AlterUniqueTogether(
            name='skilllabcoursesectionprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='skilllabcoursesectionprogress',
            name='section',
        ),
        migrations.RemoveField(
            model_name='skilllabcoursesectionprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skilllabmcq',
            name='skilllab_chapter',
        ),
        migrations.AlterUniqueTogether(
            name='skilllabmcqanswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='skilllabmcqanswer',
            name='question',
        ),
        migrations.AlterUniqueTogether(
            name='skilllabmcqprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='skilllabmcqprogress',
            name='mcq',
        ),
        migrations.RemoveField(
            model_name='skilllabmcqprogress',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='skilllabmcqquestion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='skilllabmcqquestion',
            name='mcq',
        ),
        migrations.RemoveField(
            model_name='skilllabmcqresult',
            name='mcq',
        ),
        migrations.RemoveField(
            model_name='skilllabmcqresult',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='skilllabworksheetprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='skilllabworksheetprogress',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='skilllabworksheetprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skilllabcourse',
            name='courseintro',
        ),
        migrations.RemoveField(
            model_name='skilllabcourse',
            name='index',
        ),
        migrations.RemoveField(
            model_name='skilllabcoursechapter',
            name='intro_html',
        ),
        migrations.AlterField(
            model_name='skilllabcourse',
            name='image',
            field=models.ImageField(max_length=250, null=True, upload_to=skilllab.models.skill_lab_image_directory),
        ),
        migrations.AlterField(
            model_name='skilllabcoursechapter',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.DeleteModel(
            name='SkillLabCourseProgress',
        ),
        migrations.DeleteModel(
            name='SkillLabCourseSection',
        ),
        migrations.DeleteModel(
            name='SkillLabCourseSectionProgress',
        ),
        migrations.DeleteModel(
            name='SkillLabMCQ',
        ),
        migrations.DeleteModel(
            name='SkillLabMCQAnswer',
        ),
        migrations.DeleteModel(
            name='SkillLabMCQProgress',
        ),
        migrations.DeleteModel(
            name='SkillLabMCQQuestion',
        ),
        migrations.DeleteModel(
            name='SkillLabMCQResult',
        ),
        migrations.DeleteModel(
            name='SkillLabWorksheetProgress',
        ),
    ]
