# Generated by Django 4.2.23 on 2025-11-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('to', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('response', models.TextField()),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Email'), (2, 'SMS')])),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=500)),
                ('otp', models.CharField(max_length=10)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Email'), (2, 'SMS')])),
            ],
        ),
    ]
