# Generated by Django 4.2.23 on 2026-02-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationlog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Email'), (2, 'SMS')], db_index=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Email'), (2, 'SMS')], db_index=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['type', '-created'], name='communicati_type_53c268_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user', 'type', '-created'], name='communicati_user_d4d250_idx'),
        ),
    ]
