# Generated by Django 4.0.4 on 2026-06-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_add_db_indexes_optimize_queries'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('subject_template', models.CharField(blank=True, default='', help_text='Optional. Empty = built-in default subject. Placeholders: see model docstring.', max_length=255)),
                ('body_html_template', models.TextField(blank=True, default='', help_text='Optional HTML body. Empty = built-in default template file. Placeholders: see model docstring.')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email message template',
                'verbose_name_plural': 'Email message templates',
                'ordering': ('slug',),
            },
        ),
    ]
