# Generated by Django 4.0.4 on 2026-06-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_seed_email_message_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessagetemplate',
            name='body_html_template',
            field=models.TextField(blank=True, default='', help_text='Full HTML email body. Leave empty to use the built-in default file. Use the same placeholders as the subject. See admin instructions above the fields.'),
        ),
        migrations.AlterField(
            model_name='emailmessagetemplate',
            name='subject_template',
            field=models.CharField(blank=True, default='', help_text='Email subject line. Leave empty to use the built-in default. Use {placeholder} style placeholders — see Instructions in admin.', max_length=255),
        ),
    ]
