# Generated by Django 4.2.23 on 2026-07-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0010_reload_email_templates_for_base_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_channel', models.CharField(choices=[('', 'Disabled (no SMS / WhatsApp sends)'), ('sms', 'SMS only'), ('whatsapp', 'WhatsApp only')], default='', help_text='Only one of SMS or WhatsApp can be enabled at a time.', max_length=20)),
                ('sms_provider', models.CharField(default='smartping', help_text='Plug-and-play SMS provider (smartping, plivo, …).', max_length=40)),
                ('whatsapp_provider', models.CharField(default='plivo', help_text='Plug-and-play WhatsApp provider (plivo, …).', max_length=40)),
                ('force_send_non_production', models.BooleanField(default=False, help_text='Allow real sends outside production (DEBUG / non-production). Leave off except for short tests.')),
                ('sms_message_template', models.CharField(default='{otp} is your verification code for TopTeen', help_text='SMS body. Use {otp}. Must match DLT-approved text for India.', max_length=500)),
                ('whatsapp_otp_template', models.CharField(blank=True, default='login_otp_verification', help_text='Approved WhatsApp auth template name (e.g. login_otp_verification).', max_length=200)),
                ('whatsapp_otp_template_lang', models.CharField(blank=True, default='en', help_text='Language code exactly as in Plivo/Meta (en or en_US).', max_length=20)),
                ('smartping_api_url', models.URLField(blank=True, default='https://pgapi.smartping.ai/fe/api/v1/send', max_length=500)),
                ('smartping_username', models.CharField(blank=True, default='', max_length=120)),
                ('smartping_password', models.CharField(blank=True, default='', max_length=120)),
                ('smartping_from', models.CharField(blank=True, default='', max_length=40)),
                ('smartping_dlt_content_id', models.CharField(blank=True, default='', max_length=64)),
                ('smartping_dlt_principal_entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('smartping_unicode', models.CharField(blank=True, default='false', max_length=10)),
                ('plivo_auth_id', models.CharField(blank=True, default='', help_text='Required for Plivo. Empty = Plivo disabled.', max_length=120)),
                ('plivo_auth_token', models.CharField(blank=True, default='', help_text='Required for Plivo. Empty = Plivo disabled.', max_length=120)),
                ('plivo_sms_from', models.CharField(blank=True, default='', help_text='E.164 or alphanumeric sender. Required for Plivo SMS.', max_length=40)),
                ('plivo_whatsapp_from', models.CharField(blank=True, default='', help_text='WABA number E.164. Required for Plivo WhatsApp.', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS & WhatsApp settings',
                'verbose_name_plural': 'SMS & WhatsApp settings',
            },
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Email'), (2, 'SMS'), (3, 'WhatsApp')], db_index=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Email'), (2, 'SMS'), (3, 'WhatsApp')], db_index=True),
        ),
    ]
