# Generated by Django 4.2.23 on 2026-07-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0011_messaging_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagingsettings',
            name='plivo_sms_from',
            field=models.CharField(blank=True, default='', help_text='SMS sender: Plivo number (E.164) or alphanumeric sender ID. Use “Fetch SMS numbers from Plivo” in admin after saving Auth ID/Token, or copy from Plivo Console → Phone Numbers.', max_length=40),
        ),
        migrations.AlterField(
            model_name='messagingsettings',
            name='plivo_whatsapp_from',
            field=models.CharField(blank=True, default='', help_text='WhatsApp sender: WABA-linked number in E.164 (+91…). Not auto-listed by API — copy from Plivo Console → WhatsApp → your business account.', max_length=40),
        ),
    ]
