# Generated by Django 4.2.23 on 2026-07-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0012_messaging_plivo_from_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagingsettings',
            name='sender_mode',
            field=models.CharField(choices=[('production', 'Production numbers (live customer traffic)'), ('testing', 'Testing / trial / sandbox numbers only')], default='production', help_text='Testing numbers (Plivo trial/sandbox, etc.) MUST NOT be used on production. If set to Testing, sends are blocked when ENVIRONMENT=production and DEBUG=False.', max_length=20),
        ),
        migrations.AlterField(
            model_name='messagingsettings',
            name='force_send_non_production',
            field=models.BooleanField(default=False, help_text='Allow real sends outside production (DEBUG / non-production) when using production sender numbers. Leave off except for short tests.'),
        ),
    ]
