# Generated by Django 4.2.23 on 2026-07-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0013_messaging_sender_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagingsettings',
            name='plivo_waba_id',
            field=models.CharField(blank=True, default='', help_text='WhatsApp Business Account ID from Plivo Console → WhatsApp. Required to fetch templates from Plivo.', max_length=120),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='whatsapp_otp_template_preview',
            field=models.TextField(blank=True, default='', help_text='Read-only preview of the approved template body from Plivo ({{1}} = OTP).'),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='whatsapp_otp_template_status',
            field=models.CharField(blank=True, default='', help_text='Last fetched Meta status (APPROVED, PENDING, DRAFT, …).', max_length=40),
        ),
        migrations.AlterField(
            model_name='messagingsettings',
            name='sms_message_template',
            field=models.CharField(default='{otp} is your verification code for TopTeen', help_text='SMS ONLY. Body text with {otp}. Must match DLT-approved SMS text for India. Not used for WhatsApp.', max_length=500),
        ),
        migrations.AlterField(
            model_name='messagingsettings',
            name='whatsapp_otp_template',
            field=models.CharField(blank=True, default='', help_text='WhatsApp Meta/Plivo template name only (e.g. login_otp_verification). Message body is NOT edited here — it comes from the approved provider template. Use “Fetch WhatsApp templates from Plivo”.', max_length=200),
        ),
        migrations.AlterField(
            model_name='messagingsettings',
            name='whatsapp_otp_template_lang',
            field=models.CharField(blank=True, default='en', help_text='Language from the provider template (en / en_US). Filled by fetch.', max_length=20),
        ),
    ]
