INTERNATIONAL_COURSES = [
    {
        "title": "Introduction to FinTech",
        "description": "Learn from global experts about the innovations, technologies, and regulations shaping the future of finance.",
        "url": "https://www.coursera.org/learn/introduction-fintech",
        "image": "images_new/thirdparty/course-img-1.png",
        "logo": "images_new/thirdparty/logo.png",
        "subject": "Finance",
        "institute": "The University of Hong Kong",
    },
    {
        "title": "Gemini in Google Slides",
        "description": "Discover how Gemini's generative AI features can be used to improve your productivity and efficiency in Google Slides.",
        "url": "https://www.coursera.org/",
        "image": "images_new/thirdparty/course-img-1.png",
        "logo": "images_new/thirdparty/logo.png",
        "subject": "Technology",
        "institute": "Google Cloud",
    },
    {
        "title": "Academic Writing",
        "description": "Develop academic writing skills and learn the ethical use of AI for success in higher education.",
        "url": "https://www.coursera.org/",
        "image": "images_new/thirdparty/course-img-1.png",
        "logo": "images_new/thirdparty/logo.png",
        "subject": "Writing",
        "institute": "University of Adelaide",
    },
    {
        "title": "Soft Skills: People and Power Skills Assessment",
        "description": "Apply your People and Power Skills knowledge in a final assessment.",
        "url": "https://www.coursera.org/",
        "image": "images_new/thirdparty/course-img-1.png",
        "logo": "images_new/thirdparty/logo.png",
        "subject": "Business",
        "institute": "IBM",
    },
    {
        "title": "Python for Everybody",
        "description": "Learn to program and analyze data with Python. Develop programs to gather, clean, analyze, and visualize data.",
        "url": "https://www.coursera.org/specializations/python",
        "image": "images_new/thirdparty/course-img-1.png",
        "logo": "images_new/thirdparty/logo.png",
        "subject": "Technology",
        "institute": "University of Michigan",
    },
    {
        "title": "Introduction to Computer Science",
        "description": "An introduction to the intellectual enterprises of computer science and the art of programming.",
        "url": "https://www.edx.org/learn/computer-science/harvard-university-cs50-s-introduction-to-computer-science",
        "image": "images_new/thirdparty/course-img-1.png",
        "logo": "images_new/thirdparty/logo.png",
        "subject": "Technology",
        "institute": "Harvard University",
    },
    {
        "title": "Data Science Fundamentals",
        "description": "Build foundational data science skills including data analysis, visualization, and machine learning basics.",
        "url": "https://www.coursera.org/",
        "image": "images_new/thirdparty/course-img-1.png",
        "logo": "images_new/thirdparty/logo.png",
        "subject": "Data Science",
        "institute": "IBM",
    },
    {
        "title": "Digital Marketing",
        "description": "Master the fundamentals of digital marketing including SEO, social media, and content strategy.",
        "url": "https://www.coursera.org/",
        "image": "images_new/thirdparty/course-img-1.png",
        "logo": "images_new/thirdparty/logo.png",
        "subject": "Marketing",
        "institute": "Google",
    },
    {
        "title": "Financial Markets",
        "description": "Gain a deeper understanding of financial markets, instruments, and institutions from Yale experts.",
        "url": "https://www.coursera.org/",
        "image": "images_new/thirdparty/course-img-1.png",
        "logo": "images_new/thirdparty/logo.png",
        "subject": "Finance",
        "institute": "Yale University",
    },
    {
        "title": "Machine Learning",
        "description": "Learn the foundations of machine learning and build practical models with real-world datasets.",
        "url": "https://www.coursera.org/",
        "image": "images_new/thirdparty/course-img-1.png",
        "logo": "images_new/thirdparty/logo.png",
        "subject": "Data Science",
        "institute": "Stanford University",
    },
    {
        "title": "Creative Writing",
        "description": "Explore storytelling techniques and develop your voice through guided writing exercises.",
        "url": "https://www.coursera.org/",
        "image": "images_new/thirdparty/course-img-1.png",
        "logo": "images_new/thirdparty/logo.png",
        "subject": "Writing",
        "institute": "Wesleyan University",
    },
    {
        "title": "Entrepreneurship Essentials",
        "description": "Learn how to launch and grow a venture with frameworks used by leading business schools.",
        "url": "https://www.coursera.org/",
        "image": "images_new/thirdparty/course-img-1.png",
        "logo": "images_new/thirdparty/logo.png",
        "subject": "Business",
        "institute": "Harvard University",
    },
    {
        "title": "UX Design Fundamentals",
        "description": "Understand user-centered design principles and create intuitive digital experiences.",
        "url": "https://www.coursera.org/",
        "image": "images_new/thirdparty/course-img-1.png",
        "logo": "images_new/thirdparty/logo.png",
        "subject": "Design",
        "institute": "Google",
    },
    {
        "title": "International Relations",
        "description": "Analyze global politics, diplomacy, and international cooperation in the modern world.",
        "url": "https://www.coursera.org/",
        "image": "images_new/thirdparty/course-img-1.png",
        "logo": "images_new/thirdparty/logo.png",
        "subject": "Social Sciences",
        "institute": "University of London",
    },
    {
        "title": "Cloud Computing Basics",
        "description": "Explore cloud models, services, and deployment strategies for modern applications.",
        "url": "https://www.coursera.org/",
        "image": "images_new/thirdparty/course-img-1.png",
        "logo": "images_new/thirdparty/logo.png",
        "subject": "Technology",
        "institute": "Google Cloud",
    },
    {
        "title": "Project Management",
        "description": "Build essential project management skills to plan, execute, and deliver successful outcomes.",
        "url": "https://www.coursera.org/",
        "image": "images_new/thirdparty/course-img-1.png",
        "logo": "images_new/thirdparty/logo.png",
        "subject": "Business",
        "institute": "IBM",
    },
]

INTERNATIONAL_COURSE_SUBJECTS = sorted({course["subject"] for course in INTERNATIONAL_COURSES})
INTERNATIONAL_COURSE_INSTITUTES = sorted({course["institute"] for course in INTERNATIONAL_COURSES})
