# Generated by Django 4.2.23 on 2026-01-30 07:46

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import skilllab.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLabCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('currency', models.PositiveSmallIntegerField(choices=[(0, 'US Dollar'), (1, 'IND Rupees / INR')], default=1)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=160)),
                ('name_en', models.CharField(max_length=160, null=True)),
                ('image', models.ImageField(max_length=250, null=True, upload_to=skilllab.models.skill_lab_image_directory)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'After 10th'), (2, 'After 12th'), (3, 'After 10th or 12th'), (4, 'After College')], default=2)),
                ('description', ckeditor.fields.RichTextField(null=True)),
                ('video_url', models.URLField(blank=True, max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkilllabCoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('currency', models.PositiveSmallIntegerField(choices=[(0, 'US Dollar'), (1, 'IND Rupees / INR')], default=1)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('gateway_receipt', models.CharField(blank=True, max_length=120, null=True)),
                ('is_success', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('skilllab_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skilllabcourpayment', to='skilllab.skilllabcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userskillabcourse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillLabCourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('chapter_name', models.CharField(max_length=160)),
                ('content', ckeditor.fields.RichTextField(null=True)),
                ('skilllab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skilllabcoursechapter', to='skilllab.skilllabcourse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillLabCourseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('type', models.SmallIntegerField(choices=[(1, 'Activity'), (2, 'Worksheet')])),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('downloadable_file', models.FileField(blank=True, max_length=250, null=True, upload_to=skilllab.models.skill_lab_image_directory)),
                ('skilllab_chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skilllabcourseactivity', to='skilllab.skilllabcoursechapter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
