# Generated by Django 4.2.23 on 2026-01-31 06:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skilllab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLabMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('skilllab_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='skilllab.skilllabcoursechapter')),
            ],
            options={
                'verbose_name': 'Skill Lab MCQ',
                'verbose_name_plural': 'Skill Lab MCQs',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='SkillLabMCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('question_number', models.PositiveIntegerField(default=1)),
                ('question_text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='skilllab.skilllabmcq')),
            ],
            options={
                'verbose_name': 'MCQ Question',
                'verbose_name_plural': 'MCQ Questions',
                'ordering': ['order', 'question_number'],
                'unique_together': {('mcq', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='SkillLabMCQAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('answer_letter', models.CharField(help_text='Answer option letter (A, B, C, D, etc.)', max_length=1)),
                ('answer_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='skilllab.skilllabmcqquestion')),
            ],
            options={
                'verbose_name': 'MCQ Answer',
                'verbose_name_plural': 'MCQ Answers',
                'ordering': ['order', 'answer_letter'],
                'unique_together': {('question', 'answer_letter')},
            },
        ),
    ]
