# Generated by Django 4.2.23 on 2025-11-17 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skilllab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skilllabcoursepayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userskillabcourse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skilllabcoursechapter',
            name='skilllab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skilllabcoursechapter', to='skilllab.skilllabcourse'),
        ),
        migrations.AddField(
            model_name='skilllabcourseactivity',
            name='skilllab_chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skilllabcourseactivity', to='skilllab.skilllabcoursechapter'),
        ),
    ]
