# Generated by Django 4.2.23 on 2026-01-31 07:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skilllab', '0002_add_skilllab_mcq_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilllabcourse',
            name='course_index_html',
            field=ckeditor.fields.RichTextField(blank=True, help_text='HTML for Course Index tab', null=True),
        ),
        migrations.AddField(
            model_name='skilllabcourse',
            name='course_intro_html',
            field=ckeditor.fields.RichTextField(blank=True, help_text='HTML for Course Introduction tab', null=True),
        ),
        migrations.AlterField(
            model_name='skilllabcourse',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
