# Generated by Django 4.2.23 on 2026-01-31 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skilllab', '0003_add_course_intro_index_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllabcourseactivity',
            name='skilllab_chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skilllabcourseactivity', to='skilllab.skilllabcoursechapter'),
        ),
        migrations.AlterField(
            model_name='skilllabcoursechapter',
            name='skilllab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skilllabcoursechapter', to='skilllab.skilllabcourse'),
        ),
    ]
