# Generated by Django 4.2.23 on 2026-01-31 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skilllab', '0004_cascade_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLabCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skilllabcourseprogress', to='skilllab.skilllabcoursechapter')),
                ('skilllab_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skilllabcourseprogress', to='skilllab.skilllabcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skilllabcourseprogress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Lab Course Progress',
                'verbose_name_plural': 'Skill Lab Course Progress',
                'indexes': [models.Index(fields=['user', 'skilllab_course'], name='skilllab_sk_user_id_7855b9_idx')],
                'unique_together': {('user', 'skilllab_course', 'chapter')},
            },
        ),
    ]
