# Generated by Django 4.2.23 on 2026-01-31 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skilllab', '0005_skilllabcourseprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLabMCQAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skilllabmcqattempts', to='skilllab.skilllabmcq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skilllabmcqattempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Lab MCQ Attempt',
                'verbose_name_plural': 'Skill Lab MCQ Attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillLabWorksheetProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skilllabworksheetprogress', to='skilllab.skilllabcourseactivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skilllabworksheetprogress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Lab Worksheet Progress',
                'verbose_name_plural': 'Skill Lab Worksheet Progress',
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
