# Generated by Django 4.2.23 on 2026-01-31 09:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skilllab', '0006_worksheet_mcq_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllabcoursechapter',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Legacy: full chapter content. Used when no sections exist.', null=True),
        ),
        migrations.CreateModel(
            name='SkillLabChapterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within chapter')),
                ('title', models.CharField(help_text='Section title (from heading or auto-generated)', max_length=255)),
                ('content', ckeditor.fields.RichTextField(help_text='HTML content for this section')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='skilllab.skilllabcoursechapter')),
            ],
            options={
                'verbose_name': 'Skill Lab Chapter Section',
                'verbose_name_plural': 'Skill Lab Chapter Sections',
                'ordering': ['chapter', 'order'],
                'unique_together': {('chapter', 'order')},
            },
        ),
    ]
