# Generated by Django 4.2.23 on 2026-01-31 09:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skilllab', '0007_add_chapter_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllabchaptersection',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='HTML content for this section'),
        ),
    ]
