# Generated by Django 4.2.23 on 2026-01-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilllab', '0008_chapter_section_content_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilllabchaptersection',
            name='section_type',
            field=models.CharField(choices=[('introduction', 'Introduction'), ('section', 'Section')], default='section', help_text='Introduction (first) or Section (1, 2, 3...)', max_length=20),
        ),
        migrations.AlterField(
            model_name='skilllabchaptersection',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order: 0=Introduction, 1+=Section 1, 2, 3...'),
        ),
    ]
