# Generated by Django 4.2.23 on 2026-01-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilllab', '0010_set_introduction_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllabchaptersection',
            name='section_type',
            field=models.CharField(choices=[('introduction', 'Introduction'), ('section', 'Section'), ('chapter_wrap_up', 'Chapter Wrap-Up')], default='section', help_text='Introduction (first) or Section (1, 2, 3...)', max_length=20),
        ),
    ]
