# Generated by Django 4.2.23 on 2026-01-31 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skilllab', '0011_add_chapter_wrap_up_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLabCourseResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('last_section_index', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skilllab_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skilllabcourseresume', to='skilllab.skilllabcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skilllabcourseresume', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Lab Course Resume',
                'verbose_name_plural': 'Skill Lab Course Resume',
                'indexes': [models.Index(fields=['user', 'skilllab_course'], name='skilllab_sk_user_id_1078fe_idx')],
                'unique_together': {('user', 'skilllab_course')},
            },
        ),
    ]
