# Generated by Django 4.2.23 on 2026-01-31 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skilllab', '0012_add_course_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLabCourseProgressSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('completed_sections_count', models.PositiveIntegerField(default=0)),
                ('total_sections_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skilllab_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skilllabcourseprogresssummary', to='skilllab.skilllabcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skilllabcourseprogresssummary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Lab Course Progress Summary',
                'verbose_name_plural': 'Skill Lab Course Progress Summary',
                'indexes': [models.Index(fields=['user', 'skilllab_course'], name='skilllab_sk_user_id_8cb83e_idx')],
                'unique_together': {('user', 'skilllab_course')},
            },
        ),
    ]
