# Generated by Django 4.2.23 on 2026-02-23 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skilllab', '0014_add_missing_mcq_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLabUserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('section_type', models.CharField(max_length=20)),
                ('section_id', models.PositiveIntegerField()),
                ('section_step', models.PositiveIntegerField(blank=True, null=True)),
                ('note_text', models.TextField()),
                ('anchor_text', models.TextField(blank=True)),
                ('skilllab_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to='skilllab.skilllabcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skilllab_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Lab User Note',
                'verbose_name_plural': 'Skill Lab User Notes',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['user', 'skilllab_course', 'section_type', 'section_id'], name='skilllab_sk_user_id_6ab7bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkillLabUserHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('section_type', models.CharField(max_length=20)),
                ('section_id', models.PositiveIntegerField()),
                ('section_step', models.PositiveIntegerField(blank=True, null=True)),
                ('highlighted_text', models.TextField()),
                ('color', models.CharField(default='yellow', max_length=20)),
                ('skilllab_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_highlights', to='skilllab.skilllabcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skilllab_highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Lab User Highlight',
                'verbose_name_plural': 'Skill Lab User Highlights',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['user', 'skilllab_course', 'section_type', 'section_id'], name='skilllab_sk_user_id_d832cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkillLabUserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('section_type', models.CharField(max_length=20)),
                ('section_id', models.PositiveIntegerField()),
                ('section_step', models.PositiveIntegerField(blank=True, null=True)),
                ('section_title', models.CharField(max_length=255)),
                ('section_key', models.CharField(blank=True, max_length=80)),
                ('skilllab_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookmarks', to='skilllab.skilllabcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skilllab_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Lab User Bookmark',
                'verbose_name_plural': 'Skill Lab User Bookmarks',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['user', 'skilllab_course'], name='skilllab_sk_user_id_65b9b5_idx')],
                'unique_together': {('user', 'skilllab_course', 'section_key')},
            },
        ),
    ]
