# Generated by Django 4.2.23 on 2026-02-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilllab', '0015_add_user_highlight_note_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilllabusernote',
            name='name',
            field=models.CharField(blank=True, help_text='Note title or name', max_length=255),
        ),
    ]
