# Generated by Django 4.2.23 on 2026-02-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilllab', '0016_add_note_name_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllabcourse',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'After 10th'), (2, 'After 12th'), (3, 'After 10th or 12th'), (4, 'After College')], db_index=True, default=2),
        ),
        migrations.AddIndex(
            model_name='skilllabcourse',
            index=models.Index(fields=['category', '-modified'], name='skilllab_sk_categor_28f769_idx'),
        ),
    ]
