# Generated by Django 4.0.4 on 2026-06-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilllab', '0019_internationalonlinecourse_upload_images'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='internationalonlinecourse',
            name='skilllab_in_subject_8f3a21_idx',
        ),
        migrations.AlterField(
            model_name='internationalonlinecourse',
            name='object_status',
            field=models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1),
        ),
        migrations.AddIndex(
            model_name='internationalonlinecourse',
            index=models.Index(fields=['subject', 'institute'], name='skilllab_in_subject_ee023a_idx'),
        ),
    ]
