# Generated by Django 4.0.4 on 2026-07-02 13:32

import re

from django.db import migrations, models
import django.db.models.deletion


def seed_grades_and_categories_and_backfill(apps, schema_editor):
    from skilllab.models import (
        SkillLabCourse,
        SkillLabCourseGrade,
        SkillLabCourseTopicCategory,
    )

    for n in range(6, 13):
        if n % 100 // 10 == 1:
            suffix = 'th'
        else:
            suffix = {1: 'st', 2: 'nd', 3: 'rd'}.get(n % 10, 'th')
        SkillLabCourseGrade.objects.get_or_create(
            grade_number=n,
            defaults={'name': f'Class {n}{suffix}', 'sort_order': n},
        )

    for slug, name, order in (
        ('career', 'Career', 1),
        ('skills', 'Skills', 2),
        ('life-skills', 'Life Skills', 3),
        ('future-readiness', 'Future readiness', 4),
    ):
        SkillLabCourseTopicCategory.objects.get_or_create(
            slug=slug,
            defaults={'name': name, 'sort_order': order},
        )

    grade_by_num = {g.grade_number: g for g in SkillLabCourseGrade.objects.all()}
    cat_by_slug = {c.slug: c for c in SkillLabCourseTopicCategory.objects.all()}

    for course in SkillLabCourse.objects.all():
        grade_nums = set(course.get_grade_numbers())
        intro_blob = ' '.join(
            part for part in (course.course_intro_html, course.description, course.name) if part
        ).lower()
        for n in range(6, 13):
            if re.search(rf'\b(class|grade)\s*{n}\b', intro_blob):
                grade_nums.add(n)

        course.grades.set([grade_by_num[n] for n in sorted(grade_nums) if n in grade_by_num])

        topic_key = course.get_topic_category_key()
        if topic_key in cat_by_slug:
            course.topic_category = cat_by_slug[topic_key]
            course.save(update_fields=['topic_category'])


class Migration(migrations.Migration):

    dependencies = [
        ('skilllab', '0020_remove_internationalonlinecourse_skilllab_in_subject_8f3a21_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLabCourseGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('name', models.CharField(help_text='Display label, e.g. "Class 6"', max_length=32)),
                ('grade_number', models.PositiveSmallIntegerField(db_index=True, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill Lab class',
                'verbose_name_plural': 'Skill Lab classes',
                'ordering': ['sort_order', 'grade_number'],
            },
        ),
        migrations.CreateModel(
            name='SkillLabCourseTopicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active'), (2, 'Inactive')], default=1)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill Lab topic category',
                'verbose_name_plural': 'Skill Lab topic categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='skilllabcourse',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'After 10th'), (2, 'After 12th'), (3, 'After 10th or 12th'), (4, 'After College')], db_index=True, default=2, help_text='Audience tier (parent dashboard / access). Use Classes and Topic category below for catalog filters.'),
        ),
        migrations.AddField(
            model_name='skilllabcourse',
            name='grades',
            field=models.ManyToManyField(blank=True, help_text='Class levels this course is for (6–12). Shown on course cards and used in search filters.', related_name='courses', to='skilllab.skilllabcoursegrade'),
        ),
        migrations.AddField(
            model_name='skilllabcourse',
            name='topic_category',
            field=models.ForeignKey(blank=True, help_text='Topic category for catalog filters (Career, Skills, Life Skills, Future readiness).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='skilllab.skilllabcoursetopiccategory'),
        ),
        migrations.RunPython(seed_grades_and_categories_and_backfill, migrations.RunPython.noop),
    ]
