# Generated by Django 4.0.4 on 2026-07-04 08:55

from django.db import migrations, models
import django.db.models.deletion


def add_mcq_chapter_foreign_key(apps, schema_editor):
    if schema_editor.connection.vendor != 'mysql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.TABLE_CONSTRAINTS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = 'skilllab_skilllabmcq'
              AND CONSTRAINT_NAME = 'skilllab_skilllabmcq_chapter_id_fk'
            """
        )
        if cursor.fetchone()[0]:
            return
        cursor.execute(
            """
            ALTER TABLE skilllab_skilllabmcq
            ADD CONSTRAINT skilllab_skilllabmcq_chapter_id_fk
            FOREIGN KEY (skilllab_chapter_id) REFERENCES skilllab_skilllabcoursechapter (id)
            ON DELETE CASCADE
            """
        )


def drop_mcq_chapter_foreign_key(apps, schema_editor):
    if schema_editor.connection.vendor != 'mysql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.TABLE_CONSTRAINTS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = 'skilllab_skilllabmcq'
              AND CONSTRAINT_NAME = 'skilllab_skilllabmcq_chapter_id_fk'
            """
        )
        if not cursor.fetchone()[0]:
            return
        cursor.execute(
            """
            ALTER TABLE skilllab_skilllabmcq
            DROP FOREIGN KEY skilllab_skilllabmcq_chapter_id_fk
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('skilllab', '0021_skilllab_course_class_and_topic_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllabcoursepayment',
            name='is_success',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='skilllabcourseactivity',
            index=models.Index(fields=['skilllab_chapter', 'type'], name='skilllab_sk_skillla_08f80b_idx'),
        ),
        migrations.AddIndex(
            model_name='skilllabcoursechapter',
            index=models.Index(fields=['skilllab', 'created'], name='skilllab_sk_skillla_629de0_idx'),
        ),
        migrations.AddIndex(
            model_name='skilllabcoursepayment',
            index=models.Index(fields=['user', 'skilllab_course', 'is_success'], name='skilllab_sk_user_id_b27000_idx'),
        ),
        migrations.AddIndex(
            model_name='skilllabcourseprogress',
            index=models.Index(fields=['user', 'chapter'], name='skilllab_sk_user_id_975619_idx'),
        ),
        migrations.AddIndex(
            model_name='skilllabmcq',
            index=models.Index(fields=['skilllab_chapter'], name='skilllab_sk_skillla_ae8449_idx'),
        ),
        migrations.RunPython(add_mcq_chapter_foreign_key, drop_mcq_chapter_foreign_key),
        migrations.AlterField(
            model_name='skilllabmcq',
            name='skilllab_chapter',
            field=models.ForeignKey(
                blank=True,
                db_index=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='mcqs',
                to='skilllab.skilllabcoursechapter',
            ),
        ),
        migrations.AddIndex(
            model_name='skilllabmcqattempt',
            index=models.Index(fields=['user', 'mcq'], name='skilllab_sk_user_id_a8f6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='skilllabmcqattempt',
            index=models.Index(fields=['user', 'mcq', '-attempted_at'], name='skilllab_sk_user_id_9041d0_idx'),
        ),
        migrations.AddIndex(
            model_name='skilllabuserhighlight',
            index=models.Index(fields=['user', 'skilllab_course', 'section_type', 'section_id', 'section_step'], name='skilllab_sk_hl_section_idx'),
        ),
        migrations.AddIndex(
            model_name='skilllabusernote',
            index=models.Index(fields=['user', 'skilllab_course', 'section_type', 'section_id', 'section_step'], name='skilllab_sk_nt_section_idx'),
        ),
        migrations.RemoveIndex(
            model_name='skilllabuserhighlight',
            name='skilllab_sk_user_id_d832cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='skilllabusernote',
            name='skilllab_sk_user_id_6ab7bf_idx',
        ),
    ]
