# Generated by Django 4.2.23 on 2026-07-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skilllab', '0002_initial'),
        ('skilllab', '0023_skilllabcertification'),
    ]

    operations = [
    ]
