  name: Deploy to AWS
  on:
    push:
      branches:
        - master
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Set up SSH
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_ed25519_github_devtopteen
            chmod 600 ~/.ssh/id_ed25519_github_devtopteen
            ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
        - name: Validate SSH Key
          run: |
            if [ ! -s ~/.ssh/id_ed25519_github_devtopteen ]; then
              echo "SSH key is missing or empty!"
              exit 1
            fi
        - name: Debug SSH
          run: |
            ssh -i ~/.ssh/id_ed25519_github_devtopteen -v ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} true
        - name: Deploy to AWS
          run: |
            ssh -i ~/.ssh/id_ed25519_github_devtopteen ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
              cd /home/ubuntu/topteens_new/topteen_1.0/
              source /home/ubuntu/topteens_new/env1.0/bin/activate
              git pull origin master
              pip install -r requirements.txt
              python3 manage.py makemigrations
              python3 manage.py migrate
              python3 manage.py collectstatic --noinput
              deactivate
              sudo systemctl stop topteen-new-website.socket
              sudo systemctl disable topteen-new-website.socket
              sudo systemctl stop topteen-new-website.service
              sudo systemctl disable topteen-new-website.service

              sudo systemctl enable topteen-new-website.socket
              sudo systemctl start topteen-new-website.socket
              sudo systemctl enable topteen-new-website.service
              sudo systemctl start topteen-new-website.service
              sudo systemctl restart nginx
            EOF